"""The curated seed: the water bodies a European traveller has actually heard of.

Everything else in this layer is machine found. This file is the one place a
human decides, and it exists for three reasons the open data cannot cover on
its own.

  fame that no field carries.  Sitelinks and pageviews find Lake Garda. They
        do not reliably find Lago di Sorapis, Rummu quarry, Sorvagsvatn or the
        Blue Eye, which are on every travel blog and every second Instagram
        grid and which Wikidata records as small, ordinary items. A ranking
        that misses those is wrong in the way a traveller notices first.
  every country gets an answer.  The gate in export_lakes.py would otherwise
        publish thirty Alpine lakes and nothing for Malta, Moldova or the
        Faroes. Each seeded entry is pinned into its country's list, so a
        country with four honest water bodies shows four rather than none.
  swimming permission is safety critical.  Plitvice, Morskie Oko, Strbske
        pleso, Skradinski Buk, Loch Katrine and most drinking water reservoirs
        forbid swimming, and several of them are on exactly the lists that
        call them beautiful. `swim` here OVERRIDES every machine signal,
        because a wrong "yes" is the only field in this layer that can hurt
        somebody.

Fields
    n       the searchable name, English where an English name is in use
    alt     other names to match on: the local name, the name on the signpost
    cc      ISO2, the country the entry is published under
    kind    lake | reservoir | lagoon | tarn | crater | river | geothermal
    swim    yes | limited | no | "" (unknown, the machine decides)
              yes      swimming is normal and lawful here
              limited  lawful only in a designated part, or in season, or the
                       famous part of it is closed, or the rule could not be
                       confirmed and the honest answer is "check locally"
              no       forbidden, or physically not a swimming place
    lat/lon approximate, ONLY a disambiguation hint for the resolver. Never
            published: the coordinate that ships is Wikidata's or OSM's.
    wd      an explicit Wikidata id, for the few entries entity search cannot
            reach on any query string. Use it sparingly and only after
            checking the item is the right one.
    why     brief     named in the research brief this layer was built from
            editorial added here because it is what blogs and Instagram name
    haz     curated hazards, merged with whatever the machine finds
    note    why this entry is here, for the next person reading the file.
            Internal. It is never shipped, and no sentence in the app is
            written from it.

Where a rule could not be confirmed the entry says "limited" and the app says
"check the local rules", which is both the honest answer and the safe one.

ASCII clean, no em dashes, per project convention.
"""

SEED = [
    # ---------------------------------------------------------------- AD ----
    {"n": "Lake Engolasters", "alt": ["Estany d'Engolasters"], "cc": "AD",
     "kind": "reservoir", "swim": "no", "lat": 42.51, "lon": 1.57, "why": "brief",
     "note": "hydroelectric reservoir, swimming discouraged and not provided for"},
    {"n": "Estany de Juclar", "cc": "AD", "kind": "tarn", "swim": "limited",
     "lat": 42.62, "lon": 1.72, "why": "brief", "haz": ["cold_shock"],
     "note": "high alpine tarn above 2,300 m, cold year round"},
    {"n": "Estanys de Tristaina", "cc": "AD", "kind": "tarn", "swim": "limited",
     "lat": 42.63, "lon": 1.47, "why": "editorial", "haz": ["cold_shock"],
     "note": "the three lakes walk, the Andorran picture everybody posts"},

    # ---------------------------------------------------------------- AL ----
    {"n": "Lake Ohrid", "alt": ["Liqeni i Ohrit"], "cc": "AL", "kind": "lake",
     "swim": "yes", "lat": 40.98, "lon": 20.68, "why": "brief",
     "note": "UNESCO, ancient and clear, the Pogradec shore"},
    {"n": "Lake Koman", "alt": ["Liqeni i Komanit"], "cc": "AL", "kind": "reservoir",
     "swim": "limited", "lat": 42.1, "lon": 19.82, "why": "brief",
     "note": "fjord-like ferry route, swimming only from a boat or the shore"},
    {"n": "Lake Shkoder", "alt": ["Liqeni i Shkodres"], "cc": "AL", "kind": "lake",
     "swim": "yes", "lat": 42.16, "lon": 19.4, "why": "brief",
     "note": "largest lake in the Balkans, shared with Montenegro"},
    {"n": "Blue Eye", "alt": ["Syri i Kalter"], "cc": "AL", "kind": "lake",
     "swim": "no", "lat": 39.92, "lon": 20.19, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "karst spring, protected, swimming in the spring pool is banned"},
    {"n": "Bovilla Reservoir", "alt": ["Liqeni i Bovilles"], "cc": "AL",
     "kind": "reservoir", "swim": "no", "lat": 41.42, "lon": 19.87, "why": "editorial",
     "note": "Tirana's drinking water reservoir, the viewpoint is the attraction"},

    # ---------------------------------------------------------------- AT ----
    {"n": "Worthersee", "alt": ["Worther See"], "cc": "AT", "kind": "lake",
     "swim": "yes", "lat": 46.62, "lon": 14.15, "why": "brief",
     "note": "warmest large Austrian lake, town lidos"},
    {"n": "Attersee", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.85, "lon": 13.55, "why": "brief",
     "note": "clarity to about 25 m, sailing and diving"},
    {"n": "Hallstatter See", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.57, "lon": 13.66, "why": "brief",
     "note": "designated Badeinsel, the most photographed lake village in Europe"},
    {"n": "Faaker See", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 46.57, "lon": 13.92, "why": "brief", "note": "glacial turquoise, Carinthia"},
    {"n": "Klopeiner See", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 46.62, "lon": 14.57, "why": "brief",
     "note": "one of the warmest lakes in Austria, about 26 C in high summer"},
    {"n": "Gruner See", "cc": "AT", "kind": "lake", "swim": "no",
     "lat": 47.54, "lon": 15.04, "why": "editorial",
     "note": "the underwater park at Tragoss, diving and swimming banned since 2016"},
    {"n": "Achensee", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.46, "lon": 11.72, "why": "editorial", "note": "Tyrol's largest, windsurfing"},
    {"n": "Wolfgangsee", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.73, "lon": 13.43, "why": "editorial", "note": "St Wolfgang, Salzkammergut"},
    {"n": "Neusiedler See", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.84, "lon": 16.75, "why": "editorial",
     "note": "steppe lake, shallow and warm, UNESCO with Hungary"},
    {"n": "Traunsee", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 47.87, "lon": 13.8, "why": "editorial", "note": "the deepest Austrian lake"},
    {"n": "Millstatter See", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 46.8, "lon": 13.58, "why": "editorial", "note": "warm Carinthian lake"},
    {"n": "Weissensee", "cc": "AT", "kind": "lake", "swim": "yes",
     "lat": 46.72, "lon": 13.3, "why": "editorial",
     "note": "drinking water quality, the ice skating lake in winter"},
    {"n": "Vorderer Gosausee", "alt": ["Gosausee"], "cc": "AT", "kind": "lake",
     "swim": "limited", "lat": 47.54, "lon": 13.49, "why": "editorial",
     "haz": ["cold_shock"], "note": "the Dachstein reflection, cold and steep sided"},

    # ---------------------------------------------------------------- BA ----
    {"n": "Pliva Lakes", "alt": ["Plivska jezera"], "cc": "BA", "kind": "lake",
     "swim": "yes", "lat": 44.34, "lon": 17.24, "why": "brief",
     "note": "Jajce, the watermills, swimming and rowing"},
    {"n": "Boracko Lake", "alt": ["Boracko jezero"], "cc": "BA", "kind": "lake",
     "swim": "yes", "lat": 43.55, "lon": 17.98, "why": "brief",
     "note": "glacial lake near Konjic, swimming"},
    {"n": "Una", "alt": ["Una River", "Rijeka Una"], "wd": "Q212927", "cc": "BA",
     "kind": "river", "swim": "limited",
     "lat": 44.81, "lon": 15.87, "why": "brief", "haz": ["currents"],
     "note": "Bihac, turquoise, rafting and the falls; the current is the risk"},
    {"n": "Neretva", "cc": "BA", "kind": "river", "swim": "limited",
     "lat": 43.34, "lon": 17.81, "why": "brief", "haz": ["cold_shock", "currents"],
     "note": "turquoise and very cold even in August, Mostar"},
    {"n": "Prokosko Lake", "alt": ["Prokosko jezero"], "cc": "BA", "kind": "lake",
     "swim": "limited", "lat": 43.95, "lon": 17.85, "why": "editorial",
     "haz": ["cold_shock"], "note": "Vranica mountain, the shepherd huts"},

    # ---------------------------------------------------------------- BE ----
    {"n": "Lacs de l'Eau d'Heure", "cc": "BE", "kind": "reservoir", "swim": "yes",
     "lat": 50.2, "lon": 4.38, "why": "brief",
     "note": "the largest Belgian water body, watersports and a supervised swim zone"},
    {"n": "Lac de Robertville", "cc": "BE", "kind": "reservoir", "swim": "yes",
     "lat": 50.45, "lon": 6.12, "why": "brief", "note": "Ardennes reservoir with a beach"},
    {"n": "Lac de Butgenbach", "cc": "BE", "kind": "reservoir", "swim": "yes",
     "lat": 50.42, "lon": 6.2, "why": "brief", "note": "Ardennes, swimming and sailing"},
    {"n": "Blaarmeersen", "cc": "BE", "kind": "lake", "swim": "yes",
     "lat": 51.04, "lon": 3.69, "why": "brief",
     "note": "Ghent's quarry lake recreation park"},
    {"n": "Donkmeer", "cc": "BE", "kind": "lake", "swim": "yes",
     "lat": 51.04, "lon": 3.98, "why": "editorial",
     "note": "Berlare, the largest natural lake in Flanders, rowing boats and "
             "eel restaurants. Stands in for the Zilvermeer at Mol, which is "
             "the better known swimming lake and has no Wikidata item at all, "
             "so it can carry neither a coordinate nor a photograph"},

    # ---------------------------------------------------------------- BG ----
    {"n": "Seven Rila Lakes", "alt": ["Sedemte rilski ezera"], "cc": "BG",
     "kind": "tarn", "swim": "limited", "lat": 42.2, "lon": 23.32, "why": "brief",
     "haz": ["cold_shock"], "note": "glacial cirque lakes above 2,100 m, freezing"},
    {"n": "Iskar Reservoir", "alt": ["Iskarsko yazovir"], "cc": "BG",
     "kind": "reservoir", "swim": "limited", "lat": 42.5, "lon": 23.53, "why": "brief",
     "note": "Sofia's water supply, swimming restricted in parts"},
    {"n": "Batak Reservoir", "cc": "BG", "kind": "reservoir", "swim": "yes",
     "lat": 41.98, "lon": 24.2, "why": "brief", "note": "Rhodopes, swimming and boating"},
    {"n": "Lake Srebarna", "cc": "BG", "kind": "lake", "swim": "no",
     "lat": 44.11, "lon": 27.07, "why": "editorial",
     "note": "UNESCO biosphere reserve, pelicans, no swimming"},
    {"n": "Pancharevo Lake", "cc": "BG", "kind": "reservoir", "swim": "yes",
     "lat": 42.6, "lon": 23.42, "why": "editorial",
     "note": "Sofia's rowing and swimming lake"},
    {"n": "Smolyan Lakes", "cc": "BG", "kind": "lake", "swim": "limited",
     "lat": 41.6, "lon": 24.66, "why": "editorial",
     "note": "Rhodopes, a chain of small lakes above the town"},

    # ---------------------------------------------------------------- CH ----
    {"n": "Lake Geneva", "alt": ["Lac Leman", "Genfersee"], "cc": "CH",
     "kind": "lake", "swim": "yes", "lat": 46.45, "lon": 6.5, "why": "brief",
     "note": "cross border with France, lidos on both shores"},
    {"n": "Lake Lucerne", "alt": ["Vierwaldstattersee"], "cc": "CH", "kind": "lake",
     "swim": "yes", "lat": 47.0, "lon": 8.42, "why": "brief",
     "note": "scenery and town badis"},
    {"n": "Oeschinensee", "cc": "CH", "kind": "lake", "swim": "limited",
     "lat": 46.5, "lon": 7.73, "why": "brief", "haz": ["cold_shock"],
     "note": "UNESCO, 1,578 m, swimming allowed but the water is alpine cold"},
    {"n": "Lake Zurich", "alt": ["Zurichsee"], "cc": "CH", "kind": "lake",
     "swim": "yes", "lat": 47.25, "lon": 8.65, "why": "brief",
     "note": "the badi culture, urban swimming at its best"},
    {"n": "Caumasee", "cc": "CH", "kind": "lake", "swim": "yes",
     "lat": 46.81, "lon": 9.27, "why": "brief",
     "note": "turquoise forest lake above Flims, Graubunden"},
    {"n": "Blausee", "cc": "CH", "kind": "lake", "swim": "no",
     "lat": 46.55, "lon": 7.68, "why": "editorial",
     "note": "private nature park, rowing boats only, no swimming"},
    {"n": "Bachalpsee", "cc": "CH", "kind": "tarn", "swim": "limited",
     "lat": 46.67, "lon": 8.02, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Grindelwald mirror shot at 2,265 m"},
    {"n": "Seealpsee", "cc": "CH", "kind": "lake", "swim": "limited",
     "lat": 47.27, "lon": 9.4, "why": "editorial", "haz": ["cold_shock"],
     "note": "Appenzell, the other Swiss postcard"},
    {"n": "Lake Brienz", "alt": ["Brienzersee"], "cc": "CH", "kind": "lake",
     "swim": "yes", "lat": 46.72, "lon": 7.97, "why": "editorial",
     "haz": ["cold_shock"], "note": "glacial turquoise, cold, Iseltwald"},
    {"n": "Lake Thun", "alt": ["Thunersee"], "cc": "CH", "kind": "lake",
     "swim": "yes", "lat": 46.68, "lon": 7.72, "why": "editorial",
     "note": "the warmer of the two Bernese Oberland lakes"},
    {"n": "Lake Lugano", "alt": ["Lago di Lugano", "Ceresio"], "cc": "CH",
     "kind": "lake", "swim": "yes", "lat": 45.98, "lon": 8.97, "why": "editorial",
     "note": "the warm southern one, shared with Italy"},
    {"n": "Silvaplanersee", "cc": "CH", "kind": "lake", "swim": "limited",
     "lat": 46.45, "lon": 9.79, "why": "editorial", "haz": ["cold_shock"],
     "note": "Engadin, the European windsurfing and kite lake"},

    # ---------------------------------------------------------------- CY ----
    {"n": "Kouris Reservoir", "cc": "CY", "kind": "reservoir", "swim": "no",
     "lat": 34.75, "lon": 32.87, "why": "brief",
     "note": "the island's largest dam, drinking water, swimming prohibited"},
    {"n": "Germasogeia Reservoir", "cc": "CY", "kind": "reservoir", "swim": "no",
     "lat": 34.75, "lon": 33.08, "why": "brief",
     "note": "water supply reservoir with a walking trail, no swimming"},
    {"n": "Larnaca Salt Lake", "cc": "CY", "kind": "lake", "swim": "no",
     "lat": 34.88, "lon": 33.6, "why": "brief",
     "note": "seasonal and protected, flamingos in winter, no swimming"},
    {"n": "Oroklini Lake", "alt": ["Voroklini Lake", "Oroklini"], "cc": "CY",
     "kind": "lake", "swim": "no",
     "lat": 34.97, "lon": 33.65, "why": "editorial",
     "note": "Natura 2000 bird reserve with a hide"},

    # ---------------------------------------------------------------- CZ ----
    {"n": "Lipno", "alt": ["Lipno Reservoir"], "cc": "CZ", "kind": "reservoir",
     "swim": "yes", "lat": 48.68, "lon": 14.13, "why": "brief",
     "note": "Sumava, the Czech sea, sailing and swimming"},
    {"n": "Orlik Reservoir", "cc": "CZ", "kind": "reservoir", "swim": "yes",
     "lat": 49.52, "lon": 14.17, "why": "brief", "note": "the Vltava reservoir, boating"},
    {"n": "Slapy Reservoir", "cc": "CZ", "kind": "reservoir", "swim": "yes",
     "lat": 49.82, "lon": 14.42, "why": "brief", "note": "Prague's summer water"},
    {"n": "Machovo jezero", "alt": ["Mach's Lake"], "cc": "CZ", "kind": "lake",
     "swim": "yes", "lat": 50.59, "lon": 14.64, "why": "brief",
     "haz": ["algal_bloom"],
     "note": "the classic Czech swimming lake, cyanobacteria in hot summers"},
    {"n": "Cerne jezero", "alt": ["Black Lake"], "cc": "CZ", "kind": "lake",
     "swim": "no", "lat": 49.18, "lon": 13.18, "why": "editorial",
     "note": "Sumava NP glacial lake, first zone, swimming banned"},
    {"n": "Brnenska prehrada", "cc": "CZ", "kind": "reservoir", "swim": "yes",
     "lat": 49.23, "lon": 16.51, "why": "editorial", "haz": ["algal_bloom"],
     "note": "Brno's lake, the boat up to Veveri castle"},

    # ---------------------------------------------------------------- DE ----
    {"n": "Konigssee", "cc": "DE", "kind": "lake", "swim": "limited",
     "lat": 47.55, "lon": 12.98, "why": "brief", "haz": ["cold_shock"],
     "note": "Berchtesgaden NP, electric boats only, swimming only at the north end"},
    {"n": "Eibsee", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.46, "lon": 10.98, "why": "brief",
     "note": "turquoise under the Zugspitze, a private lake with an entry fee"},
    {"n": "Walchensee", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.59, "lon": 11.33, "why": "brief",
     "note": "alpine, clear, diving and windsurfing"},
    {"n": "Schluchsee", "cc": "DE", "kind": "reservoir", "swim": "yes",
     "lat": 47.82, "lon": 8.17, "why": "brief",
     "note": "Black Forest, swimming and sailing"},
    {"n": "Titisee", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.89, "lon": 8.15, "why": "brief",
     "note": "the Black Forest lake everyone visits"},
    {"n": "Muritz", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 53.42, "lon": 12.7, "why": "brief",
     "note": "largest wholly German lake, the Mecklenburg lake district"},
    {"n": "Lake Constance", "alt": ["Bodensee"], "cc": "DE", "kind": "lake",
     "swim": "yes", "lat": 47.6, "lon": 9.35, "why": "editorial",
     "note": "three countries, hundreds of lidos"},
    {"n": "Chiemsee", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.87, "lon": 12.47, "why": "editorial",
     "note": "the Bavarian sea, Herrenchiemsee palace"},
    {"n": "Starnberger See", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.9, "lon": 11.3, "why": "editorial", "note": "Munich's swimming lake"},
    {"n": "Tegernsee", "cc": "DE", "kind": "lake", "swim": "yes",
     "lat": 47.71, "lon": 11.75, "why": "editorial", "note": "clean, alpine, expensive"},
    {"n": "Hintersee", "cc": "DE", "kind": "lake", "swim": "limited",
     "lat": 47.6, "lon": 12.86, "why": "editorial", "haz": ["cold_shock"],
     "note": "Ramsau, the Zauberwald reflection"},
    {"n": "Edersee", "cc": "DE", "kind": "reservoir", "swim": "yes",
     "lat": 51.18, "lon": 8.98, "why": "editorial",
     "note": "Hesse, the drowned villages surface in a dry year"},

    # ---------------------------------------------------------------- DK ----
    {"n": "Furesoen", "alt": ["Fureso", "Furesoe", "Furesø"], "cc": "DK",
     "kind": "lake", "swim": "yes",
     "lat": 55.79, "lon": 12.42, "why": "brief", "note": "the deepest Danish lake, Zealand"},
    {"n": "Bagsvaerd So", "cc": "DK", "kind": "lake", "swim": "yes",
     "lat": 55.77, "lon": 12.45, "why": "brief",
     "note": "rowing and swimming on Copenhagen's edge"},
    {"n": "Julso", "cc": "DK", "kind": "lake", "swim": "yes",
     "lat": 56.13, "lon": 9.6, "why": "brief",
     "note": "Himmelbjerget, the heart of the Silkeborg lake district"},
    {"n": "Gudenaa", "alt": ["Gudena"], "cc": "DK", "kind": "river",
     "swim": "limited", "lat": 56.15, "lon": 9.65, "why": "brief",
     "note": "Denmark's longest river, the canoe route"},
    {"n": "Arreso", "cc": "DK", "kind": "lake", "swim": "limited",
     "lat": 55.97, "lon": 12.07, "why": "editorial", "haz": ["algal_bloom"],
     "note": "the largest Danish lake, shallow and often blooming"},
    {"n": "Esrum So", "cc": "DK", "kind": "lake", "swim": "yes",
     "lat": 56.0, "lon": 12.37, "why": "editorial", "note": "clear, north Zealand"},

    # ---------------------------------------------------------------- EE ----
    {"n": "Lake Peipus", "alt": ["Peipsi jarv"], "cc": "EE", "kind": "lake",
     "swim": "yes", "lat": 58.68, "lon": 27.5, "why": "brief",
     "note": "a huge cross border lake with sandy beaches on the Estonian shore"},
    {"n": "Lake Ulemiste", "alt": ["Ulemiste jarv"], "cc": "EE", "kind": "lake",
     "swim": "no", "lat": 59.4, "lon": 24.77, "why": "brief",
     "note": "Tallinn's drinking water, closed to the public"},
    {"n": "Viljandi Lake", "alt": ["Viljandi jarv"], "cc": "EE", "kind": "lake",
     "swim": "yes", "lat": 58.35, "lon": 25.6, "why": "brief",
     "note": "the town swimming lake below the castle hills"},
    {"n": "Pühajärv", "alt": ["Puhajarv", "Holy Lake"], "cc": "EE", "kind": "lake",
     "swim": "yes", "lat": 58.05, "lon": 26.44, "why": "editorial",
     "note": "Otepaa, five islands, beaches"},
    {"n": "Rummu", "alt": ["Rummu quarry", "Rummu karjaar"], "cc": "EE",
     "kind": "lake", "swim": "limited", "lat": 59.22, "lon": 24.2, "why": "editorial",
     "note": "the flooded prison quarry, turquoise, an Instagram fixture; supervised zone only"},

    # ---------------------------------------------------------------- ES ----
    {"n": "Lago de Sanabria", "cc": "ES", "kind": "lake", "swim": "yes",
     "lat": 42.12, "lon": -6.72, "why": "brief",
     "note": "the largest natural lake in Iberia, glacial, beaches"},
    {"n": "Embalse de San Juan", "cc": "ES", "kind": "reservoir", "swim": "yes",
     "lat": 40.36, "lon": -4.31, "why": "brief",
     "note": "Madrid's beach, swimming and boating"},
    {"n": "Lagunas de Ruidera", "cc": "ES", "kind": "lake", "swim": "yes",
     "lat": 38.93, "lon": -2.87, "why": "brief",
     "note": "a karst lagoon chain in a natural park, designated swimming"},
    {"n": "Lake Banyoles", "alt": ["Estany de Banyoles"], "cc": "ES", "kind": "lake",
     "swim": "yes", "lat": 42.13, "lon": 2.75, "why": "brief",
     "note": "the Olympic rowing lake, designated swimming"},
    {"n": "Lagos de Covadonga", "cc": "ES", "kind": "lake", "swim": "no",
     "lat": 43.27, "lon": -4.99, "why": "editorial",
     "note": "Picos de Europa NP, Enol and Ercina, swimming not permitted"},
    {"n": "Embalse de Riano", "cc": "ES", "kind": "reservoir", "swim": "limited",
     "lat": 42.98, "lon": -5.0, "why": "editorial", "note": "the Spanish fjord"},
    {"n": "Albufera de Valencia", "cc": "ES", "kind": "lagoon", "swim": "no",
     "lat": 39.33, "lon": -0.34, "why": "editorial",
     "note": "natural park lagoon, sunset boats, not a swimming water"},
    {"n": "Estany de Sant Maurici", "alt": ["Sant Maurici", "Sant Maurici Lake"],
     "cc": "ES", "kind": "lake", "swim": "no",
     "lat": 42.58, "lon": 1.0, "why": "editorial",
     "note": "Aiguestortes NP, swimming banned in the park lakes"},
    {"n": "Laguna Negra", "cc": "ES", "kind": "lake", "swim": "no",
     "lat": 41.99, "lon": -2.85, "why": "editorial",
     "note": "Soria, a glacial cirque under a rock wall, protected"},

    # ---------------------------------------------------------------- FI ----
    {"n": "Saimaa", "cc": "FI", "kind": "lake", "swim": "yes",
     "lat": 61.35, "lon": 28.2, "why": "brief",
     "note": "the lake system, cottages and saunas, the ringed seal"},
    {"n": "Paijanne", "cc": "FI", "kind": "lake", "swim": "yes",
     "lat": 61.6, "lon": 25.5, "why": "brief",
     "note": "clear and long, Helsinki's water source"},
    {"n": "Lake Inari", "alt": ["Inarijarvi"], "cc": "FI", "kind": "lake",
     "swim": "limited", "lat": 69.0, "lon": 27.9, "why": "brief",
     "haz": ["cold_shock"], "note": "Lapland, remote and cold"},
    {"n": "Pielinen", "cc": "FI", "kind": "lake", "swim": "yes",
     "lat": 63.25, "lon": 29.6, "why": "editorial",
     "note": "Koli NP, the Finnish national view"},
    {"n": "Oulujarvi", "cc": "FI", "kind": "lake", "swim": "yes",
     "lat": 64.35, "lon": 27.25, "why": "editorial", "note": "the Kainuu sea"},
    {"n": "Nasijarvi", "cc": "FI", "kind": "lake", "swim": "yes",
     "lat": 61.6, "lon": 23.75, "why": "editorial",
     "note": "Tampere, urban swimming and public saunas"},

    # ---------------------------------------------------------------- FO ----
    {"n": "Sorvagsvatn", "alt": ["Leitisvatn"], "cc": "FO", "kind": "lake",
     "swim": "no", "lat": 62.06, "lon": -7.28, "why": "editorial",
     "haz": ["cold_shock", "cliffs"],
     "note": "the lake that looks like it hangs over the ocean, the Faroes' one famous picture"},
    {"n": "Fjallavatn", "cc": "FO", "kind": "lake", "swim": "no",
     "lat": 62.12, "lon": -7.36, "why": "editorial", "haz": ["cold_shock"],
     "note": "Vagar's second lake, a walk in over open moor"},
    {"n": "Toftavatn", "cc": "FO", "kind": "lake", "swim": "no",
     "lat": 62.1, "lon": -6.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "Eysturoy, an easy lakeside walk"},

    # ---------------------------------------------------------------- FR ----
    {"n": "Lac d'Annecy", "cc": "FR", "kind": "lake", "swim": "yes",
     "lat": 45.85, "lon": 6.17, "why": "brief",
     "note": "among the cleanest large lakes in Europe, beaches and the cycle path"},
    {"n": "Lac de Sainte-Croix", "cc": "FR", "kind": "reservoir", "swim": "yes",
     "lat": 43.76, "lon": 6.2, "why": "brief",
     "note": "Verdon, turquoise, kayaking; the inner gorge itself is closed to swimmers"},
    {"n": "Lac du Bourget", "cc": "FR", "kind": "lake", "swim": "yes",
     "lat": 45.73, "lon": 5.86, "why": "brief",
     "note": "the largest natural lake in France"},
    {"n": "Etang de Thau", "cc": "FR", "kind": "lagoon", "swim": "yes",
     "lat": 43.4, "lon": 3.6, "why": "brief",
     "note": "Occitanie lagoon, oyster beds and designated swimming areas"},
    {"n": "Lac de Serre-Poncon", "cc": "FR", "kind": "reservoir", "swim": "yes",
     "lat": 44.5, "lon": 6.35, "why": "editorial",
     "note": "the big Alpine reservoir, watersports"},
    {"n": "Lac Blanc", "cc": "FR", "kind": "tarn", "swim": "no",
     "lat": 45.99, "lon": 6.92, "why": "editorial", "haz": ["cold_shock"],
     "note": "Aiguilles Rouges, the Mont Blanc reflection, protected"},
    {"n": "Lac de Gaube", "cc": "FR", "kind": "lake", "swim": "no",
     "lat": 42.8, "lon": -0.14, "why": "editorial", "haz": ["cold_shock"],
     "note": "Pyrenees NP above Cauterets"},
    {"n": "Lac du Salagou", "cc": "FR", "kind": "reservoir", "swim": "yes",
     "lat": 43.65, "lon": 3.38, "why": "editorial",
     "note": "red earth shores, the Languedoc picture"},
    {"n": "Lac d'Aiguebelette", "cc": "FR", "kind": "lake", "swim": "yes",
     "lat": 45.55, "lon": 5.8, "why": "editorial",
     "note": "no motorboats at all, one of the warmest French lakes"},
    {"n": "Lac de Vassiviere", "cc": "FR", "kind": "reservoir", "swim": "yes",
     "lat": 45.8, "lon": 1.85, "why": "editorial",
     "note": "Limousin, the art island, beaches"},
    {"n": "Lac Pavin", "cc": "FR", "kind": "crater", "swim": "limited",
     "lat": 45.5, "lon": 2.89, "why": "editorial",
     "note": "an Auvergne crater lake, deep and cold, restricted"},
    {"n": "Lac de Guerledan", "cc": "FR", "kind": "reservoir", "swim": "yes",
     "lat": 48.2, "lon": -3.05, "why": "editorial",
     "note": "Brittany's lake, supervised beaches"},

    # ---------------------------------------------------------------- GB ----
    {"n": "Loch Lomond", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 56.09, "lon": -4.6, "why": "brief", "haz": ["cold_shock"],
     "note": "national park, wild swimming and watersports, cold year round"},
    {"n": "Windermere", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 54.36, "lon": -2.94, "why": "brief", "haz": ["water_quality"],
     "note": "England's largest lake, with documented water quality problems"},
    {"n": "Buttermere", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.53, "lon": -3.28, "why": "brief", "haz": ["cold_shock"],
     "note": "Lake District, the classic wild swim"},
    {"n": "Llyn Padarn", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 53.13, "lon": -4.13, "why": "brief", "haz": ["cold_shock"],
     "note": "a designated bathing water in Eryri, the Snowdon backdrop"},
    {"n": "River Wye", "cc": "GB", "kind": "river", "swim": "limited",
     "lat": 51.98, "lon": -2.65, "why": "brief",
     "haz": ["water_quality", "currents"],
     "note": "the canoe river; English river bathing waters mostly rate Poor, check first"},
    {"n": "Loch Ness", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 57.32, "lon": -4.42, "why": "editorial", "haz": ["cold_shock"],
     "note": "deep, dark and very cold, the famous one"},
    {"n": "Derwentwater", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.58, "lon": -3.14, "why": "editorial", "haz": ["cold_shock"],
     "note": "Keswick, launches and swimming"},
    {"n": "Ullswater", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.57, "lon": -2.87, "why": "editorial", "haz": ["cold_shock"],
     "note": "the steamers and the Ullswater Way"},
    {"n": "Wast Water", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 54.44, "lon": -3.28, "why": "editorial", "haz": ["cold_shock"],
     "note": "England's deepest, the screes, Britain's favourite view"},
    {"n": "Loch Katrine", "cc": "GB", "kind": "lake", "swim": "no",
     "lat": 56.26, "lon": -4.55, "why": "editorial",
     "note": "Glasgow's drinking water, swimming prohibited"},
    {"n": "Fairy Pools", "cc": "GB", "kind": "river", "swim": "limited",
     "lat": 57.25, "lon": -6.25, "why": "editorial", "haz": ["cold_shock"],
     "note": "Skye, Glenbrittle, wild plunge pools, an Instagram fixture"},
    {"n": "Loch an Eilein", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 57.15, "lon": -3.82, "why": "editorial", "haz": ["cold_shock"],
     "note": "Rothiemurchus, the island castle"},

    # -- 2026-08-30 coverage pass. Britain publishes the layer's thinnest
    # list against its actual wealth of water: Wikidata ranks by sitelinks
    # and by surface area, and a Cumbrian tarn or a Highland loch wins
    # neither. These are the ones a person going there would name.
    {"n": "Coniston Water", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.33, "lon": -3.07, "why": "editorial", "haz": ["cold_shock"],
     "note": "open water swimming, the steam yacht Gondola, Donald Campbell"},
    {"n": "Crummock Water", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.55, "lon": -3.3, "why": "editorial", "haz": ["cold_shock"],
     "note": "the quiet half of the Buttermere valley, a classic wild swim"},
    {"n": "Grasmere", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.45, "lon": -3.02, "why": "editorial", "haz": ["cold_shock"],
     "note": "Wordsworth's lake, rowing boats and a shore walk"},
    {"n": "Rydal Water", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 54.45, "lon": -2.98, "why": "editorial", "haz": ["cold_shock"],
     "note": "shallow and small, the coffin route walk above it"},
    {"n": "Bassenthwaite Lake", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 54.65, "lon": -3.21, "why": "editorial",
     "note": "national nature reserve, access to the water is restricted"},
    {"n": "Thirlmere", "cc": "GB", "kind": "reservoir", "swim": "no",
     "lat": 54.53, "lon": -3.06, "why": "editorial",
     "note": "Manchester's water since 1894, swimming prohibited"},
    {"n": "Haweswater", "cc": "GB", "kind": "reservoir", "swim": "no",
     "lat": 54.51, "lon": -2.8, "why": "editorial",
     "note": "drinking water reservoir, the drowned village of Mardale"},
    {"n": "Ennerdale Water", "cc": "GB", "kind": "lake", "swim": "no",
     "lat": 54.52, "lon": -3.39, "why": "editorial",
     "note": "a water supply lake, swimming prohibited, Wild Ennerdale walking"},
    {"n": "Malham Tarn", "cc": "GB", "kind": "lake", "swim": "no",
     "lat": 54.09, "lon": -2.16, "why": "editorial",
     "note": "upland alkaline tarn, a national nature reserve, no swimming"},
    {"n": "Kielder Water", "cc": "GB", "kind": "reservoir", "swim": "limited",
     "lat": 55.19, "lon": -2.55, "why": "editorial",
     "note": "northern Europe's largest man made lake, swimming at events only"},
    {"n": "Rutland Water", "cc": "GB", "kind": "reservoir", "swim": "limited",
     "lat": 52.65, "lon": -0.65, "why": "editorial",
     "note": "sailing, cycling and ospreys; open water swimming at set times"},
    {"n": "Bala Lake", "alt": ["Llyn Tegid"], "cc": "GB", "kind": "lake",
     "swim": "yes", "lat": 52.88, "lon": -3.63, "why": "editorial",
     "haz": ["cold_shock"], "note": "the largest natural lake in Wales"},
    {"n": "Llyn Gwynant", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 53.04, "lon": -4.02, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Nant Gwynant valley under Snowdon, camping and swimming"},
    {"n": "Llyn Idwal", "cc": "GB", "kind": "tarn", "swim": "limited",
     "lat": 53.11, "lon": -4.02, "why": "editorial", "haz": ["cold_shock"],
     "note": "a national nature reserve in Cwm Idwal, cold and much visited"},
    {"n": "Llyn y Fan Fach", "cc": "GB", "kind": "tarn", "swim": "limited",
     "lat": 51.88, "lon": -3.73, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Black Mountain glacial lake of the Physicians of Myddfai"},
    {"n": "Llyn Brianne", "cc": "GB", "kind": "reservoir", "swim": "no",
     "lat": 52.15, "lon": -3.75, "why": "editorial",
     "note": "water supply reservoir with a spillway, red kite country"},
    {"n": "Blue Lagoon Abereiddy", "alt": ["Abereiddy Blue Lagoon"], "cc": "GB",
     "kind": "lagoon", "swim": "yes", "lat": 51.94, "lon": -5.21,
     "why": "editorial", "haz": ["cold_shock", "currents"],
     "note": "a flooded slate quarry open to the sea, the coasteering place"},
    {"n": "Loch Awe", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 56.36, "lon": -5.14, "why": "editorial", "haz": ["cold_shock"],
     "note": "the longest freshwater loch in Scotland, Kilchurn Castle"},
    {"n": "Loch Tay", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 56.53, "lon": -4.15, "why": "editorial", "haz": ["cold_shock"],
     "note": "the crannog, Ben Lawers above it, watersports at Kenmore"},
    {"n": "Loch Earn", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 56.39, "lon": -4.2, "why": "editorial", "haz": ["cold_shock"],
     "note": "the watersports loch of the Trossachs, St Fillans to Lochearnhead"},
    {"n": "Loch Morar", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 56.95, "lon": -5.73, "why": "editorial", "haz": ["cold_shock"],
     "note": "the deepest freshwater body in the British Isles, 310 m"},
    {"n": "Loch Maree", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 57.68, "lon": -5.45, "why": "editorial", "haz": ["cold_shock"],
     "note": "Beinn Eighe above it, wooded islands, a national nature reserve"},
    {"n": "Loch Coruisk", "cc": "GB", "kind": "tarn", "swim": "limited",
     "lat": 57.2, "lon": -6.16, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Cuillin basin on Skye, reached by boat or a long walk in"},
    {"n": "Loch Muick", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 56.94, "lon": -3.15, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Balmoral estate loch under Lochnagar"},
    {"n": "Loch Shiel", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 56.8, "lon": -5.6, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Glenfinnan monument at its head, the viaduct above it"},
    {"n": "Loch Assynt", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 58.18, "lon": -5.0, "why": "editorial", "haz": ["cold_shock"],
     "note": "Ardvreck Castle, Quinag behind it, the Assynt geopark"},
    {"n": "Loch Leven Kinross", "alt": ["Loch Leven"], "cc": "GB",
     "kind": "lake", "swim": "yes", "lat": 56.2, "lon": -3.38,
     "why": "editorial", "haz": ["cold_shock", "algal_bloom"],
     "note": "the castle island, the heritage trail, a national nature reserve"},
    {"n": "Loch Insh", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 57.1, "lon": -3.93, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Cairngorms watersports loch on the Spey"},
    {"n": "Loch Lubnaig", "cc": "GB", "kind": "lake", "swim": "yes",
     "lat": 56.28, "lon": -4.28, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Trossachs swimming loch, paddleboards and a shore path"},
    {"n": "Lough Neagh", "cc": "GB", "kind": "lake", "swim": "limited",
     "lat": 54.61, "lon": -6.42, "why": "editorial",
     "haz": ["algal_bloom", "water_quality"],
     "note": "the largest lake in the British Isles, repeated blue green algae"},

    # ---------------------------------------------------------------- GR ----
    {"n": "Lake Plastiras", "cc": "GR", "kind": "reservoir", "swim": "limited",
     "lat": 39.25, "lon": 21.77, "why": "brief",
     "note": "Thessaly, scenic and cool, watersports; parts are water supply"},
    {"n": "Lake Kournas", "cc": "GR", "kind": "lake", "swim": "yes",
     "lat": 35.33, "lon": 24.28, "why": "brief",
     "note": "the only natural freshwater lake on Crete, pedalos and swimming"},
    {"n": "Voulismeni", "cc": "GR", "kind": "lake", "swim": "no",
     "lat": 35.19, "lon": 25.72, "why": "brief",
     "note": "the Agios Nikolaos harbour lake, tavernas, not a swimming water"},
    {"n": "Lake Vouliagmeni", "cc": "GR", "kind": "lake", "swim": "yes",
     "lat": 37.81, "lon": 23.79, "why": "editorial",
     "note": "a brackish thermal lake near Athens, year round bathing, entry fee"},
    {"n": "Lake Prespa", "alt": ["Megali Prespa"], "cc": "GR", "kind": "lake",
     "swim": "limited", "lat": 40.78, "lon": 21.06, "why": "editorial",
     "note": "the three country lake, national park, birds"},
    {"n": "Melissani", "alt": ["Melissani Cave"], "cc": "GR", "kind": "lake",
     "swim": "no", "lat": 38.26, "lon": 20.62, "why": "editorial",
     "note": "Kefalonia, the collapsed cave lake, boats only"},
    {"n": "Lake Doxa", "cc": "GR", "kind": "reservoir", "swim": "limited",
     "lat": 37.93, "lon": 22.35, "why": "editorial",
     "note": "Corinthia, the chapel on the peninsula"},
    {"n": "Lake Kerkini", "cc": "GR", "kind": "reservoir", "swim": "no",
     "lat": 41.21, "lon": 23.15, "why": "editorial",
     "note": "Ramsar wetland, pelicans and water buffalo, boat trips"},

    # ---------------------------------------------------------------- HR ----
    {"n": "Plitvice Lakes", "alt": ["Plitvicka jezera"], "cc": "HR", "kind": "lake",
     "swim": "no", "lat": 44.88, "lon": 15.62, "why": "brief",
     "note": "UNESCO, sixteen terraced lakes, swimming banned throughout the park"},
    {"n": "Skradinski Buk", "alt": ["Krka"], "cc": "HR", "kind": "river",
     "swim": "no", "lat": 43.8, "lon": 15.96, "why": "brief",
     "note": "Krka NP, swimming below the falls closed since 2021"},
    {"n": "Mljet Lakes", "alt": ["Veliko jezero", "Malo jezero"], "cc": "HR",
     "kind": "lagoon", "swim": "yes", "lat": 42.77, "lon": 17.38, "why": "brief",
     "note": "saltwater lakes in Mljet NP, swimming and the island monastery"},
    {"n": "Cetina", "cc": "HR", "kind": "river", "swim": "limited",
     "lat": 43.45, "lon": 16.7, "why": "brief", "haz": ["cold_shock", "currents"],
     "note": "rafting and the spring, cold"},
    {"n": "Modro jezero", "alt": ["Blue Lake"], "cc": "HR", "kind": "lake",
     "swim": "yes", "lat": 43.44, "lon": 17.19, "why": "editorial",
     "note": "Imotski, swimming in the sinkhole when the water is high"},
    {"n": "Crveno jezero", "alt": ["Red Lake"], "cc": "HR", "kind": "lake",
     "swim": "no", "lat": 43.45, "lon": 17.2, "why": "editorial", "haz": ["cliffs"],
     "note": "Imotski, sheer 240 m collapse walls, no way down to the water"},
    {"n": "Vransko jezero", "cc": "HR", "kind": "lake", "swim": "limited",
     "lat": 43.9, "lon": 15.57, "why": "editorial",
     "note": "the largest natural lake in Croatia, a nature park, birds"},

    # -- 2026-08-30 coverage pass. Croatia's list was the seven famous karst
    # names and nothing else, and the rivers people actually swim in were
    # all missing from it.
    {"n": "Peruca Lake", "alt": ["Perucko jezero"], "cc": "HR",
     "kind": "reservoir", "swim": "yes", "lat": 43.75, "lon": 16.65,
     "why": "editorial",
     "note": "the Cetina reservoir in the Dalmatian hinterland"},
    {"n": "Bacina Lakes", "alt": ["Bacinska jezera"], "cc": "HR",
     "kind": "lake", "swim": "yes", "lat": 43.07, "lon": 17.42,
     "why": "editorial",
     "note": "six connected karst lakes behind Ploce, warm and swimmable"},
    {"n": "Vrana Lake Cres", "alt": ["Vransko jezero Cres"], "cc": "HR",
     "kind": "lake", "swim": "no", "lat": 44.86, "lon": 14.36,
     "why": "editorial",
     "note": "the drinking water of Cres and Losinj, a cryptodepression"},
    {"n": "Zrmanja", "cc": "HR", "kind": "river", "swim": "yes",
     "lat": 44.15, "lon": 15.85, "why": "editorial",
     "note": "the canyon river of the Winnetou films, rafting and swimming"},
    {"n": "Mreznica", "cc": "HR", "kind": "river", "swim": "yes",
     "lat": 45.35, "lon": 15.5, "why": "editorial",
     "note": "ninety three tufa waterfalls, the Karlovac swimming river"},
    {"n": "Kupa", "cc": "HR", "kind": "river", "swim": "yes",
     "lat": 45.48, "lon": 15.3, "why": "editorial",
     "note": "the clear border river of Gorski kotar"},
    {"n": "Korana", "cc": "HR", "kind": "river", "swim": "limited",
     "lat": 45.1, "lon": 15.6, "why": "editorial",
     "note": "runs out of Plitvice past Rastoke, swimming outside the park"},
    {"n": "Rastoke", "cc": "HR", "kind": "river", "swim": "limited",
     "lat": 45.12, "lon": 15.58, "why": "editorial",
     "note": "the water mill village where the Slunjcica meets the Korana"},
    {"n": "Lokve Lake", "alt": ["Lokvarsko jezero"], "cc": "HR",
     "kind": "reservoir", "swim": "limited", "lat": 45.36, "lon": 14.75,
     "why": "editorial", "haz": ["cold_shock"],
     "note": "a forest reservoir in Gorski kotar, cold and drawn down"},
    {"n": "Sabljaci Lake", "alt": ["Jezero Sabljaci"], "cc": "HR",
     "kind": "reservoir", "swim": "yes", "lat": 45.32, "lon": 15.25,
     "why": "editorial", "note": "Ogulin's bathing lake under Klek"},
    {"n": "Butoniga", "cc": "HR", "kind": "reservoir", "swim": "no",
     "lat": 45.28, "lon": 13.92, "why": "editorial",
     "note": "Istria's drinking water reservoir, swimming prohibited"},
    {"n": "Visovac Lake", "cc": "HR", "kind": "lake", "swim": "no",
     "lat": 43.8, "lon": 15.95, "why": "editorial",
     "note": "the Krka park lake around the monastery island, boats only"},
    {"n": "Prokljan Lake", "alt": ["Prokljansko jezero"], "cc": "HR",
     "kind": "lagoon", "swim": "limited", "lat": 43.8, "lon": 15.83,
     "why": "editorial",
     "note": "brackish, where the Krka widens before Sibenik"},
    {"n": "Jarun", "cc": "HR", "kind": "lake", "swim": "yes",
     "lat": 45.78, "lon": 15.92, "why": "editorial",
     "note": "Zagreb's lake, a rowing course, beaches and the summer crowd"},
    {"n": "Bundek", "cc": "HR", "kind": "lake", "swim": "yes",
     "lat": 45.78, "lon": 15.99, "why": "editorial",
     "note": "the other Zagreb lake, on the right bank of the Sava"},

    # ---------------------------------------------------------------- HU ----
    {"n": "Lake Balaton", "cc": "HU", "kind": "lake", "swim": "yes",
     "lat": 46.83, "lon": 17.72, "why": "brief",
     "note": "the warmest large lake in central Europe, shallow, family swimming"},
    {"n": "Lake Velence", "cc": "HU", "kind": "lake", "swim": "yes",
     "lat": 47.21, "lon": 18.62, "why": "brief",
     "note": "warm and shallow, close to Budapest"},
    {"n": "Lake Tisza", "alt": ["Tisza-to"], "cc": "HU", "kind": "reservoir",
     "swim": "yes", "lat": 47.62, "lon": 20.6, "why": "brief",
     "note": "kayaking and birdlife, designated swim areas"},
    {"n": "Lake Heviz", "alt": ["Heviz"], "cc": "HU", "kind": "geothermal",
     "swim": "yes", "lat": 46.79, "lon": 17.19, "why": "editorial",
     "note": "the largest thermal lake in Europe you can swim in, 24 to 38 C"},
    {"n": "Lake Orfu", "cc": "HU", "kind": "reservoir", "swim": "yes",
     "lat": 46.13, "lon": 18.13, "why": "editorial",
     "note": "the Mecsek hills, swimming and camping"},

    # ---------------------------------------------------------------- IE ----
    {"n": "Lough Hyne", "cc": "IE", "kind": "lagoon", "swim": "yes",
     "lat": 51.5, "lon": -9.3, "why": "brief",
     "note": "Europe's first marine nature reserve, a saltwater lake, night kayaking"},
    {"n": "Lough Corrib", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.45, "lon": -9.25, "why": "brief", "note": "the fishing lake, Connemara"},
    {"n": "Glendalough Upper Lake", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.0, "lon": -6.35, "why": "brief", "haz": ["cold_shock"],
     "note": "Wicklow NP, the monastic city, cold"},
    {"n": "Lough Key", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 53.98, "lon": -8.23, "why": "brief", "note": "the forest park, boating"},
    {"n": "Lough Leane", "alt": ["Killarney Lakes"], "cc": "IE", "kind": "lake",
     "swim": "yes", "lat": 52.02, "lon": -9.55, "why": "editorial",
     "note": "Killarney NP, Ross Castle, the Gap of Dunloe"},
    {"n": "Lough Erne", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 54.45, "lon": -7.72, "why": "editorial", "note": "the cruising lakeland"},

    # -- 2026-08-30 coverage pass. Ireland published nine, which is fewer
    # than the loughs a single county holds. The same two Wikidata rankings
    # are why.
    {"n": "Lough Derg Shannon", "alt": ["Lough Derg"], "cc": "IE",
     "kind": "lake", "swim": "yes", "lat": 52.92, "lon": -8.32,
     "why": "editorial",
     "note": "the Shannon's big lake, Mountshannon and Terryglass"},
    {"n": "Lough Ree", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 53.55, "lon": -7.96, "why": "editorial",
     "note": "the middle Shannon lake, cruising and the Hodson Bay shore"},
    {"n": "Lough Mask", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.62, "lon": -9.33, "why": "editorial",
     "note": "limestone trout lough under the Partry mountains"},
    {"n": "Lough Conn", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 54.03, "lon": -9.25, "why": "editorial",
     "note": "Nephin above it, the Mayo fishing lough"},
    {"n": "Lough Gill", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 54.25, "lon": -8.38, "why": "editorial",
     "note": "Yeats country, the Isle of Innisfree, wooded shores"},
    {"n": "Lough Allen", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 54.12, "lon": -8.05, "why": "editorial",
     "note": "the first of the Shannon lakes, under the Iron Mountains"},
    {"n": "Lough Melvin", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 54.43, "lon": -8.15, "why": "editorial",
     "note": "three distinct trout races, shared with Northern Ireland"},
    {"n": "Lough Dan", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.08, "lon": -6.27, "why": "editorial", "haz": ["cold_shock"],
     "note": "Wicklow, a private shore with one permitted access point"},
    {"n": "Lough Tay", "alt": ["Guinness Lake"], "cc": "IE", "kind": "lake",
     "swim": "no", "lat": 53.11, "lon": -6.28, "why": "editorial",
     "note": "the dark lake with the pale beach, private, viewed from above"},
    {"n": "Lough Ouler", "cc": "IE", "kind": "tarn", "swim": "limited",
     "lat": 53.05, "lon": -6.35, "why": "editorial", "haz": ["cold_shock"],
     "note": "the heart shaped corrie lake under Tonelagee"},
    {"n": "Coumshingaun Lough", "cc": "IE", "kind": "tarn", "swim": "limited",
     "lat": 52.24, "lon": -7.5, "why": "editorial", "haz": ["cold_shock"],
     "note": "a corrie lake in the Comeraghs, the horseshoe walk above it"},
    {"n": "Gougane Barra", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 51.83, "lon": -9.28, "why": "editorial",
     "note": "the oratory on its island, the source of the Lee"},
    {"n": "Lough Inagh", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.51, "lon": -9.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Inagh valley between the Twelve Bens and the Maumturks"},
    {"n": "Doo Lough", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.72, "lon": -9.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Famine walk valley in Mayo, Mweelrea above it"},
    {"n": "Lough Nafooey", "cc": "IE", "kind": "lake", "swim": "limited",
     "lat": 53.58, "lon": -9.6, "why": "editorial", "haz": ["cold_shock"],
     "note": "a quiet glacial trough on the Galway and Mayo border"},
    {"n": "Lough Currane", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 51.82, "lon": -10.1, "why": "editorial",
     "note": "Waterville, sea trout, the Ring of Kerry"},
    {"n": "Muckross Lake", "alt": ["Middle Lake Killarney"], "cc": "IE",
     "kind": "lake", "swim": "yes", "lat": 52.01, "lon": -9.52,
     "why": "editorial",
     "note": "Killarney National Park, the deepest of the three lakes"},
    {"n": "Lough Beagh", "alt": ["Glenveagh"], "cc": "IE", "kind": "lake",
     "swim": "limited", "lat": 55.03, "lon": -8.0, "why": "editorial",
     "note": "Glenveagh National Park, the castle and its gardens"},
    {"n": "Lough Eske", "cc": "IE", "kind": "lake", "swim": "yes",
     "lat": 54.7, "lon": -8.05, "why": "editorial",
     "note": "under the Bluestacks in Donegal, a shore road around it"},
    {"n": "Lough Salt", "cc": "IE", "kind": "lake", "swim": "no",
     "lat": 55.08, "lon": -7.85, "why": "editorial",
     "note": "a Donegal water supply lough, swimming prohibited"},

    # ---------------------------------------------------------------- IS ----
    {"n": "Blue Lagoon", "alt": ["Blaa Lonid"], "cc": "IS", "kind": "geothermal",
     "swim": "yes", "lat": 63.88, "lon": -22.45, "why": "editorial",
     "note": "the most photographed water in Iceland, booked ahead, silica"},
    {"n": "Secret Lagoon", "alt": ["Gamla Laugin", "Gamla laugin", "Fludir"],
     "cc": "IS", "kind": "geothermal",
     "swim": "yes", "lat": 64.14, "lon": -20.31, "why": "brief",
     "note": "Fludir, the oldest swimming pool in Iceland, 38 to 40 C"},
    {"n": "Landmannalaugar", "cc": "IS", "kind": "geothermal", "swim": "yes",
     "lat": 63.99, "lon": -19.06, "why": "brief",
     "note": "highland hot river bathing, F road access only"},
    {"n": "Thingvallavatn", "alt": ["Þingvallavatn"], "cc": "IS", "kind": "lake",
     "swim": "no", "lat": 64.19, "lon": -21.1, "why": "brief", "haz": ["cold_shock"],
     "note": "the rift lake; Silfra is dry suit diving only, no casual swimming"},
    {"n": "Myvatn Nature Baths", "alt": ["Jardbodin"], "cc": "IS",
     "kind": "geothermal", "swim": "yes", "lat": 65.63, "lon": -16.85,
     "why": "editorial", "note": "the north's answer to the Blue Lagoon"},
    {"n": "Jokulsarlon", "cc": "IS", "kind": "lagoon", "swim": "no",
     "lat": 64.05, "lon": -16.18, "why": "editorial",
     "haz": ["cold_shock", "currents"],
     "note": "the glacier lagoon, icebergs and tidal currents, never a swimming water"},
    {"n": "Kerid", "alt": ["Kerið"], "cc": "IS", "kind": "crater", "swim": "no",
     "lat": 64.04, "lon": -20.89, "why": "editorial",
     "note": "a red crater holding a green lake, entry fee, no swimming"},

    # -- 2026-08-30 coverage pass. Iceland published four. The country is
    # mostly water and rock, and its lakes sit outside both Wikidata passes.
    {"n": "Myvatn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 65.6, "lon": -17.0, "why": "editorial",
     "note": "shallow volcanic lake and a protected area, midges in summer"},
    {"n": "Lagarfljot", "alt": ["Logurinn"], "cc": "IS", "kind": "lake",
     "swim": "limited", "lat": 65.2, "lon": -14.6, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "the long lake at Egilsstadir, glacial silt and its own worm"},
    {"n": "Kleifarvatn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 63.93, "lon": -21.98, "why": "editorial", "haz": ["cold_shock"],
     "note": "Reykjanes, geothermal vents on the bed, black sand shores"},
    {"n": "Thorisvatn", "cc": "IS", "kind": "reservoir",
     "swim": "no", "lat": 64.3, "lon": -18.8, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "the largest lake in Iceland, raised for hydropower, highland cold"},
    {"n": "Hvitarvatn", "cc": "IS", "kind": "lake", "swim": "no",
     "lat": 64.6, "lon": -19.83, "why": "editorial", "haz": ["cold_shock"],
     "note": "Langjokull calves into it, icebergs on the water"},
    {"n": "Langisjor", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 64.15, "lon": -18.45, "why": "editorial", "haz": ["cold_shock"],
     "note": "a blue trench in the black highland, inside Vatnajokull park"},
    {"n": "Oskjuvatn", "cc": "IS", "kind": "crater", "swim": "no",
     "lat": 65.03, "lon": -16.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Askja caldera lake, deep, cold and prone to landslides"},
    {"n": "Viti Askja", "cc": "IS", "kind": "geothermal",
     "swim": "limited", "lat": 65.05, "lon": -16.72, "why": "editorial",
     "note": "the warm crater beside Oskjuvatn, bathing comes and goes"},
    {"n": "Blondulon", "cc": "IS", "kind": "reservoir", "swim": "no",
     "lat": 65.05, "lon": -19.6, "why": "editorial", "haz": ["cold_shock"],
     "note": "a highland hydropower reservoir on the Kjolur route"},
    {"n": "Ellidavatn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 64.08, "lon": -21.79, "why": "editorial",
     "note": "Reykjavik's own lake, the Heidmork woods and a path around it"},
    {"n": "Hafravatn", "cc": "IS", "kind": "lake", "swim": "yes",
     "lat": 64.1, "lon": -21.68, "why": "editorial", "haz": ["cold_shock"],
     "note": "the swimming and angling lake above Mosfellsbaer"},
    {"n": "Ulfljotsvatn", "cc": "IS", "kind": "lake", "swim": "yes",
     "lat": 64.1, "lon": -21.03, "why": "editorial", "haz": ["cold_shock"],
     "note": "the outdoor centre lake below Thingvellir, canoes and camping"},
    {"n": "Skorradalsvatn", "cc": "IS", "kind": "lake", "swim": "yes",
     "lat": 64.52, "lon": -21.45, "why": "editorial", "haz": ["cold_shock"],
     "note": "the wooded valley lake in Borgarfjordur, summer houses"},
    {"n": "Frostastadavatn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 63.99, "lon": -19.02, "why": "editorial", "haz": ["cold_shock"],
     "note": "Landmannalaugar, lava on one side and rhyolite on the other"},
    {"n": "Ljotipollur", "cc": "IS", "kind": "crater", "swim": "limited",
     "lat": 63.98, "lon": -19.0, "why": "editorial", "haz": ["cold_shock"],
     "note": "a red rimmed explosion crater, the name means ugly puddle"},
    {"n": "Hvalvatn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 64.4, "lon": -21.2, "why": "editorial", "haz": ["cold_shock"],
     "note": "under Hvalfell above Glymur waterfall, a long walk in"},
    {"n": "Fjallsarlon", "cc": "IS", "kind": "lagoon", "swim": "no",
     "lat": 63.99, "lon": -16.38, "why": "editorial", "haz": ["cold_shock"],
     "note": "the quieter iceberg lagoon beside Jokulsarlon"},
    {"n": "Reykjadalur", "cc": "IS", "kind": "geothermal", "swim": "yes",
     "lat": 64.03, "lon": -21.21, "why": "editorial",
     "note": "the hot river above Hveragerdi, an hour's walk up the valley"},
    {"n": "Veidivotn", "cc": "IS", "kind": "lake", "swim": "limited",
     "lat": 64.15, "lon": -18.65, "why": "editorial", "haz": ["cold_shock"],
     "note": "the fishing lakes in the Bardarbunga fissure field"},

    # ---------------------------------------------------------------- IT ----
    {"n": "Lake Garda", "alt": ["Lago di Garda", "Gardasee"], "cc": "IT",
     "kind": "lake", "swim": "yes", "lat": 45.6, "lon": 10.6, "why": "brief",
     "note": "the biggest Italian lake, beaches, windsurfing in the north"},
    {"n": "Lake Como", "alt": ["Lago di Como", "Lario"], "cc": "IT", "kind": "lake",
     "swim": "yes", "lat": 45.98, "lon": 9.26, "why": "brief",
     "note": "the scenery lake, lidos at Menaggio and Bellagio"},
    {"n": "Lake Caldonazzo", "alt": ["Lago di Caldonazzo"], "cc": "IT",
     "kind": "lake", "swim": "yes", "lat": 46.0, "lon": 11.25, "why": "brief",
     "note": "Valsugana, one of the warmest lakes in Trentino"},
    {"n": "Lake Levico", "alt": ["Lago di Levico"], "cc": "IT", "kind": "lake",
     "swim": "yes", "lat": 46.01, "lon": 11.29, "why": "brief",
     "note": "the quieter twin of Caldonazzo, blue flag beaches"},
    {"n": "Lago di Braies", "alt": ["Pragser Wildsee"], "cc": "IT", "kind": "lake",
     "swim": "no", "lat": 46.69, "lon": 12.09, "why": "brief", "haz": ["cold_shock"],
     "note": "Dolomites, rowing boats only, swimming prohibited, summer access ticketed"},
    {"n": "Lago di Sorapis", "alt": ["Lago di Sorapiss", "Sorapiss"], "cc": "IT",
     "kind": "tarn", "swim": "no",
     "lat": 46.53, "lon": 12.21, "why": "editorial", "haz": ["cold_shock"],
     "note": "the milky blue Dolomite tarn, a two hour walk, swimming banned"},
    {"n": "Lago di Carezza", "alt": ["Karersee"], "cc": "IT", "kind": "lake",
     "swim": "no", "lat": 46.41, "lon": 11.58, "why": "editorial",
     "note": "the rainbow lake, fenced, no access to the water"},
    {"n": "Lake Maggiore", "alt": ["Lago Maggiore"], "cc": "IT", "kind": "lake",
     "swim": "yes", "lat": 45.95, "lon": 8.63, "why": "editorial",
     "note": "the Borromean islands, lidos, shared with Switzerland"},
    {"n": "Lago d'Iseo", "cc": "IT", "kind": "lake", "swim": "yes",
     "lat": 45.72, "lon": 10.06, "why": "editorial",
     "note": "Monte Isola, the lake island you can walk around"},
    {"n": "Lake Bolsena", "alt": ["Lago di Bolsena"], "cc": "IT", "kind": "crater",
     "swim": "yes", "lat": 42.6, "lon": 11.93, "why": "editorial",
     "note": "the largest volcanic lake in Europe, warm and clean"},
    {"n": "Lake Trasimeno", "cc": "IT", "kind": "lake", "swim": "yes",
     "lat": 43.13, "lon": 12.1, "why": "editorial",
     "note": "Umbria, shallow, three islands"},
    {"n": "Lago di Resia", "alt": ["Reschensee"], "cc": "IT", "kind": "reservoir",
     "swim": "limited", "lat": 46.81, "lon": 10.54, "why": "editorial",
     "haz": ["cold_shock"], "note": "the drowned bell tower, kitesurfing, cold"},
    {"n": "Lago di Molveno", "cc": "IT", "kind": "lake", "swim": "yes",
     "lat": 46.14, "lon": 10.96, "why": "editorial",
     "note": "under the Brenta Dolomites, repeatedly voted Italy's best lake beach"},
    {"n": "Laghi di Fusine", "cc": "IT", "kind": "lake", "swim": "no",
     "lat": 46.47, "lon": 13.68, "why": "editorial", "haz": ["cold_shock"],
     "note": "Tarvisio, two glacial lakes under Mangart, a natural park"},

    # ---------------------------------------------------------------- LI ----
    {"n": "Ganglesee", "alt": ["Gaenglesee", "Steg"], "cc": "LI",
     "kind": "reservoir", "swim": "limited", "lat": 47.11, "lon": 9.6, "why": "brief",
     "haz": ["cold_shock"], "note": "Steg, the principality's one mountain reservoir"},

    # ---------------------------------------------------------------- LT ----
    {"n": "Lake Galve", "alt": ["Galve"], "cc": "LT", "kind": "lake", "swim": "yes",
     "lat": 54.65, "lon": 24.93, "why": "brief",
     "note": "the Trakai island castle, swimming and boating"},
    {"n": "Lake Plateliai", "cc": "LT", "kind": "lake", "swim": "yes",
     "lat": 56.05, "lon": 21.83, "why": "brief", "note": "Zemaitija NP, beaches"},
    {"n": "Lake Asveja", "cc": "LT", "kind": "lake", "swim": "yes",
     "lat": 55.08, "lon": 25.4, "why": "editorial",
     "note": "the longest Lithuanian lake, a regional park"},
    {"n": "Lake Druksiai", "cc": "LT", "kind": "lake", "swim": "limited",
     "lat": 55.62, "lon": 26.6, "why": "editorial",
     "note": "the largest Lithuanian lake, the old Ignalina cooling pond"},

    # ---------------------------------------------------------------- LU ----
    {"n": "Upper Sure Lake", "alt": ["Lac de la Haute-Sure", "Stausee"], "cc": "LU",
     "kind": "reservoir", "swim": "limited", "lat": 49.9, "lon": 5.87, "why": "brief",
     "note": "a drinking water reservoir: swimming only in the designated zones at Lultzhausen, Insenborn and Liefrange"},
    {"n": "Echternach Lake", "alt": ["Lac d'Echternach"], "cc": "LU", "kind": "lake",
     "swim": "limited", "lat": 49.8, "lon": 6.42, "why": "editorial",
     "note": "the recreation lake beside the Mullerthal trails"},
    {"n": "Weiswampach Lakes", "cc": "LU", "kind": "lake", "swim": "yes",
     "lat": 50.13, "lon": 6.07, "why": "editorial", "note": "the north's swimming lakes"},

    # ---------------------------------------------------------------- LV ----
    {"n": "Lake Lubans", "alt": ["Lubana"], "cc": "LV", "kind": "lake",
     "swim": "limited", "lat": 56.75, "lon": 26.9, "why": "brief",
     "note": "the largest Latvian lake, birds, shallow and reedy"},
    {"n": "Lake Razna", "cc": "LV", "kind": "lake", "swim": "yes",
     "lat": 56.32, "lon": 27.5, "why": "editorial",
     "note": "Latgale, the land of blue lakes, a national park, beaches"},
    {"n": "Lake Alauksts", "cc": "LV", "kind": "lake", "swim": "yes",
     "lat": 57.15, "lon": 25.83, "why": "editorial",
     "note": "Vidzeme, clear, campsites"},
    {"n": "Lake Engure", "cc": "LV", "kind": "lagoon", "swim": "no",
     "lat": 57.25, "lon": 23.13, "why": "editorial",
     "note": "a nature park lagoon, one of the richest bird lakes in the Baltics"},

    # ---------------------------------------------------------------- MD ----
    {"n": "Lake Beleu", "cc": "MD", "kind": "lake", "swim": "no",
     "lat": 45.5, "lon": 28.35, "why": "editorial",
     "note": "the Prutul de Jos Ramsar wetland, birds, not a bathing water"},
    {"n": "Costesti-Stanca Reservoir", "cc": "MD", "kind": "reservoir",
     "swim": "limited", "lat": 47.83, "lon": 27.25, "why": "editorial",
     "note": "on the Prut, shared with Romania, fishing and boats"},
    {"n": "Ghidighici Reservoir", "cc": "MD", "kind": "reservoir", "swim": "yes",
     "lat": 47.07, "lon": 28.72, "why": "editorial",
     "note": "Chisinau's beach lake at Vatra"},
    {"n": "Dubasari Reservoir", "cc": "MD", "kind": "reservoir", "swim": "limited",
     "lat": 47.4, "lon": 29.1, "why": "editorial", "note": "the Dniester reservoir"},

    # ---------------------------------------------------------------- ME ----
    {"n": "Lake Skadar", "alt": ["Skadarsko jezero"], "cc": "ME", "kind": "lake",
     "swim": "yes", "lat": 42.25, "lon": 19.15, "why": "brief",
     "note": "a national park of pelicans and boat trips, swimming at Murici"},
    {"n": "Black Lake", "alt": ["Crno jezero"], "cc": "ME", "kind": "lake",
     "swim": "limited", "lat": 43.14, "lon": 19.09, "why": "brief",
     "haz": ["cold_shock"], "note": "Durmitor NP, glacial, cold, the walk around it"},
    {"n": "Piva Lake", "alt": ["Pivsko jezero"], "cc": "ME", "kind": "reservoir",
     "swim": "limited", "lat": 43.25, "lon": 18.83, "why": "brief",
     "note": "a turquoise canyon reservoir, the road above it"},
    {"n": "Biogradsko jezero", "alt": ["Biograd Lake", "Lake Biograd"], "cc": "ME",
     "kind": "lake", "swim": "no",
     "lat": 42.9, "lon": 19.6, "why": "editorial",
     "note": "Biogradska Gora NP, one of Europe's last primeval forests, no swimming"},
    {"n": "Trnovacko jezero", "cc": "ME", "kind": "tarn", "swim": "limited",
     "lat": 43.24, "lon": 18.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "the heart shaped lake under Maglic, a long walk in"},

    # -- 2026-08-30 coverage pass. Montenegro published four, and Durmitor
    # alone carries eighteen glacial lakes.
    {"n": "Krupac Lake", "alt": ["Krupacko jezero"], "cc": "ME",
     "kind": "reservoir", "swim": "yes", "lat": 42.78, "lon": 18.87,
     "why": "editorial", "note": "Niksic's summer bathing lake, a sand shore"},
    {"n": "Slano Lake", "alt": ["Slano jezero"], "cc": "ME",
     "kind": "reservoir", "swim": "limited", "lat": 42.8, "lon": 18.9,
     "why": "editorial",
     "note": "the larger Niksic reservoir, drawn down in autumn"},
    {"n": "Vrazje Lake", "alt": ["Vrazje jezero"], "cc": "ME", "kind": "lake",
     "swim": "limited", "lat": 43.13, "lon": 19.08, "why": "editorial",
     "haz": ["cold_shock"], "note": "the Devil's Lake on the Durmitor plateau"},
    {"n": "Plav Lake", "alt": ["Plavsko jezero"], "cc": "ME", "kind": "lake",
     "swim": "yes", "lat": 42.59, "lon": 19.93, "why": "editorial",
     "note": "under Prokletije, the largest glacial lake in Montenegro"},
    {"n": "Sas Lake", "alt": ["Sasko jezero"], "cc": "ME", "kind": "lake",
     "swim": "limited", "lat": 42.1, "lon": 19.28, "why": "editorial",
     "note": "a shallow bird lake behind Ulcinj, reeds to the water"},
    {"n": "Zminje Lake", "alt": ["Zminje jezero"], "cc": "ME", "kind": "tarn",
     "swim": "limited", "lat": 43.13, "lon": 19.09, "why": "editorial",
     "haz": ["cold_shock"], "note": "the Snake Lake, a short walk from Zabljak"},
    {"n": "Kapetanovo Lake", "alt": ["Kapetanovo jezero"], "cc": "ME",
     "kind": "tarn", "swim": "limited", "lat": 42.75, "lon": 19.32,
     "why": "editorial", "haz": ["cold_shock"],
     "note": "on the Lukavica plateau at 1,678 m, a rough track in"},
    {"n": "Bukumirsko Lake", "alt": ["Bukumirsko jezero"], "cc": "ME",
     "kind": "tarn", "swim": "limited", "lat": 42.63, "lon": 19.55,
     "why": "editorial", "haz": ["cold_shock"],
     "note": "a Komovi mountain lake with a legend attached to it"},
    {"n": "Riblje Lake", "alt": ["Riblje jezero"], "cc": "ME", "kind": "tarn",
     "swim": "limited", "lat": 43.11, "lon": 19.06, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "the Fish Lake, Durmitor, on the Black Lake walk"},
    {"n": "Zabojsko Lake", "alt": ["Zabojsko jezero"], "cc": "ME",
     "kind": "tarn", "swim": "limited", "lat": 43.05, "lon": 19.42,
     "why": "editorial", "haz": ["cold_shock"],
     "note": "a forest lake above the Tara canyon"},
    {"n": "Jablan Lake", "alt": ["Jablan jezero"], "cc": "ME", "kind": "tarn",
     "swim": "limited", "lat": 43.13, "lon": 19.05, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "Durmitor, the shallowest of the plateau lakes"},
    {"n": "Manito Lake", "alt": ["Manito jezero"], "cc": "ME", "kind": "tarn",
     "swim": "limited", "lat": 43.09, "lon": 19.02, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "the hardest Durmitor lake to reach, and the emptiest"},

    # ---------------------------------------------------------------- MK ----
    {"n": "Lake Ohrid", "alt": ["Ohridsko Ezero"], "cc": "MK", "kind": "lake",
     "swim": "yes", "lat": 41.05, "lon": 20.72, "why": "brief",
     "note": "UNESCO, one of the oldest lakes on earth, beaches and boardwalks"},
    {"n": "Lake Prespa", "alt": ["Prespansko Ezero"], "cc": "MK", "kind": "lake",
     "swim": "yes", "lat": 40.98, "lon": 20.98, "why": "brief",
     "note": "Golem Grad island, birds, the sandy shore at Oteshevo"},
    {"n": "Matka Canyon", "cc": "MK", "kind": "reservoir", "swim": "limited",
     "lat": 41.95, "lon": 21.3, "why": "brief",
     "note": "Skopje's canyon reservoir, kayaking and the cave"},
    {"n": "Mavrovo Lake", "cc": "MK", "kind": "reservoir", "swim": "limited",
     "lat": 41.68, "lon": 20.75, "why": "editorial",
     "note": "the half sunken church of St Nicholas, a national park"},

    # ---------------------------------------------------------------- MT ----
    {"n": "Blue Lagoon", "alt": ["Bejn il-Kmiemen"], "cc": "MT", "kind": "lagoon",
     "swim": "yes", "lat": 36.01, "lon": 14.32, "why": "brief",
     "note": "Comino. Malta has no natural lakes, so its water body is a sea lagoon; extremely crowded in summer"},
    {"n": "Chadwick Lakes", "cc": "MT", "kind": "reservoir", "swim": "no",
     "lat": 35.9, "lon": 14.4, "why": "editorial",
     "note": "a seasonal chain of dammed pools in a valley, winter and spring only"},
    {"n": "Ghadira Nature Reserve", "cc": "MT", "kind": "lagoon", "swim": "no",
     "lat": 35.97, "lon": 14.35, "why": "editorial",
     "note": "the island's main freshwater wetland, birds, no access to the water"},

    # ---------------------------------------------------------------- NL ----
    {"n": "Veluwemeer", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.37, "lon": 5.72, "why": "brief",
     "note": "a border lake with the water aqueduct, swimming and windsurfing"},
    {"n": "Wolderwijd", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.33, "lon": 5.55, "why": "brief",
     "note": "windsurfing and designated beaches"},
    {"n": "Sloterplas", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.36, "lon": 4.82, "why": "brief",
     "note": "Amsterdam's urban swimming lake"},
    {"n": "Grevelingenmeer", "cc": "NL", "kind": "lagoon", "swim": "yes",
     "lat": 51.73, "lon": 3.95, "why": "brief",
     "note": "the largest saltwater lake in western Europe, the Dutch diving water"},
    {"n": "Vinkeveense Plassen", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.23, "lon": 4.95, "why": "editorial",
     "note": "peat lakes with clear water and sand islands, diving and swimming"},
    {"n": "Loosdrechtse Plassen", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.2, "lon": 5.07, "why": "editorial",
     "note": "the sailing water near Utrecht"},
    {"n": "Henschotermeer", "cc": "NL", "kind": "lake", "swim": "yes",
     "lat": 52.07, "lon": 5.42, "why": "editorial",
     "note": "Utrechtse Heuvelrug, a family beach lake"},

    # ---------------------------------------------------------------- NO ----
    {"n": "Gjende", "cc": "NO", "kind": "lake", "swim": "no",
     "lat": 61.5, "lon": 8.75, "why": "brief", "haz": ["cold_shock"],
     "note": "Jotunheimen, the green glacial water under Besseggen"},
    {"n": "Bandak", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 59.42, "lon": 8.2, "why": "brief", "note": "the Telemark Canal, boat trips"},
    {"n": "Sognsvann", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 59.98, "lon": 10.72, "why": "brief",
     "note": "Oslo's lake at the end of the metro, the local swim"},
    {"n": "Mjosa", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 60.7, "lon": 11.0, "why": "editorial", "haz": ["cold_shock"],
     "note": "Norway's largest lake, the Skibladner paddle steamer"},
    {"n": "Lovatnet", "cc": "NO", "kind": "lake", "swim": "no",
     "lat": 61.83, "lon": 6.85, "why": "editorial", "haz": ["cold_shock"],
     "note": "the turquoise glacier lake at Loen, an Instagram fixture, ice cold"},
    {"n": "Ringedalsvatnet", "cc": "NO", "kind": "reservoir", "swim": "no",
     "lat": 60.11, "lon": 6.6, "why": "editorial", "haz": ["cold_shock", "cliffs"],
     "note": "the water under Trolltunga"},
    {"n": "Bondhusvatnet", "cc": "NO", "kind": "lake", "swim": "no",
     "lat": 60.03, "lon": 6.33, "why": "editorial", "haz": ["cold_shock"],
     "note": "Folgefonna, the milky green walk in"},

    # -- 2026-08-30 coverage pass. Norway published thirteen. It holds tens
    # of thousands of named lakes in OpenStreetMap and almost none of them
    # are written about in a language the sitelink count rewards.
    {"n": "Hornindalsvatnet", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 61.93, "lon": 6.3, "why": "editorial", "haz": ["cold_shock"],
     "note": "the deepest lake in Europe at 514 m, and cold with it"},
    {"n": "Femunden", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 62.15, "lon": 11.9, "why": "editorial", "haz": ["cold_shock"],
     "note": "the third largest Norwegian lake, a national park on its shore"},
    {"n": "Tyrifjorden", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 60.03, "lon": 10.25, "why": "editorial",
     "note": "the big lake west of Oslo, bathing places along both shores"},
    {"n": "Randsfjorden", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 60.55, "lon": 10.35, "why": "editorial",
     "note": "a long narrow lake north of Oslo with public bathing places"},
    {"n": "Vansjo", "alt": ["Vansjoen"], "cc": "NO", "kind": "lake",
     "swim": "yes", "lat": 59.42, "lon": 10.85, "why": "editorial",
     "haz": ["algal_bloom"],
     "note": "Ostfold's canoe lake, many islands, blooms in warm summers"},
    {"n": "Noklevann", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 59.87, "lon": 10.88, "why": "editorial",
     "note": "the Ostmarka forest lake in Oslo, a path all the way round"},
    {"n": "Bogstadvannet", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 59.96, "lon": 10.63, "why": "editorial",
     "note": "Oslo's family bathing lake at the edge of Nordmarka"},
    {"n": "Maridalsvannet", "cc": "NO", "kind": "lake", "swim": "no",
     "lat": 59.99, "lon": 10.79, "why": "editorial",
     "note": "Oslo's drinking water, bathing and boating both prohibited"},
    {"n": "Bygdin", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 61.33, "lon": 8.75, "why": "editorial", "haz": ["cold_shock"],
     "note": "Jotunheimen at 1,060 m, the Bitihorn above it"},
    {"n": "Tyin", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 61.28, "lon": 8.25, "why": "editorial", "haz": ["cold_shock"],
     "note": "a high lake on the road into Jotunheimen, cold all summer"},
    {"n": "Vangsmjose", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 61.13, "lon": 8.7, "why": "editorial", "haz": ["cold_shock"],
     "note": "the Valdres lake below Vang, steep sided and deep"},
    {"n": "Oldevatnet", "cc": "NO", "kind": "lake", "swim": "no",
     "lat": 61.75, "lon": 6.85, "why": "editorial", "haz": ["cold_shock"],
     "note": "meltwater from Briksdalsbreen, turquoise and near freezing"},
    {"n": "Oppstrynsvatnet", "alt": ["Strynevatnet"], "cc": "NO",
     "kind": "lake", "swim": "limited", "lat": 61.92, "lon": 7.05,
     "why": "editorial", "haz": ["cold_shock"],
     "note": "the Stryn valley lake, glacier fed and famously green"},
    {"n": "Jolstravatnet", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 61.5, "lon": 6.2, "why": "editorial", "haz": ["cold_shock"],
     "note": "Astruptunet on its shore, the painter's lake in Sunnfjord"},
    {"n": "Eikesdalsvatnet", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 62.5, "lon": 8.2, "why": "editorial", "haz": ["cold_shock"],
     "note": "Mardalsfossen falls into it, walls on both sides"},
    {"n": "Snasavatnet", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 64.15, "lon": 12.1, "why": "editorial", "haz": ["cold_shock"],
     "note": "Trondelag's largest lake, the Bolareinen rock carvings"},
    {"n": "Rossvatnet", "cc": "NO", "kind": "reservoir", "swim": "limited",
     "lat": 65.7, "lon": 13.9, "why": "editorial", "haz": ["cold_shock"],
     "note": "the second largest lake in Norway, raised for hydropower"},
    {"n": "Tinnsja", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 59.9, "lon": 8.95, "why": "editorial", "haz": ["cold_shock"],
     "note": "460 m deep, the ferry the heavy water went down with"},
    {"n": "Norsjo", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 59.35, "lon": 9.3, "why": "editorial",
     "note": "on the Telemark canal, locks and summer bathing places"},
    {"n": "Kroderen", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 60.2, "lon": 9.8, "why": "editorial",
     "note": "the Kroderbanen heritage railway runs beside it"},
    {"n": "Selbusjoen", "cc": "NO", "kind": "lake", "swim": "yes",
     "lat": 63.25, "lon": 11.0, "why": "editorial",
     "note": "the bathing lake east of Trondheim, sandy shores at Selbu"},
    {"n": "Altevatnet", "cc": "NO", "kind": "lake", "swim": "limited",
     "lat": 68.75, "lon": 18.3, "why": "editorial", "haz": ["cold_shock"],
     "note": "inner Troms, Sami reindeer country, the ice goes out in June"},

    # ---------------------------------------------------------------- PL ----
    {"n": "Sniardwy", "alt": ["Lake Sniardwy"], "cc": "PL", "kind": "lake",
     "swim": "yes", "lat": 53.77, "lon": 21.75, "why": "brief",
     "note": "the largest Polish lake, Masuria, sailing"},
    {"n": "Hancza", "cc": "PL", "kind": "lake", "swim": "yes",
     "lat": 54.27, "lon": 22.82, "why": "brief", "haz": ["cold_shock"],
     "note": "the deepest lake on the north European plain, clear, diving"},
    {"n": "Solina", "cc": "PL", "kind": "reservoir", "swim": "yes",
     "lat": 49.4, "lon": 22.45, "why": "brief", "note": "Bieszczady, the Polish sea"},
    {"n": "Morskie Oko", "cc": "PL", "kind": "tarn", "swim": "no",
     "lat": 49.2, "lon": 20.07, "why": "brief", "haz": ["cold_shock"],
     "note": "Tatra NP, the most visited lake in Poland, swimming strictly forbidden"},
    {"n": "Lake Mamry", "cc": "PL", "kind": "lake", "swim": "yes",
     "lat": 54.13, "lon": 21.75, "why": "editorial",
     "note": "Masuria, sailing and swimming"},
    {"n": "Lake Wigry", "cc": "PL", "kind": "lake", "swim": "yes",
     "lat": 54.02, "lon": 23.07, "why": "editorial",
     "note": "Wigry NP, the camaldolese monastery on the water"},
    {"n": "Jezioro Turkusowe", "cc": "PL", "kind": "lake", "swim": "limited",
     "lat": 53.87, "lon": 14.45, "why": "editorial",
     "note": "Wolin, a flooded chalk quarry, turquoise"},

    # ---------------------------------------------------------------- PT ----
    {"n": "Lagoa das Sete Cidades", "cc": "PT", "kind": "crater", "swim": "limited",
     "lat": 37.86, "lon": -25.79, "why": "brief",
     "note": "Sao Miguel, the green and blue crater lakes, swimming only in marked spots"},
    {"n": "Barragem do Alqueva", "cc": "PT", "kind": "reservoir", "swim": "yes",
     "lat": 38.2, "lon": -7.5, "why": "brief",
     "note": "the largest artificial lake in western Europe, a dark sky reserve"},
    {"n": "Lagoa Comprida", "cc": "PT", "kind": "reservoir", "swim": "limited",
     "lat": 40.36, "lon": -7.65, "why": "brief", "haz": ["cold_shock"],
     "note": "Serra da Estrela, high and cold"},
    {"n": "Lagoa do Fogo", "cc": "PT", "kind": "crater", "swim": "limited",
     "lat": 37.77, "lon": -25.47, "why": "editorial",
     "note": "Sao Miguel, a nature reserve, a steep walk down to the shore"},
    {"n": "Lagoa das Furnas", "cc": "PT", "kind": "crater", "swim": "no",
     "lat": 37.76, "lon": -25.32, "why": "editorial",
     "note": "the cozido cooked in the ground, fumaroles, no swimming"},
    {"n": "Barragem de Castelo do Bode", "cc": "PT", "kind": "reservoir",
     "swim": "yes", "lat": 39.55, "lon": -8.32, "why": "editorial",
     "note": "the Zezere reservoir, the best known Portuguese inland beaches"},
    {"n": "Praia Fluvial do Alamal", "cc": "PT", "kind": "river", "swim": "yes",
     "lat": 39.47, "lon": -7.93, "why": "editorial",
     "note": "one of the country's designated river beaches, on the Tagus"},

    # ---------------------------------------------------------------- RO ----
    {"n": "Lacul Sfanta Ana", "cc": "RO", "kind": "crater", "swim": "limited",
     "lat": 46.13, "lon": 25.89, "why": "brief",
     "note": "the only crater lake in Romania, protected, rules change by season"},
    {"n": "Lake Vidraru", "cc": "RO", "kind": "reservoir", "swim": "limited",
     "lat": 45.36, "lon": 24.63, "why": "brief",
     "note": "on the Transfagarasan, the dam and the statue"},
    {"n": "Lacul Rosu", "alt": ["Red Lake"], "cc": "RO", "kind": "lake",
     "swim": "no", "lat": 46.79, "lon": 25.79, "why": "brief",
     "note": "the drowned forest, boats only, no swimming"},
    {"n": "Techirghiol", "cc": "RO", "kind": "lake", "swim": "yes",
     "lat": 44.05, "lon": 28.6, "why": "brief",
     "note": "a hypersaline therapeutic lake, the black mud, floating like the Dead Sea"},
    {"n": "Balea Lake", "alt": ["Lacul Balea"], "cc": "RO", "kind": "tarn",
     "swim": "no", "lat": 45.6, "lon": 24.62, "why": "editorial",
     "haz": ["cold_shock"],
     "note": "2,034 m on the Transfagarasan, the ice hotel in winter"},
    {"n": "Lacul Izvorul Muntelui", "alt": ["Bicaz"], "cc": "RO",
     "kind": "reservoir", "swim": "limited", "lat": 46.93, "lon": 26.05,
     "why": "editorial", "note": "the largest Romanian reservoir, Ceahlau above it"},

    # ---------------------------------------------------------------- RS ----
    {"n": "Lake Palic", "cc": "RS", "kind": "lake", "swim": "yes",
     "lat": 46.1, "lon": 19.77, "why": "brief",
     "note": "Subotica, the art nouveau spa resort on its shore"},
    {"n": "Silver Lake", "alt": ["Srebrno jezero"], "cc": "RS", "kind": "lake",
     "swim": "yes", "lat": 44.65, "lon": 21.4, "why": "brief",
     "note": "a Danube backwater sold as the Serbian sea"},
    {"n": "Lake Perucac", "alt": ["Perucac", "Perućac"], "cc": "RS",
     "kind": "reservoir", "swim": "limited",
     "lat": 43.95, "lon": 19.42, "why": "brief", "note": "Tara NP, the Drina house"},
    {"n": "Zaovine", "cc": "RS", "kind": "reservoir", "swim": "limited",
     "lat": 43.87, "lon": 19.45, "why": "brief", "haz": ["cold_shock"],
     "note": "Tara NP, high and cold"},
    {"n": "Uvac", "cc": "RS", "kind": "reservoir", "swim": "limited",
     "lat": 43.4, "lon": 19.9, "why": "brief",
     "note": "the meanders and the griffon vultures, boat trips and the ice cave"},
    {"n": "Vlasina Lake", "cc": "RS", "kind": "reservoir", "swim": "limited",
     "lat": 42.72, "lon": 22.33, "why": "editorial",
     "note": "1,200 m, the floating peat islands"},
    {"n": "Ada Ciganlija", "cc": "RS", "kind": "lake", "swim": "yes",
     "lat": 44.79, "lon": 20.4, "why": "editorial",
     "note": "Belgrade's river island lake, the city's summer"},

    # ---------------------------------------------------------------- SE ----
    {"n": "Vanern", "cc": "SE", "kind": "lake", "swim": "yes",
     "lat": 58.9, "lon": 13.3, "why": "brief",
     "note": "the largest lake in the EU, an archipelago biosphere reserve"},
    {"n": "Vattern", "cc": "SE", "kind": "lake", "swim": "yes",
     "lat": 58.4, "lon": 14.6, "why": "brief", "haz": ["cold_shock"],
     "note": "extremely clear and cold, Visingso, diving"},
    {"n": "Siljan", "cc": "SE", "kind": "lake", "swim": "yes",
     "lat": 60.83, "lon": 14.75, "why": "brief", "note": "Dalarna, midsummer country"},
    {"n": "Malaren", "cc": "SE", "kind": "lake", "swim": "yes",
     "lat": 59.4, "lon": 17.2, "why": "brief",
     "note": "Stockholm swims in it, Drottningholm and Birka on it"},
    {"n": "Tornetrask", "cc": "SE", "kind": "lake", "swim": "no",
     "lat": 68.35, "lon": 19.15, "why": "editorial", "haz": ["cold_shock"],
     "note": "Abisko, above the Arctic Circle"},
    {"n": "Storsjon", "cc": "SE", "kind": "lake", "swim": "yes",
     "lat": 63.15, "lon": 14.4, "why": "editorial",
     "note": "Ostersund, and the lake monster"},

    # ---------------------------------------------------------------- SI ----
    {"n": "Lake Bohinj", "alt": ["Bohinjsko jezero"], "cc": "SI", "kind": "lake",
     "swim": "yes", "lat": 46.28, "lon": 13.88, "why": "brief",
     "note": "Triglav NP, the largest Slovenian lake, quieter than Bled, SUP and swimming"},
    {"n": "Lake Bled", "alt": ["Blejsko jezero"], "cc": "SI", "kind": "lake",
     "swim": "yes", "lat": 46.36, "lon": 14.1, "why": "brief",
     "note": "the island church and the castle, 20 to 24 C, grassy lidos"},
    {"n": "Soca", "alt": ["Isonzo"], "cc": "SI", "kind": "river", "swim": "limited",
     "lat": 46.33, "lon": 13.55, "why": "brief", "haz": ["cold_shock", "currents"],
     "note": "the emerald river, rafting and kayaking from Bovec, alpine cold"},
    {"n": "Lake Jasna", "alt": ["Jezero Jasna"], "cc": "SI", "kind": "lake",
     "swim": "yes", "lat": 46.47, "lon": 13.78, "why": "brief",
     "note": "Kranjska Gora, the ibex statue, small and clear"},
    {"n": "Lake Cerknica", "alt": ["Cerknisko jezero"], "cc": "SI", "kind": "lake",
     "swim": "limited", "lat": 45.75, "lon": 14.35, "why": "editorial",
     "note": "the intermittent lake that empties every summer"},

    # ---------------------------------------------------------------- SK ----
    {"n": "Strbske pleso", "cc": "SK", "kind": "tarn", "swim": "no",
     "lat": 49.12, "lon": 20.06, "why": "brief", "haz": ["cold_shock"],
     "note": "High Tatras, TANAP rules, swimming and boats forbidden"},
    {"n": "Zemplinska sirava", "cc": "SK", "kind": "reservoir", "swim": "yes",
     "lat": 48.8, "lon": 22.0, "why": "brief", "note": "the Slovak sea, beaches"},
    {"n": "Liptovska Mara", "cc": "SK", "kind": "reservoir", "swim": "yes",
     "lat": 49.08, "lon": 19.55, "why": "brief",
     "note": "the Liptov reservoir, watersports"},
    {"n": "Velke Hincovo pleso", "cc": "SK", "kind": "tarn", "swim": "no",
     "lat": 49.17, "lon": 20.05, "why": "editorial", "haz": ["cold_shock"],
     "note": "the deepest Tatra tarn, national park, no swimming"},
    {"n": "Sulovske skaly", "alt": ["Sulov"], "cc": "SK", "kind": "lake",
     "swim": "limited", "lat": 49.16, "lon": 18.5, "why": "brief",
     "note": "the rock town and the small quarry lakes below it"},
    {"n": "Slnecne jazera", "alt": ["Senec Sunny Lakes"], "cc": "SK", "kind": "lake",
     "swim": "yes", "lat": 48.22, "lon": 17.4, "why": "editorial",
     "note": "Senec, Bratislava's summer lakes"},

    # ---------------------------------------------------------------- SM ----
    {"n": "Lago di Faetano", "alt": ["Laghetto di Faetano", "Faetano"],
     "cc": "SM", "kind": "lake", "swim": "no",
     "lat": 43.94, "lon": 12.5, "why": "editorial",
     "note": "the republic's one lake, a fishing and walking pond at Faetano"},

    # ---------------------------------------------------------------- XK ----
    {"n": "Batlava Lake", "alt": ["Liqeni i Batllaves"], "cc": "XK",
     "kind": "reservoir", "swim": "limited", "lat": 42.82, "lon": 21.32,
     "why": "brief",
     "note": "Pristina's summer lake; parts serve water supply, check locally"},
    {"n": "Badovc Lake", "alt": ["Liqeni i Badovcit", "Badoc Lake", "Badovc"],
     "cc": "XK",
     "kind": "reservoir", "swim": "no",
     "lat": 42.63, "lon": 21.25, "why": "brief",
     "note": "a Pristina drinking water reservoir, swimming restricted"},
    {"n": "Mirusha Waterfalls", "alt": ["Mirusha", "Ujevarat e Mirushes"],
     "cc": "XK", "kind": "river", "swim": "limited",
     "lat": 42.55, "lon": 20.65, "why": "brief", "haz": ["currents"],
     "note": "a chain of thirteen falls and pools, a regional park"},
    {"n": "Gazivoda Lake", "alt": ["Ujmani"], "cc": "XK", "kind": "reservoir",
     "swim": "limited", "lat": 42.95, "lon": 20.6, "why": "editorial",
     "note": "the largest reservoir in Kosovo, on the Ibar"},
]

# Countries with no inland water body worth publishing. Written down rather
# than left to an empty result, so the difference between "we found nothing"
# and "there is nothing" is a fact in the repo rather than a guess in a review.
NO_WATER = {
    "MC": "Monaco has no lake, river or lagoon within its two square kilometres",
}


def by_country():
    """{cc: [entry, ...]} in file order, which is the order a tie breaks in."""
    out = {}
    for row in SEED:
        out.setdefault(row["cc"], []).append(row)
    return out


def countries():
    return sorted({row["cc"] for row in SEED})


if __name__ == "__main__":
    groups = by_country()
    print(f"{len(SEED)} seeded water bodies across {len(groups)} countries")
    for cc in sorted(groups):
        rows = groups[cc]
        bans = sum(1 for r in rows if r.get("swim") == "no")
        brief = sum(1 for r in rows if r.get("why") == "brief")
        print(f"  {cc}: {len(rows):>2}  ({brief} from the brief, {bans} no-swim)")
    for cc, why in sorted(NO_WATER.items()):
        print(f"  {cc}: none by design ({why})")
