"""The curated seed: the mountains a European traveller has actually heard of.

Everything else in this layer is machine found. This file is the one place a
human decides, and it exists for four reasons the open data cannot cover on
its own.

  fame that no field carries.  Sitelinks and pageviews find Mont Blanc. They
        do not reliably find Seceda, Reinebringen, Segla, Roque Nublo or the
        Old Man of Storr, which are on every travel feed and which Wikidata
        records as ordinary items with a handful of sitelinks. A ranking that
        misses those is wrong in the way a traveller notices first.
  the cable car is the point.  Schilthorn, Klein Matterhorn, Dajti, Srd,
        Vodno, Tornik, Gaustatoppen and Monte Solaro are not the highest or
        the most prominent things in their country. They are the mountains
        somebody without boots can stand on top of, which for most of this
        app's readers is the only kind that counts. The brief says to boost
        accessibility deliberately; this is where the boost gets its facts.
  every country gets an answer.  The gate in export_peaks.py would otherwise
        publish forty Alpine summits and nothing for the Netherlands, Malta or
        Moldova. Each seeded entry is pinned into its country's list, so a
        country with five honest high points shows five rather than none.
  height is the wrong question in half of Europe.  The highest natural point
        of the European Netherlands is a wooded 322 m road junction, and the
        thing people actually go and look at in Denmark is a chalk cliff.
        Lowland entries are seeded on what somebody would travel to see, not
        on elevation.

Fields
    n       the searchable name, English where an English name is in use
    alt     other names to match on: the local name, the name on the signpost
    cc      ISO2, the country the entry is published under
    kind    peak | volcano | massif | ridge | plateau | cliff | hill | rock
    lift    how you get up without climbing it, curated because OSM's
            aerialway geometry is good and its opening data is not:
              cable_car | gondola | funicular | rack | chairlift | road | ""
            "" means feet only. It is merged with whatever Overpass finds
            around the summit, and the wire records which of the two said so.
    lat/lon approximate, ONLY a disambiguation hint for the resolver. Never
            published: the coordinate that ships is Wikidata's or OSM's.
    wd      an explicit Wikidata id, for the few entries entity search cannot
            reach on any query string. Use it sparingly and only after
            checking the item is the right one.
    why     brief     named in the research brief this layer was built from
            editorial added here because it is what travel writing names
    haz     curated hazards, merged with whatever the machine finds
    note    why this entry is here, for the next person reading the file.
            Internal. It is never shipped, and no sentence in the app is
            written from it.

ASCII clean, no em dashes, per project convention.
"""

SEED = [
    # ---------------------------------------------------------------- AD ----
    {"n": "Coma Pedrosa", "alt": ["Pic de Coma Pedrosa"], "cc": "AD", "kind": "peak",
     "lift": "", "lat": 42.59, "lon": 1.45, "why": "brief",
     "note": "highest point of Andorra, the principality's one obligatory summit"},
    {"n": "Pic de Casamanya", "cc": "AD", "kind": "peak", "lift": "",
     "lat": 42.55, "lon": 1.57, "why": "editorial",
     "note": "the classic Ordino day walk, the whole country from the top"},
    {"n": "Pic Blanc", "alt": ["Pic Blanc del Pessons"], "cc": "AD", "kind": "peak",
     "lift": "chairlift", "lat": 42.53, "lon": 1.71, "why": "editorial",
     "note": "Grandvalira lifts run to the Pessons cirque under it"},
    {"n": "Pic de Tristaina", "alt": ["Tristaina"], "cc": "AD", "kind": "peak",
     "lift": "chairlift", "lat": 42.63, "lon": 1.47, "why": "editorial",
     "note": "Ordino Arcalis lift to the three lakes, the Andorran photograph"},

    # ---------------------------------------------------------------- AL ----
    {"n": "Mount Dajti", "alt": ["Mali i Dajtit"], "cc": "AL", "kind": "peak",
     "lift": "cable_car", "lat": 41.36, "lon": 19.93, "why": "brief",
     "note": "Dajti Ekspres from Tirana, the most used tourist cable car in the Balkans"},
    {"n": "Maja Jezerce", "alt": ["Jezerce"], "cc": "AL", "kind": "peak",
     "lift": "", "lat": 42.44, "lon": 19.81, "why": "brief",
     "note": "highest of the Accursed Mountains, the Theth and Valbona country"},
    {"n": "Maja e Korabit", "alt": ["Korab", "Golem Korab"], "cc": "AL", "kind": "peak",
     "lift": "", "lat": 41.79, "lon": 20.55, "why": "brief",
     "note": "highest point of Albania, shared with North Macedonia"},
    {"n": "Maja e Harapit", "alt": ["Arapi", "Maja e Arapit"], "cc": "AL",
     "kind": "peak", "wd": "Q626160",
     "lift": "", "lat": 42.42, "lon": 19.79, "why": "editorial",
     "note": "the big wall above Theth, Albania's answer to a Dolomite face"},
    {"n": "Maja e Cikes", "alt": ["Cika"], "cc": "AL", "kind": "peak",
     "lift": "", "lat": 40.16, "lon": 19.66, "why": "editorial",
     "note": "the Llogara pass mountain, sea to summit above the Riviera"},
    {"n": "Mount Tomorr", "alt": ["Mali i Tomorrit"], "cc": "AL", "kind": "massif",
     "lift": "", "lat": 40.63, "lon": 20.15, "why": "editorial",
     "note": "the holy mountain above Berat, pilgrimage in August"},

    # ---------------------------------------------------------------- AT ----
    {"n": "Grossglockner", "cc": "AT", "kind": "peak", "lift": "",
     "lat": 47.07, "lon": 12.69, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "highest in Austria, and the Hochalpenstrasse looks straight at it"},
    {"n": "Wildspitze", "cc": "AT", "kind": "peak", "lift": "",
     "lat": 46.89, "lon": 10.87, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "second highest, the Otztal glacier country"},
    {"n": "Grossvenediger", "cc": "AT", "kind": "peak", "lift": "",
     "lat": 47.11, "lon": 12.35, "why": "editorial", "haz": ["glacier"],
     "note": "the other Hohe Tauern giant, a glacier walk from every side"},
    {"n": "Hoher Dachstein", "alt": ["Dachstein"], "cc": "AT", "kind": "massif",
     "lift": "cable_car", "lat": 47.48, "lon": 13.61, "why": "brief",
     "note": "glacier cable car, sky walk and the staircase to nothing"},
    {"n": "Hafelekarspitze", "alt": ["Nordkette", "Hafelekar"], "cc": "AT", "kind": "peak",
     "lift": "cable_car", "lat": 47.31, "lon": 11.38, "why": "brief",
     "note": "Innsbruck's Nordkettenbahn, city centre to 2,300 m in twenty minutes"},
    {"n": "Kitzsteinhorn", "cc": "AT", "kind": "peak", "lift": "cable_car",
     "lat": 47.19, "lon": 12.69, "why": "editorial",
     "note": "Kaprun glacier lifts, open in summer, the Top of Salzburg platform"},
    {"n": "Schneeberg", "cc": "AT", "kind": "peak", "lift": "rack",
     "lat": 47.77, "lon": 15.81, "why": "editorial",
     "note": "the Salamander rack railway, Vienna's own mountain"},
    {"n": "Rax", "alt": ["Raxalpe", "Heukuppe"], "cc": "AT", "kind": "plateau",
     "lift": "cable_car", "lat": 47.71, "lon": 15.72, "why": "editorial",
     "note": "Austria's oldest passenger cable car, a walking plateau on top"},
    {"n": "Schafberg", "cc": "AT", "kind": "peak", "lift": "rack",
     "lat": 47.78, "lon": 13.44, "why": "editorial",
     "note": "cog railway from St Wolfgang, the Salzkammergut lakes laid out"},
    {"n": "Untersberg", "cc": "AT", "kind": "massif", "lift": "cable_car",
     "lat": 47.72, "lon": 13.01, "why": "editorial",
     "note": "Salzburg's cable car mountain, half of it in Bavaria"},
    {"n": "Gaislachkogl", "cc": "AT", "kind": "peak", "lift": "cable_car",
     "lat": 46.95, "lon": 10.98, "why": "editorial",
     "note": "Solden, and the Bond museum built into the summit"},
    {"n": "Pfander", "cc": "AT", "kind": "peak", "lift": "cable_car",
     "lat": 47.51, "lon": 9.78, "why": "editorial",
     "note": "Bregenz cable car, the whole of Lake Constance from the terrace"},
    {"n": "Kitzbuheler Horn", "cc": "AT", "kind": "peak", "lift": "gondola",
     "lat": 47.46, "lon": 12.42, "why": "editorial",
     "note": "toll road and gondola, an alpine flower garden at the top"},
    {"n": "Ahornspitze", "alt": ["Ahorn"], "cc": "AT", "kind": "peak",
     "lift": "cable_car", "lat": 47.14, "lon": 11.87, "why": "editorial",
     "note": "Mayrhofen's Ahornbahn, the largest cable car cabin in Austria"},
    {"n": "Zugspitze", "cc": "AT", "kind": "peak", "lift": "cable_car",
     "lat": 47.42, "lon": 10.98, "why": "editorial",
     "note": "the Tyrolean side has its own cable car, from Ehrwald"},
    {"n": "Hochkonig", "cc": "AT", "kind": "massif", "lift": "gondola",
     "lat": 47.42, "lon": 13.06, "why": "editorial", "haz": ["glacier"],
     "note": "the limestone wall over the Salzburg lowland, hut on the summit"},

    # ---------------------------------------------------------------- BA ----
    {"n": "Maglic", "cc": "BA", "kind": "peak", "lift": "",
     "lat": 43.28, "lon": 18.75, "why": "brief",
     "note": "highest in Bosnia, above the Perucica primeval forest"},
    {"n": "Bjelasnica", "cc": "BA", "kind": "peak", "lift": "chairlift",
     "lat": 43.71, "lon": 18.27, "why": "editorial",
     "note": "the 1984 Olympic downhill mountain, lifts above Sarajevo"},
    {"n": "Trebevic", "cc": "BA", "kind": "peak", "lift": "cable_car",
     "lat": 43.83, "lon": 18.44, "why": "brief",
     "note": "the rebuilt Sarajevo cable car and the abandoned bobsleigh track"},
    {"n": "Cvrsnica", "alt": ["Plocno", "Hajducka vrata"], "cc": "BA", "kind": "massif",
     "lift": "", "lat": 43.61, "lon": 17.6, "why": "editorial",
     "note": "the rock arch of Hajducka vrata, Blidinje's white wall"},
    {"n": "Prenj", "alt": ["Zelena glava"], "cc": "BA", "kind": "massif", "lift": "",
     "lat": 43.53, "lon": 17.92, "why": "editorial",
     "note": "called the Herzegovinian Himalaya, straight up from Mostar's valley"},
    {"n": "Vlasic", "alt": ["Paljenik"], "cc": "BA", "kind": "massif", "lift": "chairlift",
     "lat": 44.31, "lon": 17.63, "why": "editorial",
     "note": "high pasture, the cheese, a small ski area above Travnik"},

    # ---------------------------------------------------------------- BE ----
    {"n": "Signal de Botrange", "cc": "BE", "kind": "hill", "lift": "road",
     "lat": 50.5, "lon": 6.09, "why": "brief",
     "note": "highest point of Belgium at 694 m, a tower on a moor"},
    {"n": "Baraque de Fraiture", "cc": "BE", "kind": "hill", "lift": "chairlift",
     "lat": 50.25, "lon": 5.75, "why": "editorial",
     "note": "second highest, and the country's only real ski lift"},
    {"n": "Kemmelberg", "cc": "BE", "kind": "hill", "lift": "road",
     "lat": 50.79, "lon": 2.82, "why": "editorial",
     "note": "the West Flanders cobbled climb, a war memorial on top"},
    {"n": "Mont Saint-Aubert", "cc": "BE", "kind": "hill", "lift": "road",
     "lat": 50.66, "lon": 3.4, "why": "editorial",
     "note": "the Tournai balcony, flat country for fifty kilometres"},
    {"n": "Rochers de Freyr", "alt": ["Freyr"], "cc": "BE", "kind": "cliff", "lift": "",
     "lat": 50.22, "lon": 4.9, "why": "editorial",
     "note": "the Meuse limestone walls, Belgium's climbing cathedral"},
    {"n": "Mont Rigi", "cc": "BE", "kind": "hill", "lift": "road",
     "lat": 50.51, "lon": 6.07, "why": "editorial",
     "note": "the High Fens plateau, boardwalks over the peat bog"},

    # ---------------------------------------------------------------- BG ----
    {"n": "Musala", "cc": "BG", "kind": "peak", "lift": "gondola",
     "lat": 42.18, "lon": 23.59, "why": "brief",
     "note": "highest in the Balkans, gondola from Borovets to the hut chain"},
    {"n": "Vihren", "cc": "BG", "kind": "peak", "lift": "",
     "lat": 41.76, "lon": 23.41, "why": "brief",
     "note": "the marble summit of Pirin, above the Banderitsa lakes"},
    {"n": "Cherni Vrah", "alt": ["Vitosha"], "cc": "BG", "kind": "peak",
     "lift": "chairlift", "lat": 42.59, "lon": 23.27, "why": "brief",
     "note": "Sofia's own mountain, a tram ride and then a lift"},
    {"n": "Botev Peak", "alt": ["Botev"], "cc": "BG", "kind": "peak", "lift": "",
     "lat": 42.71, "lon": 24.92, "why": "editorial",
     "note": "highest of the Stara Planina, the range that names the peninsula"},
    {"n": "Malyovitsa", "cc": "BG", "kind": "peak", "lift": "",
     "lat": 42.17, "lon": 23.36, "why": "editorial",
     "note": "the Rila climbing school peak, the Seven Lakes over the ridge"},
    {"n": "Todorka", "cc": "BG", "kind": "peak", "lift": "gondola",
     "lat": 41.77, "lon": 23.44, "why": "editorial",
     "note": "Bansko's gondola mountain, Pirin's postcard from the piste"},
    {"n": "Belogradchik Rocks", "alt": ["Belogradchishki skali"], "cc": "BG",
     "kind": "rock", "lift": "", "lat": 43.62, "lon": 22.68, "why": "editorial",
     "note": "red sandstone towers with a fortress built into them"},
    {"n": "Shipka Peak", "alt": ["Stoletov"], "cc": "BG", "kind": "peak", "lift": "road",
     "lat": 42.75, "lon": 25.32, "why": "editorial",
     "note": "the freedom monument on the pass, 894 steps up to it"},

    # ---------------------------------------------------------------- CH ----
    {"n": "Matterhorn", "alt": ["Cervin", "Monte Cervino"], "cc": "CH", "kind": "peak",
     "lift": "", "lat": 45.98, "lon": 7.66, "why": "brief",
     "haz": ["rockfall", "glacier", "altitude", "exposure"],
     "note": "the most drawn mountain on earth, and Zermatt looks straight up it"},
    {"n": "Klein Matterhorn", "alt": ["Matterhorn Glacier Paradise"], "cc": "CH",
     "kind": "peak", "lift": "cable_car", "lat": 45.94, "lon": 7.73, "why": "brief",
     "haz": ["altitude"],
     "note": "highest cable car station in Europe at 3,883 m, open all year"},
    {"n": "Jungfrau", "cc": "CH", "kind": "peak", "lift": "rack",
     "lat": 46.54, "lon": 7.96, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "the Jungfraujoch railway tunnels through the Eiger to 3,454 m"},
    {"n": "Eiger", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.58, "lon": 8.01, "why": "brief", "haz": ["rockfall", "exposure"],
     "note": "the north face, and the Eiger Express gondola under it"},
    {"n": "Monch", "cc": "CH", "kind": "peak", "lift": "rack",
     "lat": 46.56, "lon": 7.99, "why": "editorial", "haz": ["glacier", "altitude"],
     "note": "the middle of the three, reached from the Jungfraujoch"},
    {"n": "Schilthorn", "alt": ["Piz Gloria"], "cc": "CH", "kind": "peak",
     "lift": "cable_car", "lat": 46.56, "lon": 7.84, "why": "brief",
     "note": "the revolving restaurant from the Bond film, 200 summits from it"},
    {"n": "Dufourspitze", "alt": ["Monte Rosa"], "cc": "CH", "kind": "peak", "lift": "",
     "lat": 45.94, "lon": 7.87, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "highest point of Switzerland, on the Monte Rosa massif"},
    {"n": "Piz Bernina", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.38, "lon": 9.91, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "the easternmost four-thousander, Diavolezza looks across at it"},
    {"n": "Pilatus", "cc": "CH", "kind": "massif", "lift": "rack",
     "lat": 46.98, "lon": 8.25, "why": "brief",
     "note": "the steepest cogwheel railway in the world, Lucerne below"},
    {"n": "Rigi", "alt": ["Rigi Kulm"], "cc": "CH", "kind": "peak", "lift": "rack",
     "lat": 47.06, "lon": 8.49, "why": "brief",
     "note": "queen of the mountains, and Europe's first mountain railway, 1871"},
    {"n": "Titlis", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.77, "lon": 8.44, "why": "brief", "haz": ["glacier"],
     "note": "the Rotair revolving cabin, the cliff walk and the glacier cave"},
    {"n": "Santis", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 47.25, "lon": 9.34, "why": "editorial",
     "note": "six countries on a clear day, the tower on the Alpstein"},
    {"n": "Gornergrat", "cc": "CH", "kind": "ridge", "lift": "rack",
     "lat": 45.98, "lon": 7.79, "why": "brief",
     "note": "the cog railway ridge with 29 four-thousanders in one view"},
    {"n": "Piz Nair", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.5, "lon": 9.81, "why": "editorial",
     "note": "St Moritz's funicular and cable car to 3,057 m"},
    {"n": "Diavolezza", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.41, "lon": 9.97, "why": "editorial",
     "note": "the balcony opposite Bernina and the Morteratsch glacier"},
    {"n": "Brienzer Rothorn", "cc": "CH", "kind": "peak", "lift": "rack",
     "lat": 46.79, "lon": 8.05, "why": "editorial",
     "note": "the last steam cog railway in Switzerland, Brienz turquoise below"},
    {"n": "Niesen", "cc": "CH", "kind": "peak", "lift": "funicular",
     "lat": 46.65, "lon": 7.65, "why": "editorial",
     "note": "the pyramid over Thun, and the longest stairway in the world beside it"},
    {"n": "Stanserhorn", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.93, "lon": 8.34, "why": "editorial",
     "note": "the open top deck Cabrio cable car, the only one of its kind"},
    {"n": "Harder Kulm", "cc": "CH", "kind": "peak", "lift": "funicular",
     "lat": 46.7, "lon": 7.87, "why": "editorial",
     "note": "Interlaken's funicular and the Two Lakes Bridge platform"},
    {"n": "First", "alt": ["Grindelwald First"], "cc": "CH", "kind": "peak",
     "lift": "gondola", "lat": 46.66, "lon": 8.05, "why": "editorial",
     "note": "the Cliff Walk, and the Bachalpsee an hour further"},
    {"n": "Mannlichen", "cc": "CH", "kind": "peak", "lift": "cable_car",
     "lat": 46.61, "lon": 7.94, "why": "editorial",
     "note": "the panorama walk to Kleine Scheidegg, level the whole way"},
    {"n": "Faulhorn", "cc": "CH", "kind": "peak", "lift": "",
     "lat": 46.67, "lon": 8.03, "why": "editorial",
     "note": "the oldest mountain hotel in the Alps, and the walk in from First"},
    {"n": "Weisshorn", "cc": "CH", "kind": "peak", "lift": "",
     "lat": 46.1, "lon": 7.71, "why": "editorial", "haz": ["glacier", "altitude"],
     "note": "the mountaineer's favourite shape in the Valais"},
    {"n": "Monte Generoso", "cc": "CH", "kind": "peak", "lift": "rack",
     "lat": 45.93, "lon": 9.02, "why": "editorial",
     "note": "the Ticino cog railway and Botta's stone flower on top"},
    {"n": "Creux du Van", "cc": "CH", "kind": "cliff", "lift": "",
     "lat": 46.93, "lon": 6.73, "why": "editorial", "haz": ["exposure"],
     "note": "a 160 m rock amphitheatre in the Jura, ibex on the rim"},
    {"n": "Eggishorn", "alt": ["Aletsch Arena"], "cc": "CH", "kind": "peak",
     "lift": "cable_car", "lat": 46.43, "lon": 8.09, "why": "editorial",
     "note": "the viewpoint over the longest glacier in the Alps"},

    # ---------------------------------------------------------------- CY ----
    {"n": "Mount Olympus", "alt": ["Chionistra", "Troodos"], "cc": "CY", "kind": "peak",
     "lift": "road", "lat": 34.94, "lon": 32.87, "why": "brief",
     "note": "highest in Cyprus, snow in February and a road to the top"},
    {"n": "Papoutsa", "alt": ["Madari", "Adelfoi"], "cc": "CY", "kind": "peak",
     "lift": "", "wd": "Q22988504", "lat": 34.91, "lon": 33.09, "why": "editorial",
     "note": "second highest in Cyprus, the Troodos ridge walk and both coasts"},
    {"n": "Stavrovouni", "cc": "CY", "kind": "hill", "lift": "road",
     "lat": 34.88, "lon": 33.43, "why": "editorial",
     "note": "the fourth century monastery on a cone above the Larnaca plain"},
    {"n": "Cape Greco", "alt": ["Kavo Gkreko"], "cc": "CY", "kind": "cliff", "lift": "",
     "lat": 34.96, "lon": 34.07, "why": "editorial",
     "note": "the sea cliffs and arches at the island's eastern corner"},

    # ---------------------------------------------------------------- CZ ----
    {"n": "Snezka", "cc": "CZ", "kind": "peak", "lift": "cable_car",
     "lat": 50.74, "lon": 15.74, "why": "brief",
     "note": "highest in Czechia, cable car from Pec, the chapel on the border"},
    {"n": "Praded", "cc": "CZ", "kind": "peak", "lift": "road",
     "lat": 50.08, "lon": 17.23, "why": "editorial",
     "note": "the Jeseniky tower you can see from Poland"},
    {"n": "Jested", "cc": "CZ", "kind": "peak", "lift": "cable_car",
     "lat": 50.73, "lon": 14.99, "why": "brief",
     "note": "the hyperboloid hotel and transmitter above Liberec"},
    {"n": "Lysa hora", "cc": "CZ", "kind": "peak", "lift": "road",
     "lat": 49.55, "lon": 18.45, "why": "editorial",
     "note": "the Beskydy high point, the wettest place in the country"},
    {"n": "Radhost", "cc": "CZ", "kind": "peak", "lift": "chairlift",
     "lat": 49.5, "lon": 18.25, "why": "editorial",
     "note": "the pagan idol and the wooden chapel on the ridge"},
    {"n": "Milesovka", "cc": "CZ", "kind": "peak", "lift": "",
     "lat": 50.55, "lon": 13.93, "why": "editorial",
     "note": "the Bohemian highlands' cone, the windiest summit in Czechia"},
    {"n": "Petrin", "cc": "CZ", "kind": "hill", "lift": "funicular",
     "lat": 50.08, "lon": 14.4, "why": "editorial",
     "note": "Prague's funicular hill and its small Eiffel tower"},
    {"n": "Rip", "alt": ["Rip Mountain"], "cc": "CZ", "kind": "hill", "lift": "",
     "lat": 50.4, "lon": 14.29, "why": "editorial",
     "note": "the hill the Czech founding legend starts on, a rotunda on top"},
    {"n": "Klet", "cc": "CZ", "kind": "peak", "lift": "chairlift",
     "lat": 48.87, "lon": 14.29, "why": "editorial",
     "note": "chairlift, observatory and the oldest stone lookout in Bohemia"},

    # ---------------------------------------------------------------- DE ----
    {"n": "Zugspitze", "cc": "DE", "kind": "peak",
     "lift": "rack", "lat": 47.42, "lon": 10.98, "why": "brief",
     "note": "Germany's high point, cog railway and cable car, a glacier below"},
    {"n": "Watzmann", "cc": "DE", "kind": "massif", "lift": "",
     "lat": 47.55, "lon": 12.92, "why": "editorial", "haz": ["exposure", "rockfall"],
     "note": "the east face is the highest wall in the Eastern Alps, Konigssee under it"},
    {"n": "Feldberg", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.87, "lon": 8.0, "why": "editorial",
     "note": "highest in the Black Forest, and the highest German summit outside the Alps"},
    {"n": "Brocken", "cc": "DE", "kind": "peak", "lift": "rack",
     "lat": 51.8, "lon": 10.62, "why": "brief",
     "note": "the Harz steam railway, Walpurgis night, fog three days in four"},
    {"n": "Wendelstein", "cc": "DE", "kind": "peak", "lift": "rack",
     "lat": 47.7, "lon": 12.01, "why": "editorial",
     "note": "Bavaria's oldest cog railway, a church and an observatory on top"},
    {"n": "Nebelhorn", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.42, "lon": 10.34, "why": "editorial",
     "note": "Oberstdorf's cable car and the 400 peaks panorama walk"},
    {"n": "Alpspitze", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.43, "lon": 11.06, "why": "editorial", "haz": ["exposure"],
     "note": "the AlpspiX viewing platform over Garmisch and the Hollental"},
    {"n": "Kehlsteinhaus", "alt": ["Eagle's Nest", "Kehlstein"], "cc": "DE",
     "kind": "peak", "lift": "road", "lat": 47.61, "lon": 13.04, "why": "editorial",
     "note": "bus up the mountain road and a brass lift through the rock"},
    {"n": "Jenner", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.57, "lon": 13.0, "why": "editorial",
     "note": "the Konigssee from above, straight down onto the green water"},
    {"n": "Schauinsland", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.91, "lon": 7.9, "why": "editorial",
     "note": "Germany's longest loop cable car, twenty minutes from Freiburg"},
    {"n": "Grosser Arber", "cc": "DE", "kind": "peak", "lift": "gondola",
     "lat": 49.11, "lon": 13.14, "why": "editorial",
     "note": "king of the Bavarian Forest, gondola and a summit chapel"},
    {"n": "Fichtelberg", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 50.43, "lon": 12.95, "why": "editorial",
     "note": "highest in Saxony, the oldest cable car in Germany runs up it"},
    {"n": "Drachenfels", "cc": "DE", "kind": "hill", "lift": "rack",
     "lat": 50.66, "lon": 7.21, "why": "editorial",
     "note": "the Rhine castle hill, oldest rack railway in Germany, 1883"},
    {"n": "Konigsstuhl", "alt": ["Kreidefelsen", "Jasmund"], "cc": "DE", "kind": "cliff",
     "lift": "", "lat": 54.57, "lon": 13.65, "why": "editorial",
     "note": "the Rugen chalk cliffs Caspar David Friedrich painted"},
    {"n": "Lorelei", "alt": ["Loreley"], "cc": "DE", "kind": "rock", "lift": "road",
     "lat": 50.14, "lon": 7.73, "why": "editorial",
     "note": "the slate rock in the Rhine gorge, the song and the bend in the river"},
    {"n": "Hochblauen", "alt": ["Blauen", "Belchen"], "cc": "DE", "kind": "peak",
     "lift": "cable_car", "lat": 47.82, "lon": 7.83, "why": "editorial",
     "note": "the Black Forest balcony over the Rhine plain to the Alps"},
    {"n": "Herzogstand", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.6, "lon": 11.31, "why": "editorial",
     "note": "the ridge walk between two turquoise lakes, the king's own view"},
    {"n": "Tegelberg", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.57, "lon": 10.77, "why": "editorial",
     "note": "the cable car above Neuschwanstein, paragliders off the top"},
    {"n": "Predigtstuhl", "cc": "DE", "kind": "peak", "lift": "cable_car",
     "lat": 47.7, "lon": 12.85, "why": "editorial",
     "note": "the oldest large cable car in the world still running, 1928"},
    {"n": "Grosser Feldberg", "cc": "DE", "kind": "peak", "lift": "road",
     "lat": 50.23, "lon": 8.46, "why": "editorial",
     "note": "the Taunus high point, Frankfurt's Sunday mountain"},

    # ---------------------------------------------------------------- DK ----
    {"n": "Mons Klint", "alt": ["Moens Klint"], "cc": "DK", "kind": "cliff", "lift": "",
     "wd": "Q1517331", "lat": 54.97, "lon": 12.54, "why": "brief",
     "haz": ["rockfall", "exposure"],
     "note": "128 m of white chalk straight into the Baltic, the Danish landscape"},
    {"n": "Mollehoj", "alt": ["Moellehoej"], "cc": "DK", "kind": "hill", "lift": "road",
     "lat": 56.02, "lon": 9.71, "why": "brief",
     "note": "highest natural point of Denmark at 171 m, a field and a millstone"},
    {"n": "Himmelbjerget", "cc": "DK", "kind": "hill", "lift": "road",
     "lat": 56.04, "lon": 9.68, "why": "brief",
     "note": "the sky mountain, a tower over the lakes, once thought the highest"},
    {"n": "Ejer Bavnehoj", "cc": "DK", "kind": "hill", "lift": "road",
     "lat": 55.97, "lon": 9.83, "why": "editorial",
     "note": "the tower that held the title until the survey moved it"},
    {"n": "Rubjerg Knude", "cc": "DK", "kind": "hill", "lift": "",
     "lat": 57.45, "lon": 9.77, "why": "editorial",
     "note": "the migrating dune that swallowed a lighthouse"},
    {"n": "Bulbjerg", "cc": "DK", "kind": "cliff", "lift": "",
     "lat": 57.15, "lon": 9.02, "why": "editorial",
     "note": "the only bird cliff on the Danish mainland, limestone over the sea"},

    # ---------------------------------------------------------------- EE ----
    {"n": "Suur Munamagi", "cc": "EE", "kind": "hill", "lift": "road",
     "lat": 57.72, "lon": 27.06, "why": "brief",
     "note": "highest point of the Baltics at 318 m, an observation tower on it"},
    {"n": "Ontika Cliff", "alt": ["Ontika pank", "Baltic Klint"], "cc": "EE",
     "kind": "cliff", "lift": "", "lat": 59.44, "lon": 27.13, "why": "editorial",
     "note": "the highest stretch of the Baltic limestone escarpment, 56 m"},
    {"n": "Valgehobusemagi", "cc": "EE", "kind": "hill", "lift": "chairlift",
     "wd": "Q23890450", "lat": 58.99, "lon": 26.05, "why": "editorial",
     "note": "the white horse hill, Estonia's ski lift and lookout tower"},
    {"n": "Emumagi", "cc": "EE", "kind": "hill", "lift": "road",
     "lat": 59.0, "lon": 26.42, "why": "editorial",
     "note": "north Estonia's high point, a tower above the forest"},

    # ---------------------------------------------------------------- ES ----
    {"n": "Teide", "alt": ["Pico del Teide", "Mount Teide"], "cc": "ES", "kind": "volcano",
     "lift": "cable_car", "lat": 28.27, "lon": -16.64, "why": "brief",
     "haz": ["altitude", "volcanic"],
     "note": "highest in Spain, cable car to 3,555 m, a permit for the last cone"},
    {"n": "Mulhacen", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 37.05, "lon": -3.31, "why": "brief", "haz": ["altitude"],
     "note": "highest on the Spanish mainland, the Sierra Nevada roof"},
    {"n": "Pico Veleta", "cc": "ES", "kind": "peak", "lift": "gondola",
     "lat": 37.06, "lon": -3.37, "why": "editorial",
     "note": "the highest road in Europe runs at it, and the Sierra Nevada lifts"},
    {"n": "Aneto", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 42.63, "lon": 0.66, "why": "brief", "haz": ["glacier", "altitude"],
     "note": "highest in the Pyrenees, the last big glacier under it"},
    {"n": "Naranjo de Bulnes", "alt": ["Picu Urriellu"], "cc": "ES", "kind": "peak",
     "lift": "cable_car", "lat": 43.2, "lon": -4.81, "why": "brief",
     "haz": ["exposure"],
     "note": "the limestone tooth of the Picos, and the Fuente De cable car nearby"},
    {"n": "Montserrat", "cc": "ES", "kind": "massif", "lift": "rack",
     "lat": 41.59, "lon": 1.83, "why": "brief",
     "note": "serrated conglomerate, a monastery in it, rack railway and cable car"},
    {"n": "Roque Nublo", "cc": "ES", "kind": "rock", "lift": "",
     "lat": 27.97, "lon": -15.61, "why": "editorial",
     "note": "the 80 m basalt monolith at the centre of Gran Canaria"},
    {"n": "Roque de los Muchachos", "cc": "ES", "kind": "peak", "lift": "road",
     "lat": 28.75, "lon": -17.89, "why": "editorial",
     "note": "La Palma's rim, the great telescopes and a sea of cloud below"},
    {"n": "Monte Perdido", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 42.67, "lon": 0.03, "why": "editorial", "haz": ["glacier"],
     "note": "the Ordesa canyon's headwall, UNESCO on both sides of the border"},
    {"n": "Pedraforca", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 42.24, "lon": 1.71, "why": "editorial", "haz": ["rockfall"],
     "note": "the stone fork, Catalonia's climbing symbol"},
    {"n": "Torre de Cerredo", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 43.2, "lon": -4.85, "why": "editorial",
     "note": "highest of the Picos de Europa, deep in the Cantabrian karst"},
    {"n": "Penalara", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 40.85, "lon": -3.95, "why": "editorial",
     "note": "Madrid's own summit, glacial lakes on the north side"},
    {"n": "Tibidabo", "cc": "ES", "kind": "hill", "lift": "funicular",
     "lat": 41.42, "lon": 2.12, "why": "editorial",
     "note": "the funicular, the church and the old fairground over Barcelona"},
    {"n": "Montjuic", "cc": "ES", "kind": "hill", "lift": "cable_car",
     "lat": 41.36, "lon": 2.16, "why": "editorial",
     "note": "the harbour cable car and the castle on the Barcelona headland"},
    {"n": "La Concha", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 36.55, "lon": -4.95, "why": "editorial",
     "note": "the shell shaped mountain over Marbella, Africa on a clear day"},
    {"n": "Moncayo", "cc": "ES", "kind": "peak", "lift": "",
     "lat": 41.79, "lon": -1.84, "why": "editorial",
     "note": "the snow cone over the Ebro, Aragon's landmark"},
    {"n": "Caldera de Taburiente", "cc": "ES", "kind": "massif", "lift": "",
     "lat": 28.72, "lon": -17.87, "why": "editorial",
     "note": "an eight kilometre erosion caldera, waterfalls and Canary pine"},
    {"n": "Pico de las Nieves", "cc": "ES", "kind": "peak", "lift": "road",
     "lat": 27.96, "lon": -15.57, "why": "editorial",
     "note": "the roof of Gran Canaria, Teide across the water at dawn"},

    # ---------------------------------------------------------------- FI ----
    {"n": "Halti", "alt": ["Haltitunturi"], "cc": "FI", "kind": "peak", "lift": "",
     "lat": 69.31, "lon": 21.27, "why": "brief",
     "note": "highest point of Finland, four days' walk from the nearest road"},
    {"n": "Saana", "cc": "FI", "kind": "peak", "lift": "",
     "lat": 69.04, "lon": 20.85, "why": "brief",
     "note": "the sacred fell over Kilpisjarvi, the Finnish arctic photograph"},
    {"n": "Koli", "alt": ["Ukko-Koli"], "cc": "FI", "kind": "hill", "lift": "chairlift",
     "lat": 63.1, "lon": 29.81, "why": "brief",
     "note": "the national landscape, painted by every Finnish romantic"},
    {"n": "Yllas", "alt": ["Yllastunturi"], "cc": "FI", "kind": "peak", "lift": "gondola",
     "lat": 67.56, "lon": 24.24, "why": "editorial",
     "note": "the gondola fell in Lapland, seven months of snow"},
    {"n": "Levi", "alt": ["Levitunturi"], "cc": "FI", "kind": "peak", "lift": "gondola",
     "lat": 67.8, "lon": 24.81, "why": "editorial",
     "note": "Finland's busiest ski fell, a gondola from the village"},
    {"n": "Pallastunturi", "alt": ["Taivaskero"], "cc": "FI", "kind": "peak", "lift": "",
     "lat": 68.05, "lon": 24.1, "why": "editorial",
     "note": "the cleanest air in Europe, measured, and the Hetta trail starts here"},
    {"n": "Aavasaksa", "cc": "FI", "kind": "hill", "lift": "road",
     "lat": 66.4, "lon": 23.72, "why": "editorial",
     "note": "the midnight sun hill on the Arctic Circle, a pavilion on top"},

    # ---------------------------------------------------------------- FO ----
    {"n": "Slaettaratindur", "cc": "FO", "kind": "peak", "lift": "",
     "lat": 62.28, "lon": -6.94, "why": "brief",
     "note": "highest in the Faroes at 880 m, both coasts from the top"},
    {"n": "Villingadalsfjall", "cc": "FO", "kind": "peak", "lift": "",
     "lat": 62.34, "lon": -6.55, "why": "editorial", "haz": ["exposure", "weather"],
     "note": "Vidoy's peak above the Enniberg sea cliff"},
    {"n": "Kallur", "alt": ["Kalsoy", "Kallur Lighthouse"], "cc": "FO", "kind": "cliff",
     "lift": "", "lat": 62.35, "lon": -6.79, "why": "editorial", "haz": ["exposure"],
     "note": "the lighthouse headland on Kalsoy, the most photographed walk here"},
    {"n": "Trollkonufingur", "cc": "FO", "kind": "rock", "lift": "",
     "lat": 61.95, "lon": -6.79, "why": "editorial",
     "note": "the witch's finger, a 313 m sea stack off Vagar"},
    {"n": "Sornfelli", "cc": "FO", "kind": "peak", "lift": "road",
     "lat": 62.09, "lon": -6.94, "why": "editorial",
     "note": "the radar road, the highest you can drive in the islands"},

    # ---------------------------------------------------------------- FR ----
    {"n": "Mont Blanc", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 45.83, "lon": 6.86, "why": "brief", "haz": ["glacier", "altitude", "rockfall"],
     "note": "the roof of the Alps, and Chamonix underneath it"},
    {"n": "Aiguille du Midi", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 45.88, "lon": 6.89, "why": "brief", "haz": ["altitude", "exposure"],
     "note": "3,842 m by cable car in twenty minutes, the Step into the Void"},
    {"n": "Mont Ventoux", "cc": "FR", "kind": "peak", "lift": "road",
     "lat": 44.17, "lon": 5.28, "why": "brief",
     "note": "the bald giant of Provence, the Tour's cruellest climb"},
    {"n": "Puy de Dome", "cc": "FR", "kind": "volcano", "lift": "rack",
     "lat": 45.77, "lon": 2.96, "why": "brief",
     "note": "the Panoramique des Domes rack railway, eighty volcanoes in a line"},
    {"n": "Pic du Midi de Bigorre", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 42.94, "lon": 0.14, "why": "brief",
     "note": "cable car to an observatory, a dark sky reserve, sleep at 2,877 m"},
    {"n": "Mont Aiguille", "cc": "FR", "kind": "peak", "lift": "",
     "lat": 44.84, "lon": 5.55, "why": "editorial", "haz": ["exposure"],
     "note": "the inaccessible mountain of 1492, where mountaineering begins"},
    {"n": "Puy de Sancy", "cc": "FR", "kind": "volcano", "lift": "cable_car",
     "lat": 45.53, "lon": 2.81, "why": "editorial",
     "note": "highest in the Massif Central, cable car and then a staircase"},
    {"n": "Le Brevent", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 45.93, "lon": 6.84, "why": "editorial",
     "note": "the Chamonix balcony that looks straight across at Mont Blanc"},
    {"n": "La Meije", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 45.0, "lon": 6.31, "why": "editorial", "haz": ["glacier", "exposure"],
     "note": "the last big Alp to be climbed, and La Grave's cable car under it"},
    {"n": "Barre des Ecrins", "cc": "FR", "kind": "peak", "lift": "",
     "lat": 44.92, "lon": 6.36, "why": "editorial", "haz": ["glacier", "altitude"],
     "note": "the highest summit entirely in France outside the Mont Blanc massif"},
    {"n": "Monte Cinto", "cc": "FR", "kind": "peak", "lift": "",
     "lat": 42.38, "lon": 8.92, "why": "editorial",
     "note": "highest in Corsica, the GR20 crosses under it"},
    {"n": "Aiguilles de Bavella", "cc": "FR", "kind": "rock", "lift": "",
     "lat": 41.79, "lon": 9.22, "why": "editorial",
     "note": "the red needles of southern Corsica above the pass"},
    {"n": "Grand Ballon", "cc": "FR", "kind": "peak", "lift": "road",
     "lat": 47.9, "lon": 7.1, "why": "editorial",
     "note": "highest of the Vosges, the Route des Cretes and the Alps on the horizon"},
    {"n": "Mont Aigoual", "cc": "FR", "kind": "peak", "lift": "road",
     "lat": 44.12, "lon": 3.58, "why": "editorial",
     "note": "the last manned mountain weather station in France"},
    {"n": "Mont Saleve", "cc": "FR", "kind": "peak", "lift": "cable_car",
     "lat": 46.13, "lon": 6.18, "why": "editorial",
     "note": "Geneva's balcony, a cable car from the tram stop"},
    {"n": "Aiguille Verte", "cc": "FR", "kind": "peak", "lift": "",
     "lat": 45.93, "lon": 6.97, "why": "editorial", "haz": ["glacier", "exposure"],
     "note": "the hardest of the Chamonix classics, seen from every terrace"},
    {"n": "Vignemale", "cc": "FR", "kind": "peak", "lift": "",
     "lat": 42.77, "lon": -0.15, "why": "editorial", "haz": ["glacier"],
     "note": "the highest French Pyrenean summit, the Ossoue glacier under the north face"},
    {"n": "Roc de Chere", "alt": ["Mont Veyrier"], "cc": "FR", "kind": "hill", "lift": "",
     "lat": 45.88, "lon": 6.19, "why": "editorial",
     "note": "the balconies over Lake Annecy, paragliders all afternoon"},

    # ---------------------------------------------------------------- GB ----
    {"n": "Ben Nevis", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 56.8, "lon": -5.0, "why": "brief", "haz": ["weather", "navigation"],
     "note": "highest in the British Isles, the Pony Track or the north face"},
    {"n": "Snowdon", "alt": ["Yr Wyddfa"], "cc": "GB", "kind": "peak", "lift": "rack",
     "lat": 53.07, "lon": -4.08, "why": "brief",
     "note": "the Snowdon Mountain Railway, the busiest summit in Britain"},
    {"n": "Scafell Pike", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 54.45, "lon": -3.21, "why": "brief", "haz": ["weather", "navigation"],
     "note": "highest in England, the Lake District's own three peaks leg"},
    {"n": "Old Man of Storr", "alt": ["The Storr"], "cc": "GB", "kind": "rock", "lift": "",
     "lat": 57.51, "lon": -6.18, "why": "brief",
     "note": "the Skye pinnacle, the most photographed hour in Scotland"},
    {"n": "Quiraing", "cc": "GB", "kind": "ridge", "lift": "",
     "lat": 57.64, "lon": -6.29, "why": "editorial",
     "note": "the landslip terraces on Trotternish, still moving"},
    {"n": "Arthur's Seat", "cc": "GB", "kind": "hill", "lift": "",
     "lat": 55.94, "lon": -3.16, "why": "editorial",
     "note": "an extinct volcano in the middle of Edinburgh, forty minutes up"},
    {"n": "Cairn Gorm", "cc": "GB", "kind": "peak", "lift": "funicular",
     "lat": 57.12, "lon": -3.64, "why": "editorial",
     "note": "the Cairngorm funicular, the sub-arctic plateau above it"},
    {"n": "Buachaille Etive Mor", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 56.64, "lon": -4.9, "why": "editorial",
     "note": "the pyramid at the mouth of Glencoe, every calendar's March"},
    {"n": "Pen y Fan", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 51.88, "lon": -3.44, "why": "editorial",
     "note": "highest in southern Britain, the Brecon Beacons flat top"},
    {"n": "Tryfan", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 53.11, "lon": -3.99, "why": "editorial", "haz": ["exposure"],
     "note": "the only Welsh summit you have to use your hands for, Adam and Eve on top"},
    {"n": "Helvellyn", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 54.53, "lon": -3.02, "why": "editorial", "haz": ["exposure", "weather"],
     "note": "Striding Edge, the most walked ridge in England"},
    {"n": "Suilven", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 58.11, "lon": -5.14, "why": "editorial",
     "note": "a sandstone whale rising alone out of Assynt bog"},
    {"n": "Stac Pollaidh", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 58.04, "lon": -5.2, "why": "editorial",
     "note": "small, spiky and straight off the road, the best hour in the north west"},
    {"n": "Slieve Donard", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 54.18, "lon": -5.92, "why": "editorial",
     "note": "highest in Northern Ireland, the Mourne wall to the sea at Newcastle"},
    {"n": "Cadair Idris", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 52.7, "lon": -3.91, "why": "editorial",
     "note": "the chair of Idris, a cwm lake and the legend about sleeping there"},
    {"n": "Great Gable", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 54.48, "lon": -3.22, "why": "editorial",
     "note": "the dome at the head of Wasdale, the club's war memorial on top"},
    {"n": "Catbells", "cc": "GB", "kind": "hill", "lift": "",
     "lat": 54.57, "lon": -3.17, "why": "editorial",
     "note": "the friendliest ridge in the Lakes, a launch across Derwentwater to it"},
    {"n": "Roseberry Topping", "cc": "GB", "kind": "hill", "lift": "",
     "lat": 54.5, "lon": -1.11, "why": "editorial",
     "note": "the half-collapsed cone of the North York Moors"},
    {"n": "Sgurr Alasdair", "alt": ["Cuillin"], "cc": "GB", "kind": "peak", "lift": "",
     "lat": 57.21, "lon": -6.22, "why": "editorial", "haz": ["exposure", "navigation"],
     "note": "highest on Skye, the black gabbro ridge that eats compasses"},
    {"n": "Ben Lomond", "cc": "GB", "kind": "peak", "lift": "",
     "lat": 56.19, "lon": -4.63, "why": "editorial",
     "note": "the first Munro for most of Glasgow, the loch the whole way up"},
    {"n": "Worcestershire Beacon", "alt": ["Malvern Hills"], "cc": "GB", "kind": "hill",
     "lift": "", "lat": 52.11, "lon": -2.34, "why": "editorial",
     "note": "the ridge Elgar walked, thirteen counties from the top"},
    {"n": "Box Hill", "cc": "GB", "kind": "hill", "lift": "",
     "lat": 51.25, "lon": -0.31, "why": "editorial",
     "note": "London's escarpment, the Olympic road race climbed it nine times"},

    # ---------------------------------------------------------------- GR ----
    {"n": "Mount Olympus", "alt": ["Mytikas", "Olympos"], "cc": "GR", "kind": "massif",
     "lift": "", "lat": 40.09, "lon": 22.36, "why": "brief", "haz": ["exposure"],
     "note": "the home of the gods, and a real scramble on the last hundred metres"},
    {"n": "Meteora", "cc": "GR", "kind": "rock", "lift": "road",
     "lat": 39.72, "lon": 21.63, "why": "brief",
     "note": "sandstone towers with monasteries on top, UNESCO, reachable by bus"},
    {"n": "Mount Parnassus", "alt": ["Liakoura"], "cc": "GR", "kind": "massif",
     "lift": "chairlift", "lat": 38.53, "lon": 22.62, "why": "editorial",
     "note": "Delphi sits under it and Athens skis on it"},
    {"n": "Psiloritis", "alt": ["Mount Ida", "Timios Stavros"], "cc": "GR", "kind": "peak",
     "lift": "", "lat": 35.23, "lon": 24.77, "why": "editorial",
     "note": "highest in Crete, the cave where Zeus was raised on its flank"},
    {"n": "Pachnes", "alt": ["Lefka Ori", "White Mountains"], "cc": "GR", "kind": "massif",
     "lift": "", "lat": 35.32, "lon": 24.05, "why": "editorial",
     "note": "the white desert above the Samaria gorge"},
    {"n": "Mount Athos", "cc": "GR", "kind": "peak", "lift": "",
     "lat": 40.16, "lon": 24.33, "why": "editorial",
     "note": "the holy mountain, a monastic republic, men only and by permit"},
    {"n": "Astraka", "alt": ["Tymfi", "Gamila"], "cc": "GR", "kind": "peak", "lift": "",
     "lat": 39.98, "lon": 20.79, "why": "editorial",
     "note": "the Zagori towers above the Vikos gorge, the Dragon Lake behind"},
    {"n": "Mount Pelion", "alt": ["Pilio"], "cc": "GR", "kind": "massif", "lift": "chairlift",
     "lat": 39.42, "lon": 23.05, "why": "editorial",
     "note": "the centaurs' mountain, beech forest down to Aegean beaches"},
    {"n": "Lycabettus", "alt": ["Lykavittos"], "cc": "GR", "kind": "hill",
     "lift": "funicular", "lat": 37.98, "lon": 23.74, "why": "editorial",
     "note": "the funicular hill over Athens, the Acropolis lit up below"},
    {"n": "Smolikas", "cc": "GR", "kind": "peak", "lift": "",
     "lat": 40.09, "lon": 20.92, "why": "editorial",
     "note": "second highest in Greece, the Dragon Lake on its shoulder"},
    {"n": "Nisyros", "alt": ["Stefanos crater"], "cc": "GR", "kind": "volcano", "lift": "road",
     "lat": 36.59, "lon": 27.16, "why": "editorial", "haz": ["volcanic"],
     "note": "you walk into the crater floor and it hisses at you"},
    {"n": "Taygetus", "alt": ["Profitis Ilias"], "cc": "GR", "kind": "massif", "lift": "",
     "lat": 36.96, "lon": 22.34, "why": "editorial",
     "note": "the Mani's spine, Sparta at its foot and snow into May"},

    # ---------------------------------------------------------------- HR ----
    {"n": "Srd", "cc": "HR", "kind": "hill", "lift": "cable_car",
     "lat": 42.65, "lon": 18.11, "why": "brief",
     "note": "the Dubrovnik cable car, the old town roofs and the islands from the top"},
    {"n": "Sveti Jure", "alt": ["Biokovo"], "cc": "HR", "kind": "peak", "lift": "road",
     "lat": 43.32, "lon": 17.06, "why": "brief",
     "note": "1,762 m straight up from Makarska, the glass skywalk on the way"},
    {"n": "Dinara", "alt": ["Sinjal"], "cc": "HR", "kind": "peak", "lift": "",
     "lat": 44.06, "lon": 16.38, "why": "brief",
     "note": "highest in Croatia, the range that names the whole Dinaric system"},
    {"n": "Sljeme", "alt": ["Medvednica"], "cc": "HR", "kind": "peak", "lift": "cable_car",
     "lat": 45.91, "lon": 15.97, "why": "editorial",
     "note": "Zagreb's mountain, a new cable car from the tram terminus"},
    {"n": "Vaganski vrh", "alt": ["Velebit"], "cc": "HR", "kind": "peak", "lift": "",
     "lat": 44.34, "lon": 15.51, "why": "editorial",
     "note": "the roof of Velebit, the Adriatic on one side and Lika on the other"},
    {"n": "Ucka", "alt": ["Vojak"], "cc": "HR", "kind": "peak", "lift": "road",
     "lat": 45.29, "lon": 14.2, "why": "editorial",
     "note": "the tower over Opatija, Venice visible on the clearest days"},
    {"n": "Marjan", "cc": "HR", "kind": "hill", "lift": "",
     "lat": 43.51, "lon": 16.41, "why": "editorial",
     "note": "the pine headland above Split, steps up from the old town"},
    {"n": "Premuziceva staza", "alt": ["Hajducki kukovi", "Rozanski kukovi"], "cc": "HR",
     "kind": "rock", "lift": "", "lat": 44.79, "lon": 14.98, "why": "editorial",
     "note": "the stone karst towers of north Velebit, the famous drystone path through them"},

    # ---------------------------------------------------------------- HU ----
    {"n": "Kekes", "cc": "HU", "kind": "peak", "lift": "road",
     "lat": 47.87, "lon": 20.01, "why": "brief",
     "note": "highest in Hungary at 1,014 m, a television tower on it"},
    {"n": "Janos-hegy", "alt": ["Janos Hill", "Elizabeth Lookout"], "cc": "HU",
     "kind": "hill", "lift": "chairlift", "lat": 47.52, "lon": 18.96, "why": "brief",
     "note": "Budapest's high point, the chairlift and the Elizabeth Lookout"},
    {"n": "Gellert Hill", "alt": ["Gellert-hegy"], "cc": "HU", "kind": "hill", "lift": "",
     "lat": 47.49, "lon": 19.04, "why": "editorial",
     "note": "the Citadella and the Liberty Statue over the Danube bend"},
    {"n": "Badacsony", "cc": "HU", "kind": "hill", "lift": "road",
     "lat": 46.79, "lon": 17.5, "why": "editorial",
     "note": "the basalt witness hill over Balaton, vineyards on every side"},
    {"n": "Dobogo-ko", "cc": "HU", "kind": "hill", "lift": "road",
     "lat": 47.72, "lon": 18.9, "why": "editorial",
     "note": "the Pilis viewpoint the Danube bend was painted from"},
    {"n": "Istallos-ko", "cc": "HU", "kind": "peak", "lift": "",
     "lat": 48.06, "lon": 20.42, "why": "editorial",
     "note": "the Bukk's high point, a cave under it with ice age finds"},

    # ---------------------------------------------------------------- IE ----
    {"n": "Carrauntoohil", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 51.999, "lon": -9.74, "why": "brief", "haz": ["weather", "exposure"],
     "note": "highest in Ireland, the Devil's Ladder up into MacGillycuddy's Reeks"},
    {"n": "Croagh Patrick", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 53.76, "lon": -9.66, "why": "brief",
     "note": "the pilgrimage cone over Clew Bay, some climb it barefoot in July"},
    {"n": "Cliffs of Moher", "cc": "IE", "kind": "cliff", "lift": "",
     "lat": 52.97, "lon": -9.43, "why": "brief", "haz": ["exposure", "wind"],
     "note": "214 m of Atlantic wall, the most visited natural place in Ireland"},
    {"n": "Slieve League", "alt": ["Sliabh Liag"], "cc": "IE", "kind": "cliff", "lift": "",
     "lat": 54.63, "lon": -8.69, "why": "brief", "haz": ["exposure", "wind"],
     "note": "sea cliffs three times the height of Moher, and almost empty"},
    {"n": "Ben Bulben", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 54.37, "lon": -8.47, "why": "editorial",
     "note": "the table mountain of Sligo, Yeats buried under it"},
    {"n": "Errigal", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 55.03, "lon": -8.11, "why": "editorial",
     "note": "the quartzite cone of Donegal, pink at sunset"},
    {"n": "Diamond Hill", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 53.55, "lon": -9.94, "why": "editorial",
     "note": "Connemara's boardwalked summit, the Twelve Bens across the bog"},
    {"n": "Mount Brandon", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 52.24, "lon": -10.25, "why": "editorial", "haz": ["weather", "navigation"],
     "note": "the Dingle pilgrim path up the second highest in Ireland"},
    {"n": "Great Sugar Loaf", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 53.15, "lon": -6.15, "why": "editorial",
     "note": "the little cone every Dubliner has climbed, forty minutes up"},
    {"n": "Djouce", "cc": "IE", "kind": "peak", "lift": "",
     "lat": 53.13, "lon": -6.24, "why": "editorial",
     "note": "the Wicklow Way's best hour, Powerscourt waterfall below"},

    # ---------------------------------------------------------------- IS ----
    {"n": "Kirkjufell", "cc": "IS", "kind": "peak", "lift": "",
     "lat": 64.94, "lon": -23.31, "why": "brief",
     "note": "the church mountain with the waterfall in front, Iceland's most photographed"},
    {"n": "Hvannadalshnukur", "cc": "IS", "kind": "peak", "lift": "",
     "lat": 64.02, "lon": -16.68, "why": "brief", "haz": ["glacier", "crevasse"],
     "note": "highest in Iceland, on the rim of the Oraefajokull crater"},
    {"n": "Snaefellsjokull", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 64.81, "lon": -23.78, "why": "brief", "haz": ["glacier", "volcanic"],
     "note": "the glacier volcano at the end of the peninsula, Verne's way in"},
    {"n": "Esja", "cc": "IS", "kind": "massif", "lift": "",
     "lat": 64.24, "lon": -21.72, "why": "brief",
     "note": "Reykjavik's own mountain, twenty minutes from the city"},
    {"n": "Vestrahorn", "alt": ["Stokksnes"], "cc": "IS", "kind": "peak", "lift": "",
     "lat": 64.25, "lon": -14.99, "why": "editorial",
     "note": "black sand, a lagoon and a set of gabbro spikes behind it"},
    {"n": "Eyjafjallajokull", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 63.63, "lon": -19.62, "why": "editorial", "haz": ["glacier", "volcanic"],
     "note": "the 2010 eruption that stopped Europe's aeroplanes"},
    {"n": "Herdubreid", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 65.18, "lon": -16.34, "why": "editorial",
     "note": "the queen of Icelandic mountains, a table volcano in the desert"},
    {"n": "Hekla", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 63.99, "lon": -19.67, "why": "editorial", "haz": ["volcanic"],
     "note": "medieval Europe called it the gateway to hell, and it still erupts"},
    {"n": "Fagradalsfjall", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 63.9, "lon": -22.27, "why": "editorial", "haz": ["volcanic", "gas"],
     "note": "the Reykjanes eruptions people walked up to and watched"},
    {"n": "Blahnukur", "alt": ["Landmannalaugar", "Brennisteinsalda"], "cc": "IS",
     "kind": "peak", "lift": "", "lat": 63.99, "lon": -19.06, "why": "editorial",
     "note": "the blue and orange rhyolite peaks over Landmannalaugar"},
    {"n": "Maelifell", "cc": "IS", "kind": "volcano", "lift": "",
     "lat": 63.79, "lon": -18.98, "why": "editorial",
     "note": "the green moss cone in the black sands of Myrdalssandur"},

    # ---------------------------------------------------------------- IT ----
    {"n": "Tre Cime di Lavaredo", "alt": ["Drei Zinnen"], "cc": "IT", "kind": "rock",
     "lift": "road", "lat": 46.62, "lon": 12.3, "why": "brief",
     "note": "the three towers, a toll road to the hut and a level loop around them"},
    {"n": "Matterhorn", "alt": ["Cervino", "Monte Cervino"], "cc": "IT", "kind": "peak",
     "lift": "cable_car", "lat": 45.98, "lon": 7.66, "why": "brief",
     "haz": ["glacier", "altitude"],
     "note": "the Italian side, Cervinia's lifts and the Matterhorn Alpine Crossing"},
    {"n": "Mont Blanc", "alt": ["Monte Bianco", "Skyway Monte Bianco"], "cc": "IT",
     "kind": "peak", "lift": "cable_car", "lat": 45.83, "lon": 6.86, "why": "brief",
     "haz": ["glacier", "altitude"],
     "note": "Courmayeur's rotating cable car to Punta Helbronner at 3,466 m"},
    {"n": "Etna", "alt": ["Mount Etna", "Mongibello"], "cc": "IT", "kind": "volcano",
     "lift": "cable_car", "lat": 37.75, "lon": 14.99, "why": "brief",
     "haz": ["volcanic", "gas"],
     "note": "the biggest active volcano in Europe, cable car and jeep to the craters"},
    {"n": "Vesuvius", "alt": ["Vesuvio"], "cc": "IT", "kind": "volcano", "lift": "road",
     "lat": 40.82, "lon": 14.43, "why": "brief", "haz": ["volcanic"],
     "note": "the crater rim walk, Naples and Pompeii laid out underneath"},
    {"n": "Seceda", "cc": "IT", "kind": "ridge", "lift": "cable_car",
     "lat": 46.6, "lon": 11.72, "why": "brief",
     "note": "the tilted grass ridge and the Odle spires, cable car from Ortisei"},
    {"n": "Marmolada", "cc": "IT", "kind": "peak", "lift": "cable_car",
     "lat": 46.44, "lon": 11.85, "why": "brief", "haz": ["glacier", "rockfall"],
     "note": "queen of the Dolomites, the last glacier in the range on her north side"},
    {"n": "Sassolungo", "alt": ["Langkofel"], "cc": "IT", "kind": "peak",
     "lift": "cable_car", "lat": 46.51, "lon": 11.74, "why": "editorial",
     "note": "the standing-room-only cable car to the Toni Demetz hut"},
    {"n": "Sass Pordoi", "cc": "IT", "kind": "plateau", "lift": "cable_car",
     "lat": 46.49, "lon": 11.82, "why": "editorial",
     "note": "the terrace of the Dolomites, a cable car from the Pordoi pass"},
    {"n": "Piz Boe", "alt": ["Sella"], "cc": "IT", "kind": "peak", "lift": "cable_car",
     "lat": 46.51, "lon": 11.83, "why": "editorial",
     "note": "the high point of the Sella group, a hut on the summit"},
    {"n": "Monte Solaro", "cc": "IT", "kind": "peak", "lift": "chairlift",
     "lat": 40.55, "lon": 14.22, "why": "brief",
     "note": "the single seat chairlift over Capri, the Faraglioni from the top"},
    {"n": "Monte Baldo", "cc": "IT", "kind": "ridge", "lift": "cable_car",
     "lat": 45.73, "lon": 10.86, "why": "editorial",
     "note": "Malcesine's rotating cable car, the whole of Lake Garda below"},
    {"n": "Mottarone", "cc": "IT", "kind": "peak", "lift": "cable_car",
     "lat": 45.9, "lon": 8.4, "why": "editorial",
     "note": "the Stresa cable car, seven lakes from the summit"},
    {"n": "Corno Grande", "alt": ["Gran Sasso"], "cc": "IT", "kind": "peak",
     "lift": "cable_car", "lat": 42.47, "lon": 13.56, "why": "editorial",
     "haz": ["rockfall", "exposure"],
     "note": "the highest of the Apennines and the southernmost glacier in Europe"},
    {"n": "Catinaccio", "alt": ["Rosengarten"], "cc": "IT", "kind": "massif",
     "lift": "cable_car", "lat": 46.46, "lon": 11.6, "why": "editorial",
     "note": "the rose garden that goes pink at sunset above Bolzano"},
    {"n": "Cinque Torri", "cc": "IT", "kind": "rock", "lift": "chairlift",
     "lat": 46.51, "lon": 12.05, "why": "editorial",
     "note": "five towers with a Great War open air museum around them"},
    {"n": "Tofana di Mezzo", "alt": ["Tofane", "Freccia nel Cielo"], "cc": "IT",
     "kind": "peak", "lift": "cable_car", "lat": 46.55, "lon": 12.11, "why": "editorial",
     "note": "Cortina's arrow in the sky, 3,244 m in three stages"},
    {"n": "Kronplatz", "alt": ["Plan de Corones"], "cc": "IT", "kind": "peak",
     "lift": "cable_car", "lat": 46.74, "lon": 11.96, "why": "editorial",
     "note": "the flat summit with Messner's mountain museum built into it"},
    {"n": "Stromboli", "cc": "IT", "kind": "volcano", "lift": "",
     "lat": 38.79, "lon": 15.21, "why": "editorial", "haz": ["volcanic", "gas"],
     "note": "erupts every twenty minutes, has done for two thousand years"},
    {"n": "Gran Paradiso", "cc": "IT", "kind": "peak", "lift": "",
     "lat": 45.52, "lon": 7.27, "why": "editorial", "haz": ["glacier", "altitude"],
     "note": "the only 4,000 m summit entirely in Italy, ibex on the way up"},
    {"n": "Ortler", "alt": ["Ortles"], "cc": "IT", "kind": "peak", "lift": "",
     "lat": 46.51, "lon": 10.54, "why": "editorial", "haz": ["glacier", "altitude"],
     "note": "the roof of South Tyrol, the Stelvio road under its east side"},
    {"n": "Alpe di Siusi", "alt": ["Seiser Alm"], "cc": "IT", "kind": "plateau",
     "lift": "cable_car", "lat": 46.54, "lon": 11.61, "why": "editorial",
     "note": "the largest high alpine meadow in Europe, Sciliar standing over it"},
    {"n": "Pale di San Martino", "alt": ["Cima Rosetta"], "cc": "IT", "kind": "plateau",
     "lift": "cable_car", "lat": 46.25, "lon": 11.83, "why": "editorial",
     "note": "a lunar limestone plateau reached by cable car from San Martino"},
    {"n": "Latemar", "cc": "IT", "kind": "massif", "lift": "gondola",
     "lat": 46.38, "lon": 11.6, "why": "editorial",
     "note": "the spiky ridge behind Lake Carezza, reflected in it"},
    {"n": "Monte Amiata", "cc": "IT", "kind": "volcano", "lift": "chairlift",
     "lat": 42.89, "lon": 11.62, "why": "editorial",
     "note": "the old volcano over southern Tuscany, beech woods to the top"},

    # ---------------------------------------------------------------- LI ----
    {"n": "Grauspitz", "alt": ["Vorder Grauspitz"], "cc": "LI", "kind": "peak", "lift": "",
     "lat": 47.06, "lon": 9.6, "why": "brief",
     "note": "highest point of Liechtenstein, a long day from Malbun"},
    {"n": "Drei Schwestern", "cc": "LI", "kind": "ridge", "lift": "",
     "lat": 47.15, "lon": 9.56, "why": "editorial", "haz": ["exposure"],
     "note": "the three sisters on the skyline, the country's classic ridge walk"},
    {"n": "Sareis", "alt": ["Sareiserjoch"], "cc": "LI", "kind": "peak",
     "lift": "chairlift", "wd": "Q27439081", "lat": 47.09, "lon": 9.62,
     "why": "editorial",
     "note": "the Malbun chairlift, and the ridge path to Austria from the top"},
    {"n": "Falknis", "cc": "LI", "kind": "peak", "lift": "",
     "lat": 47.05, "lon": 9.57, "why": "editorial",
     "note": "the wall above the Rhine valley, shared with Graubunden"},

    # ---------------------------------------------------------------- LT ----
    {"n": "Aukstojas", "cc": "LT", "kind": "hill", "lift": "",
     "lat": 54.42, "lon": 25.63, "why": "brief",
     "note": "highest point of Lithuania at 294 m, a viewing platform in the forest"},
    {"n": "Parnidis Dune", "alt": ["Parnidzio kopa"], "cc": "LT", "kind": "hill", "lift": "",
     "lat": 55.28, "lon": 21.0, "why": "brief",
     "note": "the sundial dune at Nida, lagoon on one side and Baltic on the other"},
    {"n": "Gediminas Hill", "alt": ["Gedimino kalnas"], "cc": "LT", "kind": "hill",
     "lift": "funicular", "lat": 54.69, "lon": 25.29, "why": "editorial",
     "note": "the funicular to the castle tower in the middle of Vilnius"},
    {"n": "Rambynas", "cc": "LT", "kind": "hill", "lift": "",
     "lat": 55.09, "lon": 22.03, "why": "editorial",
     "note": "the sacred hill over the Nemunas, midsummer fires on it"},
    {"n": "Juozapines Hill", "cc": "LT", "kind": "hill", "lift": "",
     "lat": 54.43, "lon": 25.63, "why": "editorial",
     "note": "the hill that held the national record until Aukstojas was measured"},

    # ---------------------------------------------------------------- LU ----
    {"n": "Kneiff", "cc": "LU", "kind": "hill", "lift": "road",
     "lat": 50.18, "lon": 6.03, "why": "brief",
     "note": "highest point of Luxembourg at 560 m, a stone marker by the road"},
    {"n": "Buurgplaatz", "cc": "LU", "kind": "hill", "lift": "road",
     "lat": 50.15, "lon": 6.03, "why": "editorial",
     "note": "the Oesling's second high point, and the one with the view"},
    {"n": "Widdebierg", "cc": "LU", "kind": "hill", "lift": "",
     "lat": 49.66, "lon": 6.28, "why": "editorial",
     "note": "the sandstone ridge over the Syre valley, easy walking on top"},
    {"n": "Bock", "alt": ["Bockfiels", "Bock Casemates"], "cc": "LU", "kind": "cliff",
     "lift": "", "lat": 49.61, "lon": 6.13, "why": "editorial",
     "note": "the rock promontory Luxembourg was founded on, tunnelled through"},

    # ---------------------------------------------------------------- LV ----
    {"n": "Gaizinkalns", "cc": "LV", "kind": "hill", "lift": "",
     "lat": 56.85, "lon": 25.96, "why": "brief",
     "note": "highest point of Latvia at 312 m, a ski slope on the side of it"},
    {"n": "Sigulda", "alt": ["Gauja valley", "Paradise Hill", "Paradizes kalns"],
     "cc": "LV", "kind": "cliff", "lift": "cable_car", "lat": 57.16, "lon": 24.85,
     "why": "editorial",
     "note": "the cable car across the Gauja gorge, sandstone cliffs under it"},
    {"n": "Lielais Liepukalns", "cc": "LV", "kind": "hill", "lift": "",
     "lat": 56.4, "lon": 27.36, "why": "editorial",
     "note": "the Latgale high point, a tower over the blue lakes"},
    {"n": "Zilaiskalns", "cc": "LV", "kind": "hill", "lift": "",
     "lat": 57.53, "lon": 25.15, "why": "editorial",
     "note": "the blue hill, an old pagan sanctuary with a lookout on top"},

    # ---------------------------------------------------------------- MC ----
    {"n": "Chemin des Revoires", "alt": ["Mont Agel", "Les Revoires"], "cc": "MC",
     "kind": "hill", "lift": "road", "lat": 43.74, "lon": 7.42, "why": "brief",
     "note": "highest point of Monaco at 164 m, on the slope of Mont Agel"},
    {"n": "Rock of Monaco", "alt": ["Le Rocher", "Monaco-Ville"], "cc": "MC",
     "kind": "cliff", "lift": "", "lat": 43.73, "lon": 7.42, "why": "editorial",
     "note": "the 62 m headland the palace and the old town stand on"},
    {"n": "Tete de Chien", "cc": "MC", "kind": "cliff", "lift": "road",
     "lat": 43.73, "lon": 7.4, "why": "editorial",
     "note": "the 550 m cliff directly over the principality, the classic view down"},

    # ---------------------------------------------------------------- MD ----
    {"n": "Balanesti Hill", "alt": ["Dealul Balanesti"], "cc": "MD", "kind": "hill",
     "lift": "", "lat": 47.31, "lon": 28.19, "why": "brief",
     "note": "highest point of Moldova at 430 m, vineyards on the slopes"},
    {"n": "Orheiul Vechi", "alt": ["Old Orhei", "Butuceni"], "cc": "MD", "kind": "cliff",
     "lift": "", "lat": 47.31, "lon": 28.98, "why": "brief",
     "note": "the limestone canyon of the Raut with a cave monastery in the wall"},
    {"n": "Tipova", "cc": "MD", "kind": "cliff", "lift": "",
     "lat": 47.65, "lon": 28.96, "why": "editorial",
     "note": "the Dniester gorge, waterfalls and the largest rock monastery here"},

    # ---------------------------------------------------------------- ME ----
    {"n": "Bobotov Kuk", "alt": ["Durmitor"], "cc": "ME", "kind": "peak", "lift": "",
     "lat": 43.12, "lon": 19.03, "why": "brief", "haz": ["exposure"],
     "note": "the Durmitor summit above the Black Lake and the Tara canyon"},
    {"n": "Lovcen", "alt": ["Jezerski vrh", "Njegos mausoleum"], "cc": "ME", "kind": "peak",
     "lift": "road", "lat": 42.4, "lon": 18.84, "why": "brief",
     "note": "461 steps to the mausoleum, half of Montenegro from the terrace"},
    {"n": "Zla Kolata", "cc": "ME", "kind": "peak", "lift": "",
     "lat": 42.53, "lon": 19.86, "why": "editorial",
     "note": "highest point of Montenegro, on the Albanian border in Prokletije"},
    {"n": "Sveti Ivan", "alt": ["San Giovanni", "Kotor fortress"], "cc": "ME",
     "kind": "hill", "lift": "cable_car", "lat": 42.43, "lon": 18.78, "why": "editorial",
     "note": "the ladder of Kotor up to the fortress, and now a cable car alongside"},
    {"n": "Komovi", "cc": "ME", "kind": "massif", "lift": "",
     "lat": 42.7, "lon": 19.66, "why": "editorial",
     "note": "two rock horns over the katun pastures, the shepherds' summer country"},
    {"n": "Rumija", "cc": "ME", "kind": "peak", "lift": "",
     "lat": 42.09, "lon": 19.16, "why": "editorial",
     "note": "Lake Skadar on one side, the Adriatic on the other, from one summit"},

    # ---------------------------------------------------------------- MK ----
    {"n": "Mount Vodno", "alt": ["Vodno", "Millennium Cross"], "cc": "MK", "kind": "peak",
     "lift": "cable_car", "lat": 41.96, "lon": 21.4, "why": "brief",
     "note": "the cable car to the 66 m cross over Skopje"},
    {"n": "Golem Korab", "alt": ["Korab"], "cc": "MK", "kind": "peak", "lift": "",
     "lat": 41.79, "lon": 20.55, "why": "brief",
     "note": "highest point of North Macedonia, and of Albania as well"},
    {"n": "Pelister", "alt": ["Baba"], "cc": "MK", "kind": "peak", "lift": "chairlift",
     "lat": 41.0, "lon": 21.21, "why": "editorial",
     "note": "the molika pine national park above Bitola, two glacial eyes on it"},
    {"n": "Titov Vrv", "alt": ["Sar Planina"], "cc": "MK", "kind": "peak", "lift": "",
     "lat": 42.0, "lon": 20.83, "why": "editorial",
     "note": "the Sar mountains high point, high pasture the whole way"},
    {"n": "Galicica", "alt": ["Magaro"], "cc": "MK", "kind": "ridge", "lift": "road",
     "lat": 40.98, "lon": 20.83, "why": "editorial",
     "note": "the ridge road between Lake Ohrid and Lake Prespa, both at once"},
    {"n": "Solunska Glava", "cc": "MK", "kind": "peak", "lift": "",
     "lat": 41.53, "lon": 21.32, "why": "editorial",
     "note": "they say you can see Thessaloniki from it, hence the name"},

    # ---------------------------------------------------------------- MT ----
    {"n": "Dingli Cliffs", "alt": ["Ta' Dmejrek"], "cc": "MT", "kind": "cliff", "lift": "",
     "lat": 35.85, "lon": 14.38, "why": "brief",
     "note": "highest point of Malta at 253 m, and it is a sea cliff"},
    {"n": "Ta' Cenc Cliffs", "cc": "MT", "kind": "cliff", "lift": "",
     "lat": 36.02, "lon": 14.25, "why": "editorial",
     "note": "Gozo's south coast wall, 130 m straight into the sea"},
    {"n": "Ta' Dbiegi Hill", "cc": "MT", "kind": "hill", "lift": "road",
     "lat": 36.06, "lon": 14.2, "why": "editorial",
     "note": "the highest point of Gozo, the whole island from a small summit"},
    {"n": "Wardija Ridge", "alt": ["Wardija"], "cc": "MT", "kind": "ridge", "lift": "road",
     "lat": 35.94, "lon": 14.38, "why": "editorial",
     "note": "the ridge over the northwest bays, terraces and old watchtowers"},

    # ---------------------------------------------------------------- NL ----
    {"n": "Vaalserberg", "alt": ["Drielandenpunt"], "cc": "NL", "kind": "hill",
     "lift": "road", "lat": 50.75, "lon": 6.02, "why": "brief",
     "note": "highest point of the European Netherlands at 322 m, three countries at once"},
    {"n": "Sint-Pietersberg", "cc": "NL", "kind": "hill", "lift": "",
     "lat": 50.82, "lon": 5.68, "why": "editorial",
     "note": "the marl plateau over Maastricht, caves underneath and a fort on top"},
    {"n": "Posbank", "alt": ["Veluwezoom"], "cc": "NL", "kind": "hill", "lift": "",
     "lat": 52.03, "lon": 6.0, "why": "brief",
     "note": "the heather ridge in Veluwezoom, purple in August, the Dutch view"},
    {"n": "Amerongse Berg", "cc": "NL", "kind": "hill", "lift": "",
     "lat": 52.0, "lon": 5.45, "why": "editorial",
     "note": "the high point of the Utrecht ridge, an ice age moraine"},
    {"n": "Schoorlse Duinen", "alt": ["Klimduin", "Schoorl dunes"], "cc": "NL",
     "kind": "hill", "lift": "", "lat": 52.7, "lon": 4.65, "why": "editorial",
     "note": "the highest and widest dunes in the country, a sand wall to run down"},
    {"n": "Lemelerberg", "cc": "NL", "kind": "hill", "lift": "",
     "lat": 52.48, "lon": 6.37, "why": "editorial",
     "note": "an Overijssel sand ridge with heath, juniper and a lookout"},
    {"n": "Wilhelminaberg", "alt": ["Adventure Valley", "Landgraaf"], "cc": "NL",
     "kind": "hill", "lift": "chairlift", "lat": 50.9, "lon": 6.02, "why": "editorial",
     "note": "a spoil heap turned into the only chairlift in the Netherlands"},

    # ---------------------------------------------------------------- NO ----
    {"n": "Preikestolen", "alt": ["Pulpit Rock"], "cc": "NO", "kind": "cliff", "lift": "",
     "lat": 58.99, "lon": 6.19, "why": "brief", "haz": ["exposure", "weather"],
     "note": "a 604 m flat rock over the Lysefjord, no railing, four hours return"},
    {"n": "Trolltunga", "cc": "NO", "kind": "cliff", "lift": "",
     "lat": 60.12, "lon": 6.74, "why": "brief", "haz": ["exposure", "weather", "long_day"],
     "note": "the troll's tongue over Ringedalsvatnet, a serious ten hour day"},
    {"n": "Kjeragbolten", "alt": ["Kjerag"], "cc": "NO", "kind": "cliff", "lift": "",
     "lat": 59.03, "lon": 6.59, "why": "brief", "haz": ["exposure", "weather"],
     "note": "the boulder wedged in a crevice a kilometre above the fjord"},
    {"n": "Galdhopiggen", "cc": "NO", "kind": "peak", "lift": "",
     "lat": 61.64, "lon": 8.31, "why": "brief", "haz": ["glacier", "weather"],
     "note": "highest in northern Europe, a guided glacier crossing or the long way"},
    {"n": "Gaustatoppen", "cc": "NO", "kind": "peak", "lift": "funicular",
     "lat": 59.85, "lon": 8.65, "why": "brief",
     "note": "a funicular inside the mountain, and a sixth of Norway from the top"},
    {"n": "Reinebringen", "cc": "NO", "kind": "ridge", "lift": "",
     "lat": 67.93, "lon": 13.09, "why": "brief", "haz": ["exposure"],
     "note": "1,566 sherpa steps over Reine, the Lofoten photograph"},
    {"n": "Segla", "cc": "NO", "kind": "ridge", "lift": "",
     "lat": 69.51, "lon": 17.51, "why": "brief", "haz": ["exposure"],
     "note": "the sail, a fin of rock straight out of the sea on Senja"},
    {"n": "Floyen", "cc": "NO", "kind": "hill", "lift": "funicular",
     "lat": 60.39, "lon": 5.34, "why": "brief",
     "note": "the Floibanen funicular from the middle of Bergen, eight minutes"},
    {"n": "Ulriken", "cc": "NO", "kind": "peak", "lift": "cable_car",
     "lat": 60.37, "lon": 5.4, "why": "editorial",
     "note": "the highest of Bergen's seven mountains, cable car and a ridge walk"},
    {"n": "Besseggen", "cc": "NO", "kind": "ridge", "lift": "",
     "lat": 61.5, "lon": 8.75, "why": "brief", "haz": ["exposure"],
     "note": "the ridge between a green lake and a blue one, Norway's busiest walk"},
    {"n": "Stetind", "cc": "NO", "kind": "peak", "lift": "",
     "lat": 68.16, "lon": 16.58, "why": "editorial", "haz": ["exposure"],
     "note": "voted the national mountain, an anvil of granite out of the fjord"},
    {"n": "Romsdalshorn", "alt": ["Romsdalen"], "cc": "NO", "kind": "peak", "lift": "",
     "lat": 62.48, "lon": 7.79, "why": "editorial",
     "note": "the horn over Andalsnes, with the Trollveggen wall opposite"},
    {"n": "Trollveggen", "alt": ["Troll Wall"], "cc": "NO", "kind": "cliff", "lift": "",
     "lat": 62.5, "lon": 7.75, "why": "editorial", "haz": ["rockfall"],
     "note": "the tallest vertical rock face in Europe, 1,100 m of overhang"},
    {"n": "Hoven", "alt": ["Loen Skylift"], "cc": "NO", "kind": "peak", "lift": "cable_car",
     "lat": 61.87, "lon": 6.85, "why": "editorial",
     "note": "one of the steepest cable cars in the world, from the fjord to 1,011 m"},
    {"n": "Dalsnibba", "cc": "NO", "kind": "peak", "lift": "road",
     "lat": 62.05, "lon": 7.26, "why": "editorial",
     "note": "the toll road to a 1,500 m platform straight over the Geirangerfjord"},
    {"n": "Snohetta", "cc": "NO", "kind": "peak", "lift": "",
     "lat": 62.32, "lon": 9.27, "why": "editorial",
     "note": "the Dovrefjell high point, wild reindeer and the Viewpoint pavilion"},
    {"n": "Nordkapp", "alt": ["North Cape"], "cc": "NO", "kind": "cliff", "lift": "road",
     "lat": 71.17, "lon": 25.78, "why": "editorial",
     "note": "the 307 m slate cliff people drive to the end of Europe for"},
    {"n": "Slogen", "cc": "NO", "kind": "peak", "lift": "",
     "lat": 62.22, "lon": 6.86, "why": "editorial",
     "note": "the Sunnmore Alps' finest shape, straight out of the Hjorundfjord"},
    {"n": "Store Skagastolstind", "alt": ["Storen"], "cc": "NO", "kind": "peak", "lift": "",
     "lat": 61.46, "lon": 7.81, "why": "editorial", "haz": ["exposure", "glacier"],
     "note": "the hardest of the great Norwegian summits, in Hurrungane"},

    # ---------------------------------------------------------------- PL ----
    {"n": "Rysy", "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.18, "lon": 20.09, "why": "brief", "haz": ["exposure"],
     "note": "highest point of Poland, chains on the last stretch from Morskie Oko"},
    {"n": "Kasprowy Wierch", "cc": "PL", "kind": "peak", "lift": "cable_car",
     "lat": 49.23, "lon": 19.98, "why": "brief",
     "note": "the 1936 cable car from Kuznice, the Tatra ridge in both directions"},
    {"n": "Giewont", "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.25, "lon": 19.93, "why": "brief", "haz": ["lightning", "exposure"],
     "note": "the sleeping knight over Zakopane with a 15 m iron cross on top"},
    {"n": "Sniezka", "cc": "PL", "kind": "peak", "lift": "chairlift",
     "lat": 50.74, "lon": 15.74, "why": "editorial",
     "note": "the Karkonosze border summit and its flying saucer observatory"},
    {"n": "Babia Gora", "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.57, "lon": 19.53, "why": "editorial", "haz": ["weather"],
     "note": "the queen of the Beskids, a UNESCO reserve, weather of its own"},
    {"n": "Tarnica", "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.08, "lon": 22.73, "why": "editorial",
     "note": "the Bieszczady high point, empty grass ridges called poloniny"},
    {"n": "Trzy Korony", "alt": ["Pieniny"], "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.42, "lon": 20.4, "why": "editorial",
     "note": "the three crowns straight above the Dunajec gorge and its rafts"},
    {"n": "Szczeliniec Wielki", "cc": "PL", "kind": "rock", "lift": "",
     "lat": 50.48, "lon": 16.34, "why": "editorial",
     "note": "the Table Mountains, a labyrinth of sandstone blocks on a plateau"},
    {"n": "Gubalowka", "cc": "PL", "kind": "hill", "lift": "funicular",
     "lat": 49.29, "lon": 19.94, "why": "editorial",
     "note": "Zakopane's funicular ridge, the whole Tatra skyline across the valley"},
    {"n": "Sleza", "cc": "PL", "kind": "peak", "lift": "",
     "lat": 50.86, "lon": 16.71, "why": "editorial",
     "note": "the holy mountain of Silesia, pagan stone figures on the path"},
    {"n": "Morskie Oko", "alt": ["Rysy trail"], "cc": "PL", "kind": "peak", "lift": "",
     "lat": 49.2, "lon": 20.07, "why": "editorial",
     "note": "the walk in to the eye of the sea under the highest Polish wall"},

    # ---------------------------------------------------------------- PT ----
    {"n": "Mount Pico", "alt": ["Pico", "Ponta do Pico"], "cc": "PT", "kind": "volcano",
     "lift": "", "lat": 38.47, "lon": -28.4, "why": "brief", "haz": ["altitude", "weather"],
     "note": "highest point of Portugal, a 2,351 m volcano straight out of the Atlantic"},
    {"n": "Pico Ruivo", "cc": "PT", "kind": "peak", "lift": "",
     "lat": 32.76, "lon": -16.94, "why": "brief", "haz": ["exposure"],
     "note": "the roof of Madeira, the ridge walk from Arieiro through the cloud"},
    {"n": "Pico do Arieiro", "cc": "PT", "kind": "peak", "lift": "road",
     "lat": 32.73, "lon": -16.93, "why": "brief",
     "note": "you drive to 1,818 m and stand above the sea of cloud"},
    {"n": "Torre", "alt": ["Serra da Estrela"], "cc": "PT", "kind": "peak", "lift": "road",
     "lat": 40.32, "lon": -7.61, "why": "brief",
     "note": "highest point of mainland Portugal, and the only place it reliably snows"},
    {"n": "Cabo Girao", "cc": "PT", "kind": "cliff", "lift": "cable_car",
     "lat": 32.66, "lon": -17.0, "why": "editorial", "haz": ["exposure"],
     "note": "a glass skywalk 580 m above the sea, one of Europe's highest cliffs"},
    {"n": "Sete Cidades", "cc": "PT", "kind": "volcano", "lift": "road",
     "lat": 37.86, "lon": -25.79, "why": "editorial",
     "note": "the Azorean crater with a green lake and a blue one in it"},
    {"n": "Monte", "alt": ["Monte Madeira", "Funchal cable car"], "cc": "PT",
     "kind": "hill", "lift": "cable_car", "lat": 32.67, "lon": -16.9, "why": "editorial",
     "note": "the Funchal cable car, the tropical garden and the wicker toboggans down"},
    {"n": "Foia", "alt": ["Monchique"], "cc": "PT", "kind": "peak", "lift": "road",
     "lat": 37.31, "lon": -8.6, "why": "editorial",
     "note": "the Algarve's high point, both coasts of the province from it"},
    {"n": "Cruz Alta", "alt": ["Serra de Sintra", "Pena"], "cc": "PT", "kind": "hill",
     "lift": "", "lat": 38.78, "lon": -9.39, "why": "editorial",
     "note": "the high point of the Sintra hills, right above the Pena palace"},
    {"n": "Marao", "cc": "PT", "kind": "peak", "lift": "road",
     "lat": 41.24, "lon": -7.88, "why": "editorial",
     "note": "the granite barrier between the Douro and the coast"},

    # ---------------------------------------------------------------- RO ----
    {"n": "Moldoveanu", "cc": "RO", "kind": "peak", "lift": "",
     "lat": 45.6, "lon": 24.73, "why": "brief",
     "note": "highest point of Romania, on the Fagaras ridge"},
    {"n": "Omu", "alt": ["Bucegi", "Babele", "Sphinx"], "cc": "RO", "kind": "plateau",
     "lift": "cable_car", "lat": 45.44, "lon": 25.46, "why": "brief",
     "note": "cable car from Busteni to the Bucegi plateau, the Sphinx rock on it"},
    {"n": "Tampa", "cc": "RO", "kind": "hill", "lift": "cable_car",
     "lat": 45.63, "lon": 25.59, "why": "brief",
     "note": "the cable car straight up from Brasov's old town to the sign on top"},
    {"n": "Toaca", "alt": ["Ceahlau"], "cc": "RO", "kind": "peak", "lift": "",
     "lat": 46.95, "lon": 25.95, "why": "editorial",
     "note": "the holy mountain of Moldavia, the pyramid shadow at sunrise in August"},
    {"n": "Negoiu", "cc": "RO", "kind": "peak", "lift": "",
     "lat": 45.59, "lon": 24.54, "why": "editorial", "haz": ["exposure"],
     "note": "the second highest, and the harder one, above the Transfagarasan"},
    {"n": "Peleaga", "alt": ["Retezat"], "cc": "RO", "kind": "peak", "lift": "",
     "lat": 45.36, "lon": 22.88, "why": "editorial",
     "note": "the Retezat high point, eighty glacial lakes under it"},
    {"n": "Piatra Craiului", "alt": ["La Om"], "cc": "RO", "kind": "ridge", "lift": "",
     "lat": 45.53, "lon": 25.22, "why": "editorial", "haz": ["exposure"],
     "note": "a 25 km limestone knife edge, the finest ridge in the Carpathians"},
    {"n": "Postavaru", "alt": ["Poiana Brasov"], "cc": "RO", "kind": "peak",
     "lift": "gondola", "lat": 45.58, "lon": 25.55, "why": "editorial",
     "note": "Poiana Brasov's gondola, Bucegi and Piatra Craiului from the top"},
    {"n": "Pietrele Doamnei", "alt": ["Rarau"], "cc": "RO", "kind": "rock", "lift": "",
     "lat": 47.45, "lon": 25.55, "why": "editorial",
     "note": "the lady's rocks standing out of the Bukovina forest"},
    {"n": "Balea Lac", "alt": ["Transfagarasan", "Balea"], "cc": "RO", "kind": "peak",
     "lift": "cable_car", "lat": 45.6, "lon": 24.62, "why": "editorial",
     "note": "the cable car that runs when the Transfagarasan is shut by snow"},

    # ---------------------------------------------------------------- RS ----
    {"n": "Midzor", "cc": "RS", "kind": "peak", "lift": "",
     "lat": 43.4, "lon": 22.68, "why": "brief",
     "note": "highest point of Serbia proper, on the Bulgarian border"},
    {"n": "Kopaonik", "alt": ["Pancicev vrh"], "cc": "RS", "kind": "peak", "lift": "gondola",
     "lat": 43.27, "lon": 20.8, "why": "brief",
     "note": "Serbia's ski mountain, the mausoleum of Pancic on the summit"},
    {"n": "Tornik", "alt": ["Zlatibor", "Gold Gondola"], "cc": "RS", "kind": "peak",
     "lift": "gondola", "lat": 43.68, "lon": 19.63, "why": "brief",
     "note": "the Gold Gondola from Zlatibor, one of the longest rides in the world"},
    {"n": "Rtanj", "cc": "RS", "kind": "peak", "lift": "",
     "lat": 43.77, "lon": 21.9, "why": "editorial",
     "note": "the near perfect pyramid with a chapel on it and a folklore of its own"},
    {"n": "Banjska Stena", "alt": ["Tara"], "cc": "RS", "kind": "cliff", "lift": "",
     "lat": 43.93, "lon": 19.4, "why": "editorial", "haz": ["exposure"],
     "note": "the viewpoint over the Drina canyon and the green Perucac lake"},
    {"n": "Avala", "cc": "RS", "kind": "hill", "lift": "road",
     "lat": 44.69, "lon": 20.51, "why": "editorial",
     "note": "Belgrade's hill, the tower with a lift and the monument to the unknown hero"},
    {"n": "Stara Planina", "alt": ["Babin Zub"], "cc": "RS", "kind": "peak",
     "lift": "chairlift", "lat": 43.38, "lon": 22.63, "why": "editorial",
     "note": "the grandmother's tooth rock, and the Serbian side of the Balkan range"},
    {"n": "Fruska Gora", "alt": ["Crveni Cot"], "cc": "RS", "kind": "hill", "lift": "road",
     "lat": 45.15, "lon": 19.7, "why": "editorial",
     "note": "an island of forest and monasteries over the Pannonian plain"},

    # ---------------------------------------------------------------- SE ----
    {"n": "Kebnekaise", "cc": "SE", "kind": "peak", "lift": "",
     "lat": 67.9, "lon": 18.51, "why": "brief", "haz": ["glacier", "weather"],
     "note": "highest in Sweden, and the south top is losing height every summer"},
    {"n": "Areskutan", "cc": "SE", "kind": "peak", "lift": "cable_car",
     "lat": 63.43, "lon": 13.09, "why": "brief",
     "note": "the cable car from Are village to a chapel on a 1,420 m summit"},
    {"n": "Nuolja", "alt": ["Abisko", "Aurora Sky Station"], "cc": "SE", "kind": "peak",
     "lift": "chairlift", "lat": 68.36, "lon": 18.7, "why": "editorial",
     "note": "the chairlift to the Aurora Sky Station over Tornetrask"},
    {"n": "Lapporten", "cc": "SE", "kind": "ridge", "lift": "",
     "lat": 68.28, "lon": 18.72, "why": "editorial",
     "note": "the U shaped glacial gate at Abisko, the symbol of Swedish Lapland"},
    {"n": "Helagsfjallet", "cc": "SE", "kind": "peak", "lift": "",
     "lat": 62.92, "lon": 12.45, "why": "editorial", "haz": ["glacier"],
     "note": "the southernmost glacier in Sweden sits on its north face"},
    {"n": "Sylarna", "cc": "SE", "kind": "massif", "lift": "",
     "lat": 63.03, "lon": 12.23, "why": "editorial",
     "note": "the three peaks on the Norwegian border, a classic hut to hut walk"},
    {"n": "Skuleberget", "cc": "SE", "kind": "peak", "lift": "cable_car",
     "lat": 63.1, "lon": 18.5, "why": "editorial",
     "note": "the High Coast cliff with a via ferrata and a cable car up it"},
    {"n": "Kullaberg", "cc": "SE", "kind": "cliff", "lift": "",
     "lat": 56.3, "lon": 12.45, "why": "editorial",
     "note": "the rock nose into the Kattegat, caves, a lighthouse and porpoises"},

    # ---------------------------------------------------------------- SI ----
    {"n": "Triglav", "cc": "SI", "kind": "peak", "lift": "",
     "lat": 46.38, "lon": 13.84, "why": "brief", "haz": ["exposure", "via_ferrata"],
     "note": "on the flag, in the anthem, and a cabled ridge on the last part"},
    {"n": "Vogel", "cc": "SI", "kind": "peak", "lift": "cable_car",
     "lat": 46.26, "lon": 13.84, "why": "brief",
     "note": "the cable car from Lake Bohinj, Triglav straight across the valley"},
    {"n": "Velika Planina", "cc": "SI", "kind": "plateau", "lift": "cable_car",
     "lat": 46.3, "lon": 14.63, "why": "brief",
     "note": "a herdsmen's village of round shingle huts on a high pasture"},
    {"n": "Mangart", "cc": "SI", "kind": "peak", "lift": "road",
     "lat": 46.44, "lon": 13.65, "why": "editorial",
     "note": "the highest road in Slovenia stops just under the summit"},
    {"n": "Krvavec", "cc": "SI", "kind": "peak", "lift": "gondola",
     "lat": 46.3, "lon": 14.53, "why": "editorial",
     "note": "the gondola nearest Ljubljana airport, above the valley fog all winter"},
    {"n": "Jalovec", "cc": "SI", "kind": "peak", "lift": "",
     "lat": 46.42, "lon": 13.71, "why": "editorial", "haz": ["exposure"],
     "note": "the shark fin some Slovenes think is the finer mountain"},
    {"n": "Sneznik", "cc": "SI", "kind": "peak", "lift": "",
     "lat": 45.58, "lon": 14.45, "why": "editorial",
     "note": "the big lonely dome above the karst forest, bears underneath"},
    {"n": "Nanos", "cc": "SI", "kind": "plateau", "lift": "",
     "lat": 45.79, "lon": 14.05, "why": "editorial",
     "note": "the wall the bora wind comes off, straight over the Vipava valley"},
    {"n": "Ljubljana Castle Hill", "alt": ["Grajski gric"], "cc": "SI", "kind": "hill",
     "lift": "funicular", "lat": 46.05, "lon": 14.51, "why": "editorial",
     "note": "a minute of funicular from the market to the castle tower"},

    # ---------------------------------------------------------------- SK ----
    {"n": "Gerlachovsky stit", "cc": "SK", "kind": "peak", "lift": "",
     "lat": 49.16, "lon": 20.13, "why": "brief", "haz": ["exposure"],
     "note": "highest in the Carpathians, and only with a mountain guide"},
    {"n": "Lomnicky stit", "cc": "SK", "kind": "peak", "lift": "cable_car",
     "lat": 49.2, "lon": 20.21, "why": "brief",
     "note": "a cable car to 2,634 m, an observatory and a very small terrace"},
    {"n": "Krivan", "cc": "SK", "kind": "peak", "lift": "",
     "lat": 49.16, "lon": 20.0, "why": "brief",
     "note": "the national symbol, on the coins, the walk every Slovak does once"},
    {"n": "Chopok", "alt": ["Jasna"], "cc": "SK", "kind": "peak", "lift": "cable_car",
     "lat": 48.94, "lon": 19.59, "why": "editorial",
     "note": "cable cars up both sides of the Low Tatras ridge"},
    {"n": "Rysy", "cc": "SK", "kind": "peak", "lift": "",
     "lat": 49.18, "lon": 20.09, "why": "editorial", "haz": ["exposure"],
     "note": "the Slovak side, chains and a hut, and Poland over the top"},
    {"n": "Dumbier", "cc": "SK", "kind": "peak", "lift": "cable_car",
     "lat": 48.93, "lon": 19.64, "why": "editorial",
     "note": "the Low Tatras high point, a ridge walk from the Chopok lift"},
    {"n": "Slavkovsky stit", "cc": "SK", "kind": "peak", "lift": "",
     "lat": 49.15, "lon": 20.2, "why": "editorial",
     "note": "the big one you can climb without a guide, straight up from Stary Smokovec"},
    {"n": "Sulovske skaly", "cc": "SK", "kind": "rock", "lift": "",
     "lat": 49.16, "lon": 18.6, "why": "editorial",
     "note": "the conglomerate rock town with a gate arch and a castle ruin"},

    # ---------------------------------------------------------------- SM ----
    {"n": "Monte Titano", "cc": "SM", "kind": "peak", "lift": "cable_car",
     "lat": 43.94, "lon": 12.45, "why": "brief",
     "note": "the three towers on a limestone ridge, UNESCO, a cable car up to it"},
    {"n": "Monte Cerreto", "cc": "SM", "kind": "hill", "lift": "road",
     "lat": 43.9, "lon": 12.47, "why": "editorial",
     "note": "the republic's second summit, the Adriatic from the far side"},

    # ---------------------------------------------------------------- XK ----
    {"n": "Gjeravica", "cc": "XK", "kind": "peak", "lift": "",
     "lat": 42.53, "lon": 20.14, "why": "brief",
     "note": "highest point of Kosovo, glacial lakes below the summit"},
    {"n": "Hajla", "cc": "XK", "kind": "peak", "lift": "",
     "lat": 42.79, "lon": 20.13, "why": "editorial",
     "note": "the wall above the Rugova valley, shared with Montenegro"},
    {"n": "Rugova Canyon", "alt": ["Rugova", "Via Ferrata Ari"], "cc": "XK",
     "kind": "cliff", "lift": "cable_car", "lat": 42.68, "lon": 20.2, "why": "editorial",
     "note": "the gorge behind Peja, a cable car and the country's via ferrata"},
    {"n": "Piribeg", "alt": ["Brezovica", "Sharr"], "cc": "XK", "kind": "peak",
     "lift": "chairlift", "lat": 42.19, "lon": 20.98, "why": "editorial",
     "note": "the Brezovica lifts on the Sharr ridge, the Prizren side of it"},
    {"n": "Marijash", "alt": ["Maja e Marijashit"], "cc": "XK", "kind": "peak", "lift": "",
     "lat": 42.6, "lon": 20.13, "why": "editorial",
     "note": "the Accursed Mountains' Kosovo side, the peaks of the Balkans trail"},
]


def by_country():
    """The seed grouped by ISO2, in file order inside each country."""
    out = {}
    for entry in SEED:
        out.setdefault(entry["cc"], []).append(entry)
    return out


def countries():
    """Every ISO2 the seed names, sorted."""
    return sorted({entry["cc"] for entry in SEED})
