-- Carta — unified European trip dataset
-- Generated by pipeline/export_sql.py. Safe to re-run: everything is IF NOT EXISTS
-- or CREATE OR REPLACE, and the seed migration is idempotent (ON CONFLICT DO UPDATE).

create extension if not exists pg_trgm;

-- ---------------------------------------------------------------- reference

create table if not exists carta_regions (
  key         text primary key,
  name        text not null unique
);

create table if not exists carta_trip_types (
  id          smallint primary key,
  name        text not null unique,
  slug        text not null unique
);

create table if not exists carta_countries (
  code        char(2) primary key,
  name        text not null unique,
  region_key  text not null references carta_regions(key)
);

-- -------------------------------------------------------------------- trips

create table if not exists carta_trips (
  id                      text primary key,
  source_id               text,
  title                   text not null,
  summary                 text,
  summary_generated       boolean not null default false,
  hook                    text,

  country_code            char(2) not null references carta_countries(code),
  region_key              text not null references carta_regions(key),
  sub_region              text,
  is_multi_country        boolean not null default false,

  trip_type_id            smallint not null references carta_trip_types(id),
  duration_days           smallint not null default 7 check (duration_days = 7),

  best_period_months      smallint[] not null default '{}',
  best_period_window      text,
  best_period_note        text,
  best_period_avoid       text,

  budget_tier             text not null check (budget_tier in ('€','€€','€€€')),
  budget_tier_min         smallint check (budget_tier_min between 1 and 3),
  budget_tier_max         smallint check (budget_tier_max between 1 and 3),
  budget_tier_raw         text,
  budget_total_low_eur    integer check (budget_total_low_eur > 0),
  budget_total_high_eur   integer check (budget_total_high_eur > 0),
  budget_total_note       text,
  check (budget_total_low_eur is null or budget_total_high_eur is null
         or budget_total_low_eur <= budget_total_high_eur),

  difficulty              smallint check (difficulty between 1 and 5),
  difficulty_label        text,
  difficulty_note         text,
  fitness_level           text check (fitness_level in
                            ('Easy','Moderate','Active','Demanding','Expert')),
  crowd_level             text check (crowd_level in ('Low','Moderate','High')),
  family_friendly         boolean,
  car_required            boolean,

  basecamps               text[] not null default '{}',
  gateway_airport         text,
  gateway_airport_code    char(3),
  languages               text[] not null default '{}',
  currency                text,
  emergency_number        text,

  lat                     double precision check (lat between -90 and 90),
  lon                     double precision check (lon between -180 and 180),
  coord_precision         text check (coord_precision in ('source','city','gateway','country')),
  coord_place             text,

  tags                    text[] not null default '{}',
  type_specific           jsonb not null default '{}'::jsonb,
  snapshot                jsonb not null default '{}'::jsonb,
  logistics               jsonb not null default '{}'::jsonb,
  sources                 jsonb not null default '{}'::jsonb,
  packing_notes           text[] not null default '{}',
  what_could_go_wrong     text[] not null default '{}',
  verify_flags            text[] not null default '{}',
  verify_flag_count       integer not null default 0,
  volatile_pricing        boolean not null default false,

  word_count              integer,
  data_vintage            smallint not null default 2026,
  source_batch            text,
  source_file             text,
  source_format           text,
  synthesized             boolean not null default false,
  ingested_at             date,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- trips that legitimately span two countries
create table if not exists carta_trip_countries (
  trip_id       text not null references carta_trips(id) on delete cascade,
  country_code  char(2) not null references carta_countries(code),
  is_primary    boolean not null default false,
  primary key (trip_id, country_code)
);

create table if not exists carta_trip_days (
  trip_id     text not null references carta_trips(id) on delete cascade,
  day_number  smallint not null check (day_number between 1 and 7),
  title       text,
  morning     text,
  afternoon   text,
  evening     text,
  day_stats   text,
  sleep       text,
  primary key (trip_id, day_number)
);

create table if not exists carta_trip_budget_lines (
  trip_id   text not null references carta_trips(id) on delete cascade,
  category  text not null check (category in
              ('accommodation','food','transport','activities')),
  low_eur   integer check (low_eur >= 0),
  high_eur  integer check (high_eur >= 0),
  note      text,
  primary key (trip_id, category),
  check (low_eur is null or high_eur is null or low_eur <= high_eur)
);

create table if not exists carta_trip_accommodations (
  trip_id     text not null references carta_trips(id) on delete cascade,
  rank        smallint not null,
  name        text not null,
  style       text,
  location    text,
  description text,
  booking     text,
  price_note  text,
  primary key (trip_id, rank)
);

create table if not exists carta_trip_pro_tips (
  trip_id   text not null references carta_trips(id) on delete cascade,
  position  smallint not null,
  tip       text not null,
  primary key (trip_id, position)
);

-- ------------------------------------------------------------------ indexes

create index if not exists carta_trips_type_idx        on carta_trips (trip_type_id);
create index if not exists carta_trips_country_idx     on carta_trips (country_code);
create index if not exists carta_trips_region_idx      on carta_trips (region_key);
create index if not exists carta_trips_tier_idx        on carta_trips (budget_tier);
create index if not exists carta_trips_difficulty_idx  on carta_trips (difficulty);
create index if not exists carta_trips_budget_idx      on carta_trips (budget_total_low_eur);
create index if not exists carta_trips_tags_idx        on carta_trips using gin (tags);
create index if not exists carta_trips_months_idx      on carta_trips using gin (best_period_months);
create index if not exists carta_trips_typespec_idx    on carta_trips using gin (type_specific);
create index if not exists carta_trips_title_trgm_idx  on carta_trips using gin (title gin_trgm_ops);

-- ---------------------------------------------------------------- full text

-- array_to_string is only STABLE, so the document is assembled in an
-- explicitly IMMUTABLE helper before being fed to a generated column.
create or replace function carta_search_doc(
  p_title text, p_sub_region text, p_summary text, p_tags text[]
) returns tsvector as $fn$
  select setweight(to_tsvector('simple', coalesce(p_title, '')), 'A')
      || setweight(to_tsvector('simple', coalesce(p_sub_region, '')), 'B')
      || setweight(to_tsvector('simple', coalesce(p_summary, '')), 'C')
      || setweight(to_tsvector('simple',
           coalesce((select string_agg(x, ' ') from unnest(coalesce(p_tags, '{}')) as x), '')), 'C');
$fn$ language sql immutable;

alter table carta_trips
  add column if not exists search_vector tsvector
  generated always as (carta_search_doc(title, sub_region, summary, tags)) stored;

create index if not exists carta_trips_search_idx on carta_trips using gin (search_vector);

-- --------------------------------------------------------------- timestamps

create or replace function carta_touch_updated_at() returns trigger as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$ language plpgsql;

drop trigger if exists carta_trips_touch on carta_trips;
create trigger carta_trips_touch before update on carta_trips
  for each row execute function carta_touch_updated_at();

-- -------------------------------------------------------------------- views

create or replace view carta_trip_cards as
select
  t.id, t.title, t.summary, t.sub_region,
  c.name  as country, t.country_code,
  r.name  as region,  t.region_key,
  tt.name as trip_type, tt.slug as trip_type_slug, t.trip_type_id,
  t.duration_days, t.best_period_months, t.best_period_window,
  t.budget_tier, t.budget_total_low_eur, t.budget_total_high_eur,
  t.difficulty, t.difficulty_label, t.fitness_level,
  t.lat, t.lon, t.coord_precision, t.tags,
  t.verify_flag_count, t.volatile_pricing
from carta_trips t
join carta_countries  c  on c.code = t.country_code
join carta_regions    r  on r.key  = t.region_key
join carta_trip_types tt on tt.id  = t.trip_type_id;

create or replace view carta_coverage_matrix as
select c.name as country, c.code as country_code, r.name as region,
       tt.name as trip_type, tt.id as trip_type_id,
       count(t.id) as trip_count
from carta_countries c
cross join carta_trip_types tt
join carta_regions r on r.key = c.region_key
left join carta_trips t on t.country_code = c.code and t.trip_type_id = tt.id
group by c.name, c.code, r.name, tt.name, tt.id;

-- ---------------------------------------------------------------------- RLS
-- Published trip content is public read-only; writes go through the service role.

alter table carta_trips                enable row level security;
alter table carta_trip_days            enable row level security;
alter table carta_trip_budget_lines    enable row level security;
alter table carta_trip_accommodations  enable row level security;
alter table carta_trip_pro_tips        enable row level security;
alter table carta_trip_countries       enable row level security;
alter table carta_countries            enable row level security;
alter table carta_regions              enable row level security;
alter table carta_trip_types           enable row level security;

do $policies$
declare
  tbl text;
  grantees text;
begin
  -- Supabase ships the anon/authenticated roles; a bare Postgres (local test,
  -- CI) does not, so fall back to PUBLIC there instead of failing the migration.
  if exists (select 1 from pg_roles where rolname = 'anon')
     and exists (select 1 from pg_roles where rolname = 'authenticated') then
    grantees := 'anon, authenticated';
  else
    grantees := 'public';
  end if;

  foreach tbl in array array[
    'carta_trips','carta_trip_days','carta_trip_budget_lines',
    'carta_trip_accommodations','carta_trip_pro_tips','carta_trip_countries',
    'carta_countries','carta_regions','carta_trip_types'
  ] loop
    execute format('drop policy if exists %I on %I', tbl || '_public_read', tbl);
    execute format(
      'create policy %I on %I for select to %s using (true)',
      tbl || '_public_read', tbl, grantees);
  end loop;
end;
$policies$;
