"""Add 65 new gem destinations to complete the thin countries (2026-07-12).

Follows the exact recipe of add_istria_gems.py (the shape every gem goes
through), generalized:

  1. Coordinates are SNAPPED from Wikipedia (prop=coordinates, batched):
     the hand-written lat/lon is only a sanity cross-check; if Wikipedia
     disagrees by >40 km we warn loudly and keep the Wikipedia value.
  2. Base record: routes copied from the anchor airport's own Ryanair fare
     calendar (when it has one) + ground-transport fields; costs/accommodation
     reused from the anchor (country-level blocks, same as every other gem).
  3. `no_ryanair_route` mirrors fix_data's semantics - unreachable by BOTH
     flight and drive: False when the anchor has fares, else False when the
     drive from home (Brussels) is road-connected and <= max_drive_km, else True
     (Iceland/Faroe/Aland/Moldova stay honestly unreachable, like gem:vik).
  4. image/activities/beauty left None - filled by the resumable
     harvest_images.py / harvest_activities.py / apply_beauty_layer.py runs.

Only patches app_data/app_data.json (master). public/ is regenerated by
continent-app's sync-data step on the next build.

Usage: python add_thin_country_gems.py
"""
import copy
import json
import math
import urllib.parse
import urllib.request
from pathlib import Path

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))  # pipeline/ (car_layer etc.)
import car_layer

ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / "app_data" / "app_data.json"

WIKI_API = "https://en.wikipedia.org/w/api.php"
UA = {"User-Agent": "carta-travel-app/1.0 (data pipeline; coordinate check)"}

# slug, city (display), wiki (title for coord snap), country, iso2, lat, lon,
# categories (existing vocab only), blurb, anchor (IATA), minutes, eur
NEW_GEMS = [
    # ── Denmark (3 -> 9) ────────────────────────────────────────────────────
    dict(slug="aarhus", city="Aarhus", wiki="Aarhus", country="Denmark", iso2="DK",
         lat=56.1629, lon=10.2039, categories=["city", "art", "historic", "food"],
         blurb="Denmark's second city - the ARoS rainbow walkway, Latin Quarter lanes and Viking roots",
         anchor="BLL", minutes=95, eur=18),
    dict(slug="odense", city="Odense", wiki="Odense", country="Denmark", iso2="DK",
         lat=55.4038, lon=10.4024, categories=["city", "historic", "fairytale", "family"],
         blurb="Hans Christian Andersen's storybook hometown on the island of Funen",
         anchor="BLL", minutes=70, eur=14),
    dict(slug="skagen", city="Skagen", wiki="Skagen", country="Denmark", iso2="DK",
         lat=57.7209, lon=10.5839, categories=["coast", "beach", "art", "nature", "quiet"],
         blurb="Two seas collide off the Grenen sandbar, in the luminous light that drew Denmark's painters",
         anchor="AAL", minutes=105, eur=18),
    dict(slug="ribe", city="Ribe", wiki="Ribe", country="Denmark", iso2="DK",
         lat=55.3308, lon=8.7666, categories=["town", "medieval", "historic", "quiet"],
         blurb="Denmark's oldest town - crooked 16th-century houses and Wadden Sea birdlife",
         anchor="BLL", minutes=60, eur=12),
    dict(slug="roskilde", city="Roskilde", wiki="Roskilde", country="Denmark", iso2="DK",
         lat=55.6415, lon=12.0803, categories=["town", "unesco", "cathedral", "historic", "music"],
         blurb="UNESCO cathedral of Danish kings and a fjord-side Viking Ship Museum",
         anchor="CPH", minutes=35, eur=10),
    dict(slug="mons-klint", city="Møns Klint", wiki="Møns Klint", country="Denmark", iso2="DK",
         lat=54.9670, lon=12.5470, categories=["nature", "coast", "iconic", "quiet"],
         blurb="Gleaming 120 m chalk cliffs above improbably turquoise Baltic water",
         anchor="CPH", minutes=120, eur=22),
    # ── Estonia (4 -> 6) ────────────────────────────────────────────────────
    dict(slug="lahemaa", city="Lahemaa National Park", wiki="Lahemaa National Park", country="Estonia", iso2="EE",
         lat=59.5333, lon=25.7333, categories=["national-park", "nature", "coast", "wilderness", "quiet"],
         blurb="Bogs on boardwalks, boulder beaches and manor houses an hour from Tallinn",
         anchor="TLL", minutes=60, eur=12),
    dict(slug="haapsalu", city="Haapsalu", wiki="Haapsalu", country="Estonia", iso2="EE",
         lat=58.9431, lon=23.5414, categories=["town", "spa", "coast", "historic", "quiet"],
         blurb="Wooden-lace houses, a bishop's castle and a famously warm, shallow bay",
         anchor="TLL", minutes=100, eur=15),
    # ── Latvia (4 -> 7) ─────────────────────────────────────────────────────
    dict(slug="kuldiga", city="Kuldīga", wiki="Kuldīga", country="Latvia", iso2="LV",
         lat=56.9677, lon=21.9617, categories=["town", "unesco", "historic", "fairytale", "quiet"],
         blurb="UNESCO old town beside the Venta rapid - Europe's widest waterfall",
         anchor="RIX", minutes=150, eur=20),
    dict(slug="rundale", city="Rundāle Palace", wiki="Rundāle Palace", country="Latvia", iso2="LV",
         lat=56.4139, lon=24.0242, categories=["castle", "baroque", "art", "countryside"],
         blurb="Latvia's Versailles - a Rastrelli baroque palace amid rose gardens",
         anchor="RIX", minutes=80, eur=14),
    dict(slug="liepaja", city="Liepāja", wiki="Liepāja", country="Latvia", iso2="LV",
         lat=56.5047, lon=21.0108, categories=["city", "beach", "coast", "music", "historic"],
         blurb="White-sand Baltic beach city with the haunting Karosta naval quarter",
         anchor="RIX", minutes=200, eur=24),
    # ── Lithuania (6 -> 8) ──────────────────────────────────────────────────
    dict(slug="kernave", city="Kernavė", wiki="Kernavė", country="Lithuania", iso2="LT",
         lat=54.8878, lon=24.8474, categories=["unesco", "historic", "ruins", "countryside", "quiet"],
         blurb="UNESCO hill-fort mounds above the Neris - Lithuania's medieval first capital",
         anchor="VNO", minutes=45, eur=10),
    dict(slug="druskininkai", city="Druskininkai", wiki="Druskininkai", country="Lithuania", iso2="LT",
         lat=54.0169, lon=23.9713, categories=["spa", "town", "nature", "family", "quiet"],
         blurb="Pine-forest spa resort of mineral baths, lakes and a year-round snow arena",
         anchor="VNO", minutes=110, eur=16),
    # ── Kosovo (1 -> 3) ─────────────────────────────────────────────────────
    dict(slug="prizren", city="Prizren", wiki="Prizren", country="Kosovo", iso2="XK",
         lat=42.2139, lon=20.7397, categories=["town", "ottoman", "medieval", "historic"],
         blurb="Ottoman bridges, mosques and a hilltop fortress above Kosovo's prettiest old town",
         anchor="PRN", minutes=85, eur=12),
    dict(slug="peja", city="Peja & Rugova Canyon", wiki="Peja", country="Kosovo", iso2="XK",
         lat=42.6598, lon=20.2888, categories=["town", "mountains", "nature", "monastery", "unesco"],
         blurb="Gateway to the Rugova Canyon via ferrata and the UNESCO Patriarchate monastery",
         anchor="PRN", minutes=85, eur=12),
    # ── North Macedonia (2 -> 4) ────────────────────────────────────────────
    dict(slug="matka", city="Matka Canyon", wiki="Matka Canyon", country="North Macedonia", iso2="MK",
         lat=41.9520, lon=21.3000, categories=["nature", "lake", "adventure", "monastery", "quiet"],
         blurb="Cliff-walled canyon lake with cave boat trips, minutes from Skopje",
         anchor="SKP", minutes=30, eur=8),
    dict(slug="bitola", city="Bitola", wiki="Bitola", country="North Macedonia", iso2="MK",
         lat=41.0311, lon=21.3403, categories=["city", "ottoman", "roman", "ruins", "historic"],
         blurb="Consular boulevards, an Ottoman bazaar and the mosaics of Heraclea Lyncestis",
         anchor="OHD", minutes=70, eur=12),
    # ── Cyprus (2 -> 7) ─────────────────────────────────────────────────────
    dict(slug="troodos", city="Troodos Mountains", wiki="Troodos Mountains", country="Cyprus", iso2="CY",
         lat=34.9333, lon=32.8833, categories=["mountains", "village", "wine", "monastery", "unesco", "nature"],
         blurb="Painted UNESCO churches, Kykkos monastery and wine villages under Cyprus's peaks",
         anchor="PFO", minutes=75, eur=14),
    dict(slug="polis-akamas", city="Polis & Akamas", wiki="Polis, Cyprus", country="Cyprus", iso2="CY",
         lat=35.0367, lon=32.4264, categories=["coast", "beach", "nature", "national-park", "quiet"],
         blurb="Laid-back Polis and the wild Akamas peninsula - turtle beaches and the Blue Lagoon",
         anchor="PFO", minutes=45, eur=10),
    dict(slug="nicosia", city="Nicosia", wiki="Nicosia", country="Cyprus", iso2="CY",
         lat=35.1856, lon=33.3823, categories=["city", "historic", "ottoman", "art"],
         blurb="The world's last divided capital - Venetian walls and a walk-through Green Line crossing",
         anchor="PFO", minutes=95, eur=16),
    dict(slug="ayia-napa", city="Ayia Napa & Cape Greco", wiki="Ayia Napa", country="Cyprus", iso2="CY",
         lat=34.9880, lon=34.0130, categories=["beach", "party", "coast", "nature", "nightlife"],
         blurb="Nissi Beach sands and the sea caves of Cape Greco national forest park",
         anchor="PFO", minutes=120, eur=18),
    dict(slug="limassol", city="Limassol", wiki="Limassol", country="Cyprus", iso2="CY",
         lat=34.7071, lon=33.0226, categories=["city", "beach", "nightlife", "roman", "historic"],
         blurb="Seafront promenade, old-port nightlife and ancient Kourion's clifftop theatre",
         anchor="PFO", minutes=45, eur=10),
    # ── Faroe Islands (2 -> 5) ──────────────────────────────────────────────
    dict(slug="gjogv", city="Gjógv", wiki="Gjógv", country="Faroe Islands", iso2="FO",
         lat=62.3236, lon=-6.9340, categories=["village", "fjord", "nature", "remote", "iconic", "quiet"],
         blurb="Turf-roofed village around a natural gorge harbour, under Slættaratindur",
         anchor="FAE", minutes=50, eur=12),
    dict(slug="saksun", city="Saksun", wiki="Saksun", country="Faroe Islands", iso2="FO",
         lat=62.2497, lon=-7.1764, categories=["village", "nature", "remote", "iconic", "quiet"],
         blurb="An amphitheatre of cliffs around a tidal lagoon and one sod-roofed hamlet",
         anchor="FAE", minutes=45, eur=10),
    dict(slug="mykines", city="Mykines", wiki="Mykines, Faroe Islands", country="Faroe Islands", iso2="FO",
         lat=62.1030, lon=-7.6420, categories=["island", "nature", "remote", "wilderness", "summer-only"],
         blurb="The puffin island - a ridge-walk to a lighthouse at the archipelago's western edge",
         anchor="FAE", minutes=60, eur=25),
    # ── Iceland (4 -> 8) ────────────────────────────────────────────────────
    dict(slug="snaefellsnes", city="Snæfellsnes", wiki="Snæfellsnes", country="Iceland", iso2="IS",
         lat=64.8930, lon=-23.7050, categories=["nature", "coast", "volcanic", "iconic", "wilderness"],
         blurb="Iceland in miniature - Kirkjufell, black churches, lava fields and a glacier-capped volcano",
         anchor="KEF", minutes=150, eur=25),
    dict(slug="golden-circle", city="Golden Circle (Þingvellir)", wiki="Þingvellir", country="Iceland", iso2="IS",
         lat=64.2559, lon=-21.1295, categories=["nature", "national-park", "unesco", "iconic", "volcanic"],
         blurb="Þingvellir's continental rift, Geysir's eruptions and the double falls of Gullfoss",
         anchor="KEF", minutes=70, eur=15),
    dict(slug="jokulsarlon", city="Jökulsárlón", wiki="Jökulsárlón", country="Iceland", iso2="IS",
         lat=64.0784, lon=-16.2306, categories=["nature", "iconic", "wilderness", "remote"],
         blurb="Icebergs calve off Europe's biggest glacier and wash up on black Diamond Beach",
         anchor="KEF", minutes=300, eur=40),
    dict(slug="myvatn", city="Lake Mývatn", wiki="Mývatn", country="Iceland", iso2="IS",
         lat=65.6039, lon=-16.9961, categories=["lake", "volcanic", "nature", "wilderness", "northern-lights"],
         blurb="Pseudocraters, boiling mud at Hverir and geothermal baths without Blue Lagoon crowds",
         anchor="AEY", minutes=75, eur=14),
    # ── Bosnia and Herzegovina (4 -> 8) ─────────────────────────────────────
    dict(slug="blagaj", city="Blagaj", wiki="Blagaj", country="Bosnia and Herzegovina", iso2="BA",
         lat=43.2572, lon=17.8878, categories=["village", "ottoman", "monastery", "nature", "quiet"],
         blurb="A dervish house pressed under a 200 m cliff where the Buna river bursts out",
         anchor="SJJ", minutes=140, eur=16),
    dict(slug="pocitelj", city="Počitelj", wiki="Počitelj", country="Bosnia and Herzegovina", iso2="BA",
         lat=43.1353, lon=17.7328, categories=["village", "ottoman", "medieval", "fortress", "historic", "quiet"],
         blurb="Stone Ottoman village stacked in a rocky amphitheatre above the Neretva",
         anchor="SJJ", minutes=150, eur=17),
    dict(slug="jajce", city="Jajce", wiki="Jajce", country="Bosnia and Herzegovina", iso2="BA",
         lat=44.3420, lon=17.2700, categories=["town", "medieval", "fortress", "nature", "historic"],
         blurb="A 20 m waterfall in the town centre, watermills and a royal hilltop fortress",
         anchor="SJJ", minutes=150, eur=17),
    dict(slug="bihac-una", city="Bihać & Una Falls", wiki="Bihać", country="Bosnia and Herzegovina", iso2="BA",
         lat=44.8169, lon=15.8708, categories=["nature", "national-park", "adventure", "quiet"],
         blurb="Emerald Una rapids, rafting and the thundering Štrbački buk cascades",
         anchor="BNX", minutes=150, eur=17),
    # ── Montenegro (4 -> 8) ─────────────────────────────────────────────────
    dict(slug="durmitor", city="Durmitor (Žabljak)", wiki="Žabljak", country="Montenegro", iso2="ME",
         lat=43.1550, lon=19.1226, categories=["mountains", "national-park", "unesco", "nature", "adventure", "skiing"],
         blurb="Black Lake, 2,500 m Dinaric peaks and the Tara canyon - Europe's deepest",
         anchor="TGD", minutes=130, eur=16),
    dict(slug="perast", city="Perast", wiki="Perast", country="Montenegro", iso2="ME",
         lat=42.4864, lon=18.6980, categories=["town", "coast", "baroque", "unesco", "iconic", "quiet"],
         blurb="Two islet churches float off a one-street baroque town in the Bay of Kotor",
         anchor="TIV", minutes=20, eur=8),
    dict(slug="sveti-stefan", city="Sveti Stefan", wiki="Sveti Stefan", country="Montenegro", iso2="ME",
         lat=42.2561, lon=18.8911, categories=["island", "coast", "beach", "luxury", "iconic"],
         blurb="The postcard islet-resort tied to pink-pebble beaches on the Budva riviera",
         anchor="TIV", minutes=40, eur=10),
    dict(slug="ulcinj", city="Ulcinj", wiki="Ulcinj", country="Montenegro", iso2="ME",
         lat=41.9294, lon=19.2244, categories=["town", "beach", "coast", "ottoman"],
         blurb="Ottoman old town above 13 km of Velika Plaža sand and steady kite-surf wind",
         anchor="TGD", minutes=80, eur=12),
    # ── Albania (4 -> 8) ────────────────────────────────────────────────────
    dict(slug="theth", city="Theth & Albanian Alps", wiki="Theth", country="Albania", iso2="AL",
         lat=42.3947, lon=19.7710, categories=["mountains", "village", "nature", "wilderness", "adventure", "remote"],
         blurb="Stone lock-in towers, the Blue Eye spring and the Valbona pass in the Accursed Mountains",
         anchor="TIA", minutes=180, eur=22),
    dict(slug="himara", city="Himara", wiki="Himarë", country="Albania", iso2="AL",
         lat=40.1017, lon=19.7447, categories=["coast", "beach", "village", "quiet"],
         blurb="Riviera coves - Gjipe, Livadhi, Porto Palermo - without Ksamil's crowds",
         anchor="TIA", minutes=220, eur=25),
    dict(slug="kruje", city="Krujë", wiki="Krujë", country="Albania", iso2="AL",
         lat=41.5089, lon=19.7928, categories=["town", "historic", "ottoman", "fortress", "medieval"],
         blurb="Skanderbeg's citadel and a working Ottoman bazaar on the mountainside above Tirana",
         anchor="TIA", minutes=40, eur=8),
    dict(slug="shkoder", city="Shkodër", wiki="Shkodër", country="Albania", iso2="AL",
         lat=42.0683, lon=19.5126, categories=["city", "lake", "historic", "ottoman"],
         blurb="Rozafa castle views over lake, rivers and minarets - gateway to the Albanian Alps",
         anchor="TIA", minutes=90, eur=12),
    # ── Serbia (2 -> 5) ─────────────────────────────────────────────────────
    dict(slug="novi-sad", city="Novi Sad", wiki="Novi Sad", country="Serbia", iso2="RS",
         lat=45.2551, lon=19.8452, categories=["city", "fortress", "historic", "music", "wine"],
         blurb="Petrovaradin fortress (home of EXIT festival), Danube beaches and Fruška Gora wineries",
         anchor="BEG", minutes=80, eur=12),
    dict(slug="uvac", city="Uvac Canyon", wiki="Uvac (river)", country="Serbia", iso2="RS",
         lat=43.3153, lon=19.8783, categories=["nature", "iconic", "wilderness", "remote"],
         blurb="Emerald river meanders folded into limestone, patrolled by griffon vultures",
         anchor="BEG", minutes=240, eur=28),
    dict(slug="mokra-gora", city="Mokra Gora & Tara", wiki="Mokra Gora", country="Serbia", iso2="RS",
         lat=43.7936, lon=19.5069, categories=["mountains", "village", "nature", "family"],
         blurb="The Šargan Eight heritage railway, Kusturica's timber Drvengrad and Tara's viewpoints",
         anchor="BEG", minutes=200, eur=24),
    # ── Slovakia (6 -> 9) ───────────────────────────────────────────────────
    dict(slug="bojnice", city="Bojnice", wiki="Bojnice", country="Slovakia", iso2="SK",
         lat=48.7797, lon=18.5758, categories=["castle", "fairytale", "town", "family", "spa"],
         blurb="Slovakia's fairytale castle - turrets, moat and Europe's oldest zoo next door",
         anchor="BTS", minutes=150, eur=18),
    dict(slug="slovak-paradise", city="Slovak Paradise", wiki="Slovak Paradise", country="Slovakia", iso2="SK",
         lat=48.9186, lon=20.4172, categories=["national-park", "nature", "adventure", "hiking", "wilderness"],
         blurb="Ladder-and-chain gorge trails up waterfalls above the Hornád canyon",
         anchor="KSC", minutes=90, eur=14),
    dict(slug="vlkolinec", city="Vlkolínec", wiki="Vlkolínec", country="Slovakia", iso2="SK",
         lat=49.0392, lon=19.2775, categories=["village", "unesco", "historic", "mountains", "quiet"],
         blurb="A perfectly preserved UNESCO hamlet of 45 painted log houses",
         anchor="BTS", minutes=210, eur=24),
    # ── Bulgaria (6 -> 10) ──────────────────────────────────────────────────
    dict(slug="bansko", city="Bansko", wiki="Bansko", country="Bulgaria", iso2="BG",
         lat=41.8383, lon=23.4885, categories=["mountains", "skiing", "town", "national-park", "nature"],
         blurb="Budget ski slopes under UNESCO Pirin peaks, with a stone-house old town",
         anchor="SOF", minutes=150, eur=18),
    dict(slug="koprivshtitsa", city="Koprivshtitsa", wiki="Koprivshtitsa", country="Bulgaria", iso2="BG",
         lat=42.6367, lon=24.3592, categories=["village", "historic", "fairytale", "quiet"],
         blurb="A whole town of colour-washed National Revival houses frozen in 1876",
         anchor="SOF", minutes=110, eur=14),
    dict(slug="melnik", city="Melnik", wiki="Melnik, Bulgaria", country="Bulgaria", iso2="BG",
         lat=41.5242, lon=23.3963, categories=["village", "wine", "nature", "quiet"],
         blurb="Bulgaria's smallest town - sand pyramids, wine cellars and broad-shouldered reds",
         anchor="SOF", minutes=170, eur=20),
    dict(slug="nesebar", city="Nesebar", wiki="Nesebar", country="Bulgaria", iso2="BG",
         lat=42.6589, lon=27.7361, categories=["town", "unesco", "beach", "coast", "medieval", "byzantine"],
         blurb="UNESCO peninsula old town of Byzantine churches beside Sunny Beach sands",
         anchor="BOJ", minutes=40, eur=8),
    # ── Hungary (7 -> 9) ────────────────────────────────────────────────────
    dict(slug="szentendre", city="Szentendre", wiki="Szentendre", country="Hungary", iso2="HU",
         lat=47.6690, lon=19.0755, categories=["town", "art", "baroque", "historic", "quiet"],
         blurb="Artists' town of Balkan-baroque lanes on the Danube Bend, an HÉV ride from Budapest",
         anchor="BUD", minutes=45, eur=8),
    dict(slug="tokaj", city="Tokaj", wiki="Tokaj", country="Hungary", iso2="HU",
         lat=48.1180, lon=21.4083, categories=["wine", "town", "unesco", "countryside", "quiet"],
         blurb="The UNESCO wine region of golden aszú - cellars carved into volcanic hills",
         anchor="BUD", minutes=180, eur=22),
    # ── Finland (7 -> 9) ────────────────────────────────────────────────────
    dict(slug="rauma", city="Rauma", wiki="Rauma, Finland", country="Finland", iso2="FI",
         lat=61.1281, lon=21.5110, categories=["town", "unesco", "historic", "coast", "quiet"],
         blurb="Old Rauma - the Nordics' largest wooden old town, all lace and pastel",
         anchor="HEL", minutes=210, eur=26),
    dict(slug="aland", city="Åland (Mariehamn)", wiki="Mariehamn", country="Finland", iso2="FI",
         lat=60.0971, lon=19.9348, categories=["islands", "sailing", "nature", "summer-only", "quiet"],
         blurb="An autonomous archipelago of 6,700 islands - cycling, red granite and maritime calm",
         anchor="TKU", minutes=300, eur=35),
    # ── Sweden (8 -> 10) ────────────────────────────────────────────────────
    dict(slug="uppsala", city="Uppsala", wiki="Uppsala", country="Sweden", iso2="SE",
         lat=59.8586, lon=17.6389, categories=["city", "university", "cathedral", "historic"],
         blurb="Scandinavia's oldest university, its grandest cathedral and Viking burial mounds",
         anchor="ARN", minutes=25, eur=8),
    dict(slug="vaxholm", city="Stockholm Archipelago (Vaxholm)", wiki="Vaxholm", country="Sweden", iso2="SE",
         lat=59.4021, lon=18.3515, categories=["islands", "sailing", "coast", "family", "quiet"],
         blurb="Gateway to 30,000 skerries - wooden villas, a sea fortress and island-hopping ferries",
         anchor="ARN", minutes=60, eur=12),
    # ── Czechia (9 -> 10) ───────────────────────────────────────────────────
    dict(slug="bohemian-switzerland", city="Bohemian Switzerland", wiki="Bohemian Switzerland", country="Czechia", iso2="CZ",
         lat=50.8730, lon=14.2320, categories=["national-park", "nature", "iconic", "hiking", "wilderness"],
         blurb="Pravčická gate - Europe's largest sandstone arch - and gorge boat rides at Hřensko",
         anchor="PRG", minutes=105, eur=15),
    # ── Luxembourg (1 -> 3) ─────────────────────────────────────────────────
    dict(slug="vianden", city="Vianden", wiki="Vianden", country="Luxembourg", iso2="LU",
         lat=49.9350, lon=6.2081, categories=["castle", "village", "medieval", "fairytale", "nature"],
         blurb="A storybook castle over slate roofs in the Our valley - Hugo's exile hideout",
         anchor="LUX", minutes=45, eur=10),
    dict(slug="echternach", city="Echternach & Mullerthal", wiki="Echternach", country="Luxembourg", iso2="LU",
         lat=49.8117, lon=6.4217, categories=["town", "abbey", "nature", "hiking", "historic"],
         blurb="Basilica town on the Mullerthal Trail - mossy gorges of 'Little Switzerland'",
         anchor="LUX", minutes=35, eur=8),
    # ── Malta (1 -> 3) ──────────────────────────────────────────────────────
    dict(slug="gozo", city="Gozo", wiki="Gozo", country="Malta", iso2="MT",
         lat=36.0443, lon=14.2512, categories=["island", "historic", "beach", "diving", "unesco", "quiet"],
         blurb="Slower sister island - Ġgantija's 5,500-year-old temples, red sands and dive sites",
         anchor="MLA", minutes=75, eur=12),
    dict(slug="mdina", city="Mdina", wiki="Mdina", country="Malta", iso2="MT",
         lat=35.8867, lon=14.4028, categories=["town", "medieval", "historic", "iconic", "quiet"],
         blurb="The Silent City - lamplit honey-stone lanes and bastion views over half of Malta",
         anchor="MLA", minutes=30, eur=6),
    # ── Belgium (8 -> 10) ───────────────────────────────────────────────────
    dict(slug="ypres", city="Ypres", wiki="Ypres", country="Belgium", iso2="BE",
         lat=50.8510, lon=2.8857, categories=["town", "memorial", "historic", "quiet"],
         blurb="The rebuilt Cloth Hall and the Last Post, sounded at the Menin Gate every evening",
         anchor="BRU", minutes=90, eur=14),
    dict(slug="bouillon", city="Bouillon", wiki="Bouillon", country="Belgium", iso2="BE",
         lat=49.7936, lon=5.0670, categories=["castle", "village", "medieval", "nature", "quiet"],
         blurb="Godfrey's crusader castle above a horseshoe bend of the Semois",
         anchor="BRU", minutes=110, eur=16),
    # ── Moldova (1 -> 2) ────────────────────────────────────────────────────
    dict(slug="orheiul-vechi", city="Orheiul Vechi", wiki="Orheiul Vechi", country="Moldova", iso2="MD",
         lat=47.3053, lon=28.9700, categories=["monastery", "nature", "historic", "remote", "quiet"],
         blurb="Cave monastery carved into a limestone ridge above a Răut river loop",
         anchor="KIV", minutes=50, eur=10),
]

MAX_SNAP_KM = 40.0


def haversine_km(lat1, lon1, lat2, lon2):
    r = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def snap_coordinates(gems):
    """Batch-fetch Wikipedia coordinates for every gem's wiki title and snap
    lat/lon to them (warn when the hand-written guess was >MAX_SNAP_KM off)."""
    titles = [g["wiki"] for g in gems]
    coords = {}
    for i in range(0, len(titles), 50):
        batch = titles[i:i + 50]
        q = urllib.parse.urlencode({
            "action": "query", "prop": "coordinates", "titles": "|".join(batch),
            "redirects": 1, "coprimary": "primary", "format": "json", "colimit": "max",
        })
        req = urllib.request.Request(f"{WIKI_API}?{q}", headers=UA)
        with urllib.request.urlopen(req, timeout=30) as resp:
            j = json.load(resp)
        # map normalized/redirected titles back to what we asked for
        back = {}
        for entry in (j["query"].get("normalized") or []) + (j["query"].get("redirects") or []):
            back[entry["to"]] = back.get(entry["from"], entry["from"])
        for page in j["query"]["pages"].values():
            asked = back.get(page.get("title"), page.get("title"))
            cc = (page.get("coordinates") or [{}])[0]
            if cc.get("lat") is not None:
                coords[asked] = (cc["lat"], cc["lon"])

    for g in gems:
        got = coords.get(g["wiki"])
        if not got:
            print(f"  [coords] {g['city']}: no Wikipedia coordinates - keeping hand-written value")
            continue
        d = haversine_km(g["lat"], g["lon"], got[0], got[1])
        if d > MAX_SNAP_KM:
            print(f"  [coords] WARNING {g['city']}: guess was {d:.0f} km off Wikipedia - using Wikipedia ({got[0]:.4f},{got[1]:.4f})")
        g["lat"], g["lon"] = round(got[0], 4), round(got[1], 4)


def build_record(spec, dests, home, max_drive_km):
    anchor = dests[spec["anchor"]]
    routes = {}
    for origin, route in (anchor.get("routes") or {}).items():
        r = copy.deepcopy(route)
        r["anchor_airport"] = spec["anchor"]
        r["ground_transport_one_way_eur"] = spec["eur"]
        r["ground_transport_minutes"] = spec["minutes"]
        routes[origin] = r
    anchor_has_fares = any((r.get("outbound_fare") or {}) for r in routes.values())

    local_transport = car_layer.local_transport_for(
        spec["city"], spec["iso2"], "gem", spec["categories"]
    )

    # fix_data semantics: no_ryanair_route == unreachable by BOTH flight and drive.
    if anchor_has_fares:
        unreachable = False
    else:
        road_km = haversine_km(home["lat"], home["lon"], spec["lat"], spec["lon"]) * 1.3
        drivable = local_transport.get("road_connected", True) and road_km <= max_drive_km
        unreachable = not drivable

    return {
        "id": f"gem:{spec['slug']}",
        "tier": "gem",
        "iata": None,
        "city": spec["city"],
        "country": spec["country"],
        "iso2": spec["iso2"],
        "lat": spec["lat"],
        "lon": spec["lon"],
        "categories": spec["categories"],
        "tags": [],
        "blurb": spec["blurb"],
        "no_ryanair_route": unreachable,
        "anchor_airport": spec["anchor"],
        "transfer": None,
        "routes": routes,
        "costs": copy.deepcopy(anchor["costs"]),
        "accommodation": copy.deepcopy(anchor["accommodation"]),
        "local_transport": local_transport,
        "beauty": None,      # apply_beauty_layer.py
        "image": None,       # harvest_images.py
        "activities": None,  # harvest_activities.py
    }


def main():
    data = json.loads(MASTER.read_text(encoding="utf-8"))
    dests = data["destinations"]
    home = data["meta"]["home"]
    max_drive_km = (data["meta"].get("car_model") or {}).get("max_drive_km", 3500)

    missing_anchor = [g["slug"] for g in NEW_GEMS if g["anchor"] not in dests]
    if missing_anchor:
        raise SystemExit(f"unknown anchor airports for: {missing_anchor}")

    print(f"Snapping coordinates for {len(NEW_GEMS)} gems from Wikipedia...")
    snap_coordinates(NEW_GEMS)

    added, skipped = [], []
    for spec in NEW_GEMS:
        did = f"gem:{spec['slug']}"
        if did in dests:
            skipped.append(did)
            continue
        dests[did] = build_record(spec, dests, home, max_drive_km)
        added.append(did)

    data["meta"]["n_destinations"] = len(dests)
    MASTER.write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"added {len(added)} gems ({len(skipped)} already present) -> {len(dests)} total destinations")
    for did in added:
        v = dests[did]
        print(f"  {did}: {v['city']}, {v['country']} (anchor {v['anchor_airport']}, "
              f"{'bookable' if v['routes'] and not v['no_ryanair_route'] else 'drive/browse' if not v['no_ryanair_route'] else 'unreachable-browse'})")


if __name__ == "__main__":
    main()
