"""Add 12 famous small destinations that were missing from the catalogue
(2026-07-13): Makarska, Sibenik, Lago Maggiore (Stresa) and friends.

Follows the exact recipe of add_thin_country_gems.py:
  1. Coordinates snapped from Wikipedia (prop=coordinates, batched).
  2. Base record: routes copied from the anchor airport's own Ryanair fare
     calendar + ground-transport fields; costs/accommodation reused from the
     anchor; local_transport from car_layer.
  3. image/activities/beauty left None, filled by the resumable
     harvest_images.py / harvest_activities.py / apply_beauty_layer.py runs.

Only patches app_data/app_data.json (master). public/ is regenerated by
continent-app's sync-data step on the next build.

Usage: python add_famous_small_gems.py
"""
import copy
import json
import math
import urllib.parse
import urllib.request
from pathlib import Path

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))  # pipeline/ (car_layer etc.)
import car_layer

ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / "app_data" / "app_data.json"

WIKI_API = "https://en.wikipedia.org/w/api.php"
UA = {"User-Agent": "carta-travel-app/1.0 (data pipeline; coordinate check)"}

# slug, city (display), wiki (title for coord snap), country, iso2, lat, lon,
# categories (existing vocab only), blurb (no dashes), anchor (IATA), minutes, eur
NEW_GEMS = [
    # ── Croatia: the Dalmatian towns travellers actually ask for ───────────
    dict(slug="makarska", city="Makarska", wiki="Makarska", country="Croatia", iso2="HR",
         lat=43.2969, lon=17.0178, categories=["town", "beach", "coast", "nature"],
         blurb="Riviera beach town squeezed between the Biokovo cliffs and a palm-lined bay",
         anchor="SPU", minutes=75, eur=12),
    dict(slug="sibenik", city="Šibenik", wiki="Šibenik", country="Croatia", iso2="HR",
         lat=43.7350, lon=15.8898, categories=["town", "unesco", "cathedral", "historic", "coast"],
         blurb="Stone lanes and a UNESCO cathedral, with Krka's waterfalls just upriver",
         anchor="SPU", minutes=60, eur=10),
    # ── Italy: the lake the user asked about + three southern icons ────────
    dict(slug="lago-maggiore", city="Lago Maggiore (Stresa)", wiki="Stresa", country="Italy", iso2="IT",
         lat=45.8846, lon=8.5321, categories=["lake", "luxury", "nature", "romantic"],
         blurb="Belle epoque lakefront with boats out to the Borromean island palaces",
         anchor="MXP", minutes=45, eur=10),
    dict(slug="taormina", city="Taormina", wiki="Taormina", country="Italy", iso2="IT",
         lat=37.8516, lon=15.2853, categories=["town", "historic", "iconic", "coast", "romantic"],
         blurb="An ancient Greek theatre with Etna smoking behind the Ionian blue",
         anchor="CTA", minutes=70, eur=12),
    dict(slug="capri", city="Capri", wiki="Capri", country="Italy", iso2="IT",
         lat=40.5532, lon=14.2222, categories=["island", "luxury", "iconic", "coast"],
         blurb="The Blue Grotto, the Faraglioni rocks and Italy's most glamorous little island",
         anchor="NAP", minutes=100, eur=25),
    dict(slug="tropea", city="Tropea", wiki="Tropea", country="Italy", iso2="IT",
         lat=38.6767, lon=15.8983, categories=["town", "beach", "coast", "iconic"],
         blurb="A cliff-top old town above one of Italy's most photographed beaches",
         anchor="LMZ", minutes=45, eur=10),
    # ── France ──────────────────────────────────────────────────────────────
    dict(slug="cassis", city="Cassis", wiki="Cassis", country="France", iso2="FR",
         lat=43.2140, lon=5.5390, categories=["village", "coast", "nature", "romantic"],
         blurb="A pastel fishing port at the mouth of the calanque fjords",
         anchor="MRS", minutes=40, eur=10),
    dict(slug="menton", city="Menton", wiki="Menton", country="France", iso2="FR",
         lat=43.7745, lon=7.4970, categories=["town", "coast", "romantic", "quiet"],
         blurb="Lemon-yellow old town on the Italian border, the Riviera at its calmest",
         anchor="NCE", minutes=40, eur=8),
    dict(slug="bonifacio", city="Bonifacio", wiki="Bonifacio, Corse-du-Sud", country="France", iso2="FR",
         lat=41.3871, lon=9.1595, categories=["town", "fortress", "coast", "iconic"],
         blurb="A white limestone citadel balanced over the strait to Sardinia",
         anchor="FSC", minutes=30, eur=8),
    # ── Greece ──────────────────────────────────────────────────────────────
    dict(slug="hydra", city="Hydra", wiki="Hydra (island)", country="Greece", iso2="GR",
         lat=37.3510, lon=23.4650, categories=["island", "historic", "romantic", "quiet"],
         blurb="A car-free island of stone mansions where donkeys do the deliveries",
         anchor="ATH", minutes=120, eur=25),
    # ── Spain ───────────────────────────────────────────────────────────────
    dict(slug="nerja", city="Nerja", wiki="Nerja", country="Spain", iso2="ES",
         lat=36.7599, lon=-3.8810, categories=["town", "beach", "coast"],
         blurb="The Balcon de Europa lookout, cliff coves and vast show caves",
         anchor="AGP", minutes=60, eur=10),
    dict(slug="besalu", city="Besalú", wiki="Besalú", country="Spain", iso2="ES",
         lat=42.1989, lon=2.6996, categories=["village", "medieval", "historic", "quiet"],
         blurb="A fortified Romanesque bridge opening into one of Catalonia's best medieval cores",
         anchor="GRO", minutes=40, eur=8),
]

MAX_SNAP_KM = 40.0


def haversine_km(lat1, lon1, lat2, lon2):
    r = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def snap_coordinates(gems):
    titles = [g["wiki"] for g in gems]
    coords = {}
    for i in range(0, len(titles), 50):
        batch = titles[i:i + 50]
        q = urllib.parse.urlencode({
            "action": "query", "prop": "coordinates", "titles": "|".join(batch),
            "redirects": 1, "coprimary": "primary", "format": "json", "colimit": "max",
        })
        req = urllib.request.Request(f"{WIKI_API}?{q}", headers=UA)
        with urllib.request.urlopen(req, timeout=30) as resp:
            j = json.load(resp)
        back = {}
        for entry in (j["query"].get("normalized") or []) + (j["query"].get("redirects") or []):
            back[entry["to"]] = back.get(entry["from"], entry["from"])
        for page in j["query"]["pages"].values():
            asked = back.get(page.get("title"), page.get("title"))
            cc = (page.get("coordinates") or [{}])[0]
            if cc.get("lat") is not None:
                coords[asked] = (cc["lat"], cc["lon"])

    for g in gems:
        got = coords.get(g["wiki"])
        if not got:
            print(f"  [coords] {g['city']}: no Wikipedia coordinates, keeping hand-written value")
            continue
        d = haversine_km(g["lat"], g["lon"], got[0], got[1])
        if d > MAX_SNAP_KM:
            print(f"  [coords] WARNING {g['city']}: guess was {d:.0f} km off Wikipedia, using Wikipedia ({got[0]:.4f},{got[1]:.4f})")
        g["lat"], g["lon"] = round(got[0], 4), round(got[1], 4)


def build_record(spec, dests, home, max_drive_km):
    anchor = dests[spec["anchor"]]
    routes = {}
    for origin, route in (anchor.get("routes") or {}).items():
        r = copy.deepcopy(route)
        r["anchor_airport"] = spec["anchor"]
        r["ground_transport_one_way_eur"] = spec["eur"]
        r["ground_transport_minutes"] = spec["minutes"]
        routes[origin] = r
    anchor_has_fares = any((r.get("outbound_fare") or {}) for r in routes.values())

    local_transport = car_layer.local_transport_for(
        spec["city"], spec["iso2"], "gem", spec["categories"]
    )

    if anchor_has_fares:
        unreachable = False
    else:
        road_km = haversine_km(home["lat"], home["lon"], spec["lat"], spec["lon"]) * 1.3
        drivable = local_transport.get("road_connected", True) and road_km <= max_drive_km
        unreachable = not drivable

    return {
        "id": f"gem:{spec['slug']}",
        "tier": "gem",
        "iata": None,
        "city": spec["city"],
        "country": spec["country"],
        "iso2": spec["iso2"],
        "lat": spec["lat"],
        "lon": spec["lon"],
        "categories": spec["categories"],
        "tags": [],
        "blurb": spec["blurb"],
        "no_ryanair_route": unreachable,
        "anchor_airport": spec["anchor"],
        "transfer": None,
        "routes": routes,
        "costs": copy.deepcopy(anchor["costs"]),
        "accommodation": copy.deepcopy(anchor["accommodation"]),
        "local_transport": local_transport,
        "beauty": None,      # apply_beauty_layer.py
        "image": None,       # harvest_images.py
        "activities": None,  # harvest_activities.py
    }


def main():
    data = json.loads(MASTER.read_text(encoding="utf-8"))
    dests = data["destinations"]
    home = data["meta"]["home"]
    max_drive_km = (data["meta"].get("car_model") or {}).get("max_drive_km", 3500)

    missing_anchor = [g["slug"] for g in NEW_GEMS if g["anchor"] not in dests]
    if missing_anchor:
        raise SystemExit(f"unknown anchor airports for: {missing_anchor}")

    print(f"Snapping coordinates for {len(NEW_GEMS)} gems from Wikipedia...")
    snap_coordinates(NEW_GEMS)

    added, skipped = [], []
    for spec in NEW_GEMS:
        did = f"gem:{spec['slug']}"
        if did in dests:
            skipped.append(did)
            continue
        dests[did] = build_record(spec, dests, home, max_drive_km)
        added.append(did)

    data["meta"]["n_destinations"] = len(dests)
    MASTER.write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"added {len(added)} gems ({len(skipped)} already present) -> {len(dests)} total destinations")
    for did in added:
        v = dests[did]
        print(f"  {did}: {v['city']}, {v['country']} (anchor {v['anchor_airport']}, "
              f"{'bookable' if v['routes'] and not v['no_ryanair_route'] else 'drive/browse' if not v['no_ryanair_route'] else 'unreachable-browse'})")


if __name__ == "__main__":
    main()
