#!/usr/bin/env bash
# The whole layer, every country, in the one order that works.
#
# Not a replacement for build_cycling.py: that is the supported entry point
# and it takes the same steps. This exists because a full-Europe pass is an
# overnight job that has to survive being watched, and each stage here logs
# to its own file so a failure is legible without re-running its predecessor.
#
# THE ORDER IS THE POINT, and every one of these was learned by getting it
# wrong first:
#
#   splice BEFORE enrich    services attached to a discontinuous line get no
#                           position along it at all, and the stage planner
#                           then has nothing to cut at.
#   landcover BEFORE scenic scenic reads the land-cover table; running it
#                           first means every route drops the component and
#                           renormalises, which is honest and useless.
#   elevation BEFORE sync   elevation measures the ORIGINAL relation, so the
#                           splice has to rescale the spans afterwards or a
#                           route states a length shorter than the line it
#                           ships.
#   near BEFORE scenic      the catalogue component reads it.
#
# One country at a time inside each stage, because two concurrent extract
# passes put this Postgres into crash recovery once already.
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by byte
# offset as it executes, so an edit in flight makes it resume at the wrong
# place: editing this line during a run re-ran a stage that had just failed,
# which looked like a retry loop and was actually the shell reading a file
# that had moved under it. Stop the run, edit, restart.
set -u
cd "$(dirname "$0")/../.." || exit 1
L=pipeline/logs
mkdir -p "$L"

run () {                      # run <logname> <command...>
  local name="$1"; shift
  echo "=== $name : $(date +%H:%M:%S) ===" | tee -a "$L/cycling_all.log"
  "$@" > "$L/cycling_$name.log" 2>&1
  local rc=$?
  echo "    $name exit=$rc $(date +%H:%M:%S)" | tee -a "$L/cycling_all.log"
  return 0                    # never abandon the rest of the run for one stage
}

PY=python

# splice and the fast enrichment are already done for all 43 countries; both
# are idempotent, so a re-run is cheap insurance rather than repeated work.
run splice_all      $PY pipeline/cycling/splice_cycling.py
run enrich_fast     $PY pipeline/cycling/enrich_cycling.py --steps regions,surface,safety
# Smallest extract first, and --max-gb defers the big five to their own run.
# Area assembly is MEMORY bound, not disk bound, and that did not change when
# the disk did: Austria at 0.81 GB sat at 1.26 GB resident, so France at
# 4.7 GB is several times that on a shared machine. Banking 38 countries
# beats dying on Germany with thirty untouched.
run landcover_all   $PY pipeline/cycling/landcover.py --max-gb 1.5
run enrich_services $PY pipeline/cycling/enrich_cycling.py --steps services,routeservices
run enrich_ele      $PY pipeline/cycling/enrich_cycling.py --steps elevation
run splice_sync     $PY pipeline/cycling/splice_cycling.py --sync-only
run enrich_scenic   $PY pipeline/cycling/enrich_cycling.py --steps near,scenic --refresh
run photos          $PY pipeline/cycling/cycle_images.py
run crosscheck      $PY pipeline/cycling/harvest_cycling.py --crosscheck
run rate            $PY pipeline/cycling/cycle_index.py
run tours           $PY pipeline/cycling/stage_planner.py
run validate        $PY pipeline/cycling/validate_cycling.py --verbose
run export          $PY pipeline/cycling/export_cycling.py

echo "=== done $(date +%H:%M:%S) ===" | tee -a "$L/cycling_all.log"
